//# -*- indent-tabs-mode: nil  c-basic-offset: 2 -*-
//###########################################################################
//# PROJECT: Waters
//# PACKAGE: net.sourceforge.waters.model.marshaller
//# CLASS:   WatersUnmarshalException
//###########################################################################
//# $Id: WatersUnmarshalException.java,v 1.3 2006-02-20 22:20:21 robi Exp $
//###########################################################################

package net.sourceforge.waters.model.marshaller;

import java.io.File;
import java.net.URI;

import net.sourceforge.waters.model.base.WatersException;


/**
 * An exception indicating that reading or importing Waters data structures
 * from a file has failed. This exception is typically used to wrap
 * exceptions generated by other packages into a {@link WatersException}.
 *
 * @author Robi Malik
 */

public class WatersUnmarshalException extends WatersException {

  //#########################################################################
  //# Constructors
  /**
   * Constructs a new exception with <CODE>null</CODE> as its detail message.
   */
  public WatersUnmarshalException()
  {
  }

  /**
   * Constructs a new exception with the specified cause. The detail
   * message will be <CODE>(cause==null ? null : cause.toString())</CODE>
   * (which typically contains the class and detail message of cause).
   */
  public WatersUnmarshalException(final Throwable cause)
  {
    super(cause);
  }

  /**
   * Constructs a new exception with the specified detail message.
   */
  public WatersUnmarshalException(final String message)
  {
    super(message);
  }

  /**
   * Constructs a new exception with the specified detail message and cause.
   */
  public WatersUnmarshalException(final String message,
                                  final Throwable cause) 
  {
    super(message, cause);
  }

  /**
   * Constructs a new exception indicating that the specified URI
   * cannot be accessed.
   */
  public WatersUnmarshalException(final URI uri)
  {
    this("Failed to open '" + uri + "'!");
  }

  /**
   * Constructs a new exception indicating that the specified URI
   * cannot be accessed, with a specified cause.
   */
  public WatersUnmarshalException(final URI uri, final Throwable cause)
  {
    super("Failed to open '" + uri + "'" +
          (cause == null ? "!" : ": " + cause));
  }

  /**
   * Constructs a new exception indicating that the specified file
   * cannot be loaded.
   */
  public WatersUnmarshalException(final File filename)
  {
    this("Failed to load file '" + filename + "'!");
  }

  /**
   * Constructs a new exception indicating that the specified file
   * cannot be loaded, with a specified cause.
   */
  public WatersUnmarshalException(final File filename, final Throwable cause)
  {
    super("Failed to load file '" + filename + "'" +
          (cause == null ? "!" : ": " + cause));
  }

}
