//# -*- indent-tabs-mode: nil  c-basic-offset: 2 -*-
//###########################################################################
//# PROJECT: Waters
//# PACKAGE: net.sourceforge.waters.model.marshaller
//# CLASS:   WatersMarshalException
//###########################################################################
//# $Id: WatersMarshalException.java,v 1.2 2005-11-03 01:24:16 robi Exp $
//###########################################################################

package net.sourceforge.waters.model.marshaller;

import java.io.File;

import net.sourceforge.waters.model.base.WatersException;


/**
 * An exception indicating that writing or exporting Waters data structures
 * to a file has failed. This exception is typically used to wrap
 * exceptions generated by other packages into a {@link WatersException}.
 *
 * @author Robi Malik
 */

public class WatersMarshalException extends WatersException {

  //#########################################################################
  //# Constructors
  /**
   * Constructs a new exception with <CODE>null</CODE> as its detail message.
   */
  public WatersMarshalException()
  {
  }

  /**
   * Constructs a new exception with the specified cause. The detail
   * message will be <CODE>(cause==null ? null : cause.toString())</CODE>
   * (which typically contains the class and detail message of cause).
   */
  public WatersMarshalException(final Throwable cause)
  {
    super(cause);
  }

  /**
   * Constructs a new exception with the specified detail message.
   */
  public WatersMarshalException(final String message)
  {
    super(message);
  }

  /**
   * Constructs a new exception with the specified detail message and cause.
   */
  public WatersMarshalException(final String message, final Throwable cause) 
  {
    super(message, cause);
  }

  /**
   * Constructs a new exception indicating that the specified file
   * cannot be loaded.
   */
  public WatersMarshalException(final File filename)
  {
    this("Failed to write file '" + filename + "'!");
  }

  /**
   * Constructs a new exception indicating that the specified file
   * cannot be written, with a specified cause.
   */
  public WatersMarshalException(final File filename, final Throwable cause)
  {
    super("Failed to write file '" + filename + "'" +
          (cause == null ? "!" : cause));
  }

}
