//# -*- indent-tabs-mode: nil  c-basic-offset: 2 -*-
//###########################################################################
//# PROJECT: Waters
//# PACKAGE: net.sourceforge.waters.plain.module
//# CLASS:   EdgeElement
//###########################################################################
//# $Id$
//###########################################################################
//# THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY A SCRIPT.
//# DO NOT EDIT.
//###########################################################################

package net.sourceforge.waters.plain.module;

import net.sourceforge.waters.model.base.Proxy;
import net.sourceforge.waters.model.base.ProxyTools;
import net.sourceforge.waters.model.base.ProxyVisitor;
import net.sourceforge.waters.model.base.VisitorException;
import net.sourceforge.waters.model.module.EdgeProxy;
import net.sourceforge.waters.model.module.GuardActionBlockProxy;
import net.sourceforge.waters.model.module.LabelBlockProxy;
import net.sourceforge.waters.model.module.ModuleProxyVisitor;
import net.sourceforge.waters.model.module.NodeProxy;
import net.sourceforge.waters.model.module.PointGeometryProxy;
import net.sourceforge.waters.model.module.SplineGeometryProxy;
import net.sourceforge.waters.plain.base.Element;


/**
 * An immutable implementation of the {@link EdgeProxy} interface.
 *
 * @author Robi Malik
 */

public final class EdgeElement
  extends Element
  implements EdgeProxy
{

  //#########################################################################
  //# Constructors
  /**
   * Creates a new edge.
   * @param source The source node of the new edge, or <CODE>null</CODE>.
   * @param target The target node of the new edge, or <CODE>null</CODE>.
   * @param labelBlock The label block of the new edge, or <CODE>null</CODE> if empty.
   * @param guardActionBlock The guard action block of the new edge, or <CODE>null</CODE>.
   * @param geometry The rendering information of the new edge, or <CODE>null</CODE>.
   * @param startPoint The rendering information for the start point of the new edge, or <CODE>null</CODE>.
   * @param endPoint The rendering information for the end point of the new edge, or <CODE>null</CODE>.
   */
  public EdgeElement(final NodeProxy source,
                     final NodeProxy target,
                     final LabelBlockProxy labelBlock,
                     final GuardActionBlockProxy guardActionBlock,
                     final SplineGeometryProxy geometry,
                     final PointGeometryProxy startPoint,
                     final PointGeometryProxy endPoint)
  {
    mSource = source;
    mTarget = target;
    if (labelBlock == null) {
      mLabelBlock = new LabelBlockElement();
    } else {
      mLabelBlock = labelBlock;
    }
    mGuardActionBlock = guardActionBlock;
    mGeometry = geometry;
    mStartPoint = startPoint;
    mEndPoint = endPoint;
  }

  /**
   * Creates a new edge using default values.
   * This constructor creates an edge with
   * the source node set to <CODE>null</CODE>,
   * the target node set to <CODE>null</CODE>,
   * an empty label block,
   * the guard action block set to <CODE>null</CODE>,
   * the rendering information set to <CODE>null</CODE>,
   * the rendering information for the start point set to <CODE>null</CODE>, and
   * the rendering information for the end point set to <CODE>null</CODE>.
   */
  public EdgeElement()
  {
    this(null,
         null,
         null,
         null,
         null,
         null,
         null);
  }


  //#########################################################################
  //# Cloning
  public EdgeElement clone()
  {
    return (EdgeElement) super.clone();
  }


  //#########################################################################
  //# Equality and Hashcode
  public Class<EdgeProxy> getProxyInterface()
  {
    return EdgeProxy.class;
  }

  public boolean equalsByContents(final Proxy partner)
  {
    if (super.equalsByContents(partner)) {
      final EdgeProxy downcast = (EdgeProxy) partner;
      return
        ProxyTools.equalsByContents(mSource, downcast.getSource()) &&
        ProxyTools.equalsByContents(mTarget, downcast.getTarget()) &&
        mLabelBlock.equalsByContents(downcast.getLabelBlock()) &&
        ProxyTools.equalsByContents(mGuardActionBlock, downcast.getGuardActionBlock());
    } else {
      return false;
    }
  }

  public boolean equalsWithGeometry(final Proxy partner)
  {
    if (super.equalsByContents(partner)) {
      final EdgeProxy downcast = (EdgeProxy) partner;
      return
        ProxyTools.equalsWithGeometry(mSource, downcast.getSource()) &&
        ProxyTools.equalsWithGeometry(mTarget, downcast.getTarget()) &&
        mLabelBlock.equalsWithGeometry(downcast.getLabelBlock()) &&
        ProxyTools.equalsWithGeometry(mGuardActionBlock, downcast.getGuardActionBlock()) &&
        ProxyTools.equalsWithGeometry(mGeometry, downcast.getGeometry()) &&
        ProxyTools.equalsWithGeometry(mStartPoint, downcast.getStartPoint()) &&
        ProxyTools.equalsWithGeometry(mEndPoint, downcast.getEndPoint());
    } else {
      return false;
    }
  }

  public int hashCodeByContents()
  {
    int result = super.hashCodeByContents();
    result *= 5;
    result += ProxyTools.hashCodeByContents(mSource);
    result *= 5;
    result += ProxyTools.hashCodeByContents(mTarget);
    result *= 5;
    result += mLabelBlock.hashCodeByContents();
    result *= 5;
    result += ProxyTools.hashCodeByContents(mGuardActionBlock);
    return result;
  }

  public int hashCodeWithGeometry()
  {
    int result = super.hashCodeByContents();
    result *= 5;
    result += ProxyTools.hashCodeWithGeometry(mSource);
    result *= 5;
    result += ProxyTools.hashCodeWithGeometry(mTarget);
    result *= 5;
    result += mLabelBlock.hashCodeWithGeometry();
    result *= 5;
    result += ProxyTools.hashCodeWithGeometry(mGuardActionBlock);
    result *= 5;
    result += ProxyTools.hashCodeWithGeometry(mGeometry);
    result *= 5;
    result += ProxyTools.hashCodeWithGeometry(mStartPoint);
    result *= 5;
    result += ProxyTools.hashCodeWithGeometry(mEndPoint);
    return result;
  }


  //#########################################################################
  //# Interface net.sourceforge.waters.model.base.Proxy
  public Object acceptVisitor(final ProxyVisitor visitor)
    throws VisitorException
  {
    final ModuleProxyVisitor downcast = (ModuleProxyVisitor) visitor;
    return downcast.visitEdgeProxy(this);
  }


  //#########################################################################
  //# Interface net.sourceforge.waters.model.module.EdgeProxy
  public NodeProxy getSource()
  {
    return mSource;
  }

  public NodeProxy getTarget()
  {
    return mTarget;
  }

  public LabelBlockProxy getLabelBlock()
  {
    return mLabelBlock;
  }

  public GuardActionBlockProxy getGuardActionBlock()
  {
    return mGuardActionBlock;
  }

  public SplineGeometryProxy getGeometry()
  {
    return mGeometry;
  }

  public PointGeometryProxy getStartPoint()
  {
    return mStartPoint;
  }

  public PointGeometryProxy getEndPoint()
  {
    return mEndPoint;
  }


  //#########################################################################
  //# Data Members
  private final NodeProxy mSource;
  private final NodeProxy mTarget;
  private final LabelBlockProxy mLabelBlock;
  private final GuardActionBlockProxy mGuardActionBlock;
  private final SplineGeometryProxy mGeometry;
  private final PointGeometryProxy mStartPoint;
  private final PointGeometryProxy mEndPoint;

}
