//# -*- indent-tabs-mode: nil  c-basic-offset: 2 -*-
//###########################################################################
//# PROJECT: Waters
//# PACKAGE: net.sourceforge.waters.plain.module
//# CLASS:   ForeachEventElement
//###########################################################################
//# $Id$
//###########################################################################
//# THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY A SCRIPT.
//# DO NOT EDIT.
//###########################################################################

package net.sourceforge.waters.plain.module;

import java.util.Collection;

import net.sourceforge.waters.model.base.Proxy;
import net.sourceforge.waters.model.base.ProxyVisitor;
import net.sourceforge.waters.model.base.VisitorException;
import net.sourceforge.waters.model.module.ForeachEventProxy;
import net.sourceforge.waters.model.module.ModuleProxyVisitor;
import net.sourceforge.waters.model.module.SimpleExpressionProxy;


/**
 * An immutable implementation of the {@link ForeachEventProxy} interface.
 *
 * @author Robi Malik
 */

public final class ForeachEventElement
  extends ForeachElement
  implements ForeachEventProxy
{

  //#########################################################################
  //# Constructors
  /**
   * Creates a new foreach construct for events.
   * @param name The name of the new foreach construct for events.
   * @param range The range of the new foreach construct for events.
   * @param guard The guard of the new foreach construct for events, or <CODE>null</CODE>.
   * @param body The body of the new foreach construct for events, or <CODE>null</CODE> if empty.
   */
  public ForeachEventElement(final String name,
                             final SimpleExpressionProxy range,
                             final SimpleExpressionProxy guard,
                             final Collection<? extends Proxy> body)
  {
    super(name, range, guard, body);
  }

  /**
   * Creates a new foreach construct for events using default values.
   * This constructor creates a foreach construct for events with
   * the guard set to <CODE>null</CODE> and
   * an empty body.
   * @param name The name of the new foreach construct for events.
   * @param range The range of the new foreach construct for events.
   */
  public ForeachEventElement(final String name,
                             final SimpleExpressionProxy range)
  {
    this(name,
         range,
         null,
         null);
  }


  //#########################################################################
  //# Cloning
  public ForeachEventElement clone()
  {
    return (ForeachEventElement) super.clone();
  }


  //#########################################################################
  //# Equality and Hashcode
  public Class<ForeachEventProxy> getProxyInterface()
  {
    return ForeachEventProxy.class;
  }


  //#########################################################################
  //# Interface net.sourceforge.waters.model.base.Proxy
  public Object acceptVisitor(final ProxyVisitor visitor)
    throws VisitorException
  {
    final ModuleProxyVisitor downcast = (ModuleProxyVisitor) visitor;
    return downcast.visitForeachEventProxy(this);
  }

}
