//# -*- indent-tabs-mode: nil  c-basic-offset: 2 -*-
//###########################################################################
//# THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY A SCRIPT.
//# DO NOT EDIT.
//###########################################################################
//# Copyright (C) 2004-2023 Robi Malik
//###########################################################################
//# This file is part of Waters.
//# Waters is free software: you can redistribute it and/or modify it under
//# the terms of the GNU General Public License as published by the Free
//# Software Foundation, either version 2 of the License, or (at your option)
//# any later version.
//# Waters is distributed in the hope that it will be useful, but WITHOUT ANY
//# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
//# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
//# details.
//# You should have received a copy of the GNU General Public License along
//# with Waters. If not, see <http://www.gnu.org/licenses/>.
//#
//# Linking Waters statically or dynamically with other modules is making a
//# combined work based on Waters. Thus, the terms and conditions of the GNU
//# General Public License cover the whole combination.
//# In addition, as a special exception, the copyright holders of Waters give
//# you permission to combine Waters with code included in the standard
//# release of Supremica under the Supremica Software License Agreement (or
//# modified versions of such code, with unchanged license). You may copy and
//# distribute such a system following the terms of the GNU GPL for Waters and
//# the licenses of the other code concerned.
//# Note that people who make modified versions of Waters are not obligated to
//# grant this special exception for their modified versions; it is their
//# choice whether to do so. The GNU General Public License gives permission
//# to release a modified version without this exception; this exception also
//# makes it possible to release a modified version which carries forward this
//# exception.
//###########################################################################

package net.sourceforge.waters.plain.module;

import java.util.Collection;

import net.sourceforge.waters.model.base.Proxy;
import net.sourceforge.waters.model.base.ProxyVisitor;
import net.sourceforge.waters.model.base.VisitorException;
import net.sourceforge.waters.model.module.ForeachProxy;
import net.sourceforge.waters.model.module.ModuleProxyVisitor;
import net.sourceforge.waters.model.module.SimpleExpressionProxy;


/**
 * An immutable implementation of the {@link ForeachProxy} interface.
 *
 * @author Robi Malik
 */

public final class ForeachElement
  extends NestedBlockElement
  implements ForeachProxy
{

  //#########################################################################
  //# Constructors
  /**
   * Creates a new foreach construct.
   * @param body The list of body objects of the new foreach construct, or <CODE>null</CODE> if empty.
   * @param name The name of the dummy variable of the new foreach construct.
   * @param range The range of the new foreach construct.
   */
  public ForeachElement(final Collection<? extends Proxy> body,
                        final String name,
                        final SimpleExpressionProxy range)
  {
    super(body);
    mName = name;
    mRange = range;
  }

  /**
   * Creates a new foreach construct using default values.
   * This constructor creates a foreach construct with
   * an empty list of body objects.
   * @param name The name of the dummy variable of the new foreach construct.
   * @param range The range of the new foreach construct.
   */
  public ForeachElement(final String name,
                        final SimpleExpressionProxy range)
  {
    this(null,
         name,
         range);
  }


  //#########################################################################
  //# Cloning
  @Override
  public ForeachElement clone()
  {
    return (ForeachElement) super.clone();
  }


  //#########################################################################
  //# Comparing
  public Class<ForeachProxy> getProxyInterface()
  {
    return ForeachProxy.class;
  }


  //#########################################################################
  //# Interface net.sourceforge.waters.model.base.Proxy
  public Object acceptVisitor(final ProxyVisitor visitor)
    throws VisitorException
  {
    final ModuleProxyVisitor downcast = (ModuleProxyVisitor) visitor;
    return downcast.visitForeachProxy(this);
  }


  //#########################################################################
  //# Interface net.sourceforge.waters.model.module.ForeachProxy
  public String getName()
  {
    return mName;
  }

  public SimpleExpressionProxy getRange()
  {
    return mRange;
  }


  //#########################################################################
  //# Data Members
  private final String mName;
  private final SimpleExpressionProxy mRange;


  //#########################################################################
  //# Class Constants
  private static final long serialVersionUID = 5561734081433945027L;

}
