//# -*- indent-tabs-mode: nil  c-basic-offset: 2 -*-
//###########################################################################
//# PROJECT: Waters
//# PACKAGE: net.sourceforge.waters.plain.module
//# CLASS:   IntConstantElement
//###########################################################################
//# $Id$
//###########################################################################
//# THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY A SCRIPT.
//# DO NOT EDIT.
//###########################################################################

package net.sourceforge.waters.plain.module;

import net.sourceforge.waters.model.base.ProxyVisitor;
import net.sourceforge.waters.model.base.VisitorException;
import net.sourceforge.waters.model.module.IntConstantProxy;
import net.sourceforge.waters.model.module.ModuleProxyVisitor;


/**
 * An immutable implementation of the {@link IntConstantProxy} interface.
 *
 * @author Robi Malik
 */

public final class IntConstantElement
  extends SimpleExpressionElement
  implements IntConstantProxy
{

  //#########################################################################
  //# Constructors
  /**
   * Creates a new integer constant.
   * @param plainText The original text of the new integer constant, or <CODE>null</CODE>.
   * @param value The integer value of the new integer constant.
   */
  public IntConstantElement(final String plainText,
                            final int value)
  {
    super(plainText);
    mValue = value;
  }

  /**
   * Creates a new integer constant using default values.
   * This constructor creates an integer constant with
   * the original text set to <CODE>null</CODE>.
   * @param value The integer value of the new integer constant.
   */
  public IntConstantElement(final int value)
  {
    this(null,
         value);
  }


  //#########################################################################
  //# Cloning
  public IntConstantElement clone()
  {
    return (IntConstantElement) super.clone();
  }


  //#########################################################################
  //# Comparing
  public Class<IntConstantProxy> getProxyInterface()
  {
    return IntConstantProxy.class;
  }


  //#########################################################################
  //# Interface net.sourceforge.waters.model.base.Proxy
  public Object acceptVisitor(final ProxyVisitor visitor)
    throws VisitorException
  {
    final ModuleProxyVisitor downcast = (ModuleProxyVisitor) visitor;
    return downcast.visitIntConstantProxy(this);
  }


  //#########################################################################
  //# Interface net.sourceforge.waters.model.module.IntConstantProxy
  public int getValue()
  {
    return mValue;
  }


  //#########################################################################
  //# Data Members
  private final int mValue;


  //#########################################################################
  //# Class Constants
  private static final long serialVersionUID = 6146767186819894411L;

}
