//# -*- indent-tabs-mode: nil  c-basic-offset: 2 -*-
//###########################################################################
//# THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY A SCRIPT.
//# DO NOT EDIT.
//###########################################################################
//# Copyright (C) 2004-2018 Robi Malik
//###########################################################################
//# This file is part of Waters.
//# Waters is free software: you can redistribute it and/or modify it under
//# the terms of the GNU General Public License as published by the Free
//# Software Foundation, either version 2 of the License, or (at your option)
//# any later version.
//# Waters is distributed in the hope that it will be useful, but WITHOUT ANY
//# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
//# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
//# details.
//# You should have received a copy of the GNU General Public License along
//# with Waters. If not, see <http://www.gnu.org/licenses/>.
//#
//# Linking Waters statically or dynamically with other modules is making a
//# combined work based on Waters. Thus, the terms and conditions of the GNU
//# General Public License cover the whole combination.
//# In addition, as a special exception, the copyright holders of Waters give
//# you permission to combine Waters with code included in the standard
//# release of Supremica under the Supremica Software License Agreement (or
//# modified versions of such code, with unchanged license). You may copy and
//# distribute such a system following the terms of the GNU GPL for Waters and
//# the licenses of the other code concerned.
//# Note that people who make modified versions of Waters are not obligated to
//# grant this special exception for their modified versions; it is their
//# choice whether to do so. The GNU General Public License gives permission
//# to release a modified version without this exception; this exception also
//# makes it possible to release a modified version which carries forward this
//# exception.
//###########################################################################

package net.sourceforge.waters.plain.module;

import java.awt.geom.Point2D;

import net.sourceforge.waters.model.base.ProxyVisitor;
import net.sourceforge.waters.model.base.VisitorException;
import net.sourceforge.waters.model.module.LabelGeometryProxy;
import net.sourceforge.waters.model.module.ModuleProxyVisitor;
import net.sourceforge.waters.plain.base.GeometryElement;

import net.sourceforge.waters.xsd.module.AnchorPosition;


/**
 * An immutable implementation of the {@link LabelGeometryProxy} interface.
 *
 * @author Robi Malik
 */

public final class LabelGeometryElement
  extends GeometryElement
  implements LabelGeometryProxy
{

  //#########################################################################
  //# Constructors
  /**
   * Creates a new label geometry.
   * @param offset The offset of the new label geometry.
   * @param anchor The anchor position of the new label geometry.
   */
  public LabelGeometryElement(final Point2D offset,
                              final AnchorPosition anchor)
  {
    mOffset = (Point2D) offset.clone();
    mAnchor = anchor;
  }

  /**
   * Creates a new label geometry using default values.
   * This constructor creates a label geometry with
   * the anchor position set to <CODE>AnchorPosition.NW</CODE>.
   * @param offset The offset of the new label geometry.
   */
  public LabelGeometryElement(final Point2D offset)
  {
    this(offset,
         AnchorPosition.NW);
  }


  //#########################################################################
  //# Cloning
  @Override
  public LabelGeometryElement clone()
  {
    return (LabelGeometryElement) super.clone();
  }


  //#########################################################################
  //# Comparing
  public Class<LabelGeometryProxy> getProxyInterface()
  {
    return LabelGeometryProxy.class;
  }


  //#########################################################################
  //# Interface net.sourceforge.waters.model.base.Proxy
  public Object acceptVisitor(final ProxyVisitor visitor)
    throws VisitorException
  {
    final ModuleProxyVisitor downcast = (ModuleProxyVisitor) visitor;
    return downcast.visitLabelGeometryProxy(this);
  }


  //#########################################################################
  //# Interface net.sourceforge.waters.model.module.LabelGeometryProxy
  public Point2D getOffset()
  {
    return (Point2D) mOffset.clone();
  }

  public AnchorPosition getAnchor()
  {
    return mAnchor;
  }


  //#########################################################################
  //# Data Members
  private final Point2D mOffset;
  private final AnchorPosition mAnchor;


  //#########################################################################
  //# Class Constants
  private static final long serialVersionUID = -1337175543808520293L;

}
