//# -*- indent-tabs-mode: nil  c-basic-offset: 2 -*-
//###########################################################################
//# THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY A SCRIPT.
//# DO NOT EDIT.
//###########################################################################
//# Copyright (C) 2004-2023 Robi Malik
//###########################################################################
//# This file is part of Waters.
//# Waters is free software: you can redistribute it and/or modify it under
//# the terms of the GNU General Public License as published by the Free
//# Software Foundation, either version 2 of the License, or (at your option)
//# any later version.
//# Waters is distributed in the hope that it will be useful, but WITHOUT ANY
//# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
//# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
//# details.
//# You should have received a copy of the GNU General Public License along
//# with Waters. If not, see <http://www.gnu.org/licenses/>.
//#
//# Linking Waters statically or dynamically with other modules is making a
//# combined work based on Waters. Thus, the terms and conditions of the GNU
//# General Public License cover the whole combination.
//# In addition, as a special exception, the copyright holders of Waters give
//# you permission to combine Waters with code included in the standard
//# release of Supremica under the Supremica Software License Agreement (or
//# modified versions of such code, with unchanged license). You may copy and
//# distribute such a system following the terms of the GNU GPL for Waters and
//# the licenses of the other code concerned.
//# Note that people who make modified versions of Waters are not obligated to
//# grant this special exception for their modified versions; it is their
//# choice whether to do so. The GNU General Public License gives permission
//# to release a modified version without this exception; this exception also
//# makes it possible to release a modified version which carries forward this
//# exception.
//###########################################################################

package net.sourceforge.waters.plain.module;

import java.awt.Color;
import java.awt.geom.Point2D;
import java.awt.geom.Rectangle2D;
import java.net.URI;
import java.util.Collection;
import java.util.Map;

import net.sourceforge.waters.model.base.ComponentKind;
import net.sourceforge.waters.model.base.EventKind;
import net.sourceforge.waters.model.base.Proxy;
import net.sourceforge.waters.model.expr.BinaryOperator;
import net.sourceforge.waters.model.expr.UnaryOperator;
import net.sourceforge.waters.model.module.AnchorPosition;
import net.sourceforge.waters.model.module.BinaryExpressionProxy;
import net.sourceforge.waters.model.module.BoxGeometryProxy;
import net.sourceforge.waters.model.module.ColorGeometryProxy;
import net.sourceforge.waters.model.module.ConstantAliasProxy;
import net.sourceforge.waters.model.module.EdgeProxy;
import net.sourceforge.waters.model.module.EventDeclProxy;
import net.sourceforge.waters.model.module.ExpressionProxy;
import net.sourceforge.waters.model.module.GraphProxy;
import net.sourceforge.waters.model.module.GuardActionBlockProxy;
import net.sourceforge.waters.model.module.IdentifierProxy;
import net.sourceforge.waters.model.module.LabelBlockProxy;
import net.sourceforge.waters.model.module.LabelGeometryProxy;
import net.sourceforge.waters.model.module.ModuleProxy;
import net.sourceforge.waters.model.module.ModuleProxyCloner;
import net.sourceforge.waters.model.module.ModuleProxyFactory;
import net.sourceforge.waters.model.module.NodeProxy;
import net.sourceforge.waters.model.module.ParameterBindingProxy;
import net.sourceforge.waters.model.module.PlainEventListProxy;
import net.sourceforge.waters.model.module.PointGeometryProxy;
import net.sourceforge.waters.model.module.ScopeKind;
import net.sourceforge.waters.model.module.SimpleExpressionProxy;
import net.sourceforge.waters.model.module.SimpleIdentifierProxy;
import net.sourceforge.waters.model.module.SplineGeometryProxy;
import net.sourceforge.waters.model.module.SplineKind;
import net.sourceforge.waters.model.module.VariableMarkingProxy;


public class ModuleElementFactory
  implements ModuleProxyFactory
{

  //#########################################################################
  //# Static Class Methods
  /**
   * Gets the single instance of this class.
   */
  public static ModuleElementFactory getInstance()
  {
    return INSTANCE;
  }

  /**
   * Gets the cloning visitor that can convert Module objects from
   * arbitrary implementations into this implementation.
   */
  public static ModuleProxyCloner getCloningInstance()
  {
    if (CLONING_INSTANCE == null) {
      CLONING_INSTANCE = new ModuleProxyCloner(INSTANCE);
    }
    return CLONING_INSTANCE;
  }


  //#########################################################################
  //# Interface net.sourceforge.waters.model.module.ModuleProxyFactory
  @Override
  public ModuleProxyCloner getCloner()
  {
    return getCloningInstance();
  }

  @Override
  public BinaryExpressionElement createBinaryExpressionProxy
      (final String plainText,
       final BinaryOperator operator,
       final SimpleExpressionProxy left,
       final SimpleExpressionProxy right)
  {
    return new BinaryExpressionElement(plainText,
                                       operator,
                                       left,
                                       right);
  }

  @Override
  public BinaryExpressionElement createBinaryExpressionProxy
      (final BinaryOperator operator,
       final SimpleExpressionProxy left,
       final SimpleExpressionProxy right)
  {
    return new BinaryExpressionElement(operator,
                                       left,
                                       right);
  }

  @Override
  public BoxGeometryElement createBoxGeometryProxy
      (final Rectangle2D rectangle)
  {
    return new BoxGeometryElement(rectangle);
  }

  @Override
  public ColorGeometryElement createColorGeometryProxy
      (final Collection<? extends Color> colorSet)
  {
    return new ColorGeometryElement(colorSet);
  }

  @Override
  public ColorGeometryElement createColorGeometryProxy()
  {
    return new ColorGeometryElement();
  }

  @Override
  public ConditionalElement createConditionalProxy
      (final Collection<? extends Proxy> body,
       final SimpleExpressionProxy guard)
  {
    return new ConditionalElement(body,
                                  guard);
  }

  @Override
  public ConditionalElement createConditionalProxy
      (final SimpleExpressionProxy guard)
  {
    return new ConditionalElement(guard);
  }

  @Override
  public ConstantAliasElement createConstantAliasProxy
      (final IdentifierProxy identifier,
       final ExpressionProxy expression,
       final ScopeKind scope)
  {
    return new ConstantAliasElement(identifier,
                                    expression,
                                    scope);
  }

  @Override
  public ConstantAliasElement createConstantAliasProxy
      (final IdentifierProxy identifier,
       final ExpressionProxy expression)
  {
    return new ConstantAliasElement(identifier,
                                    expression);
  }

  @Override
  public EdgeElement createEdgeProxy
      (final NodeProxy source,
       final NodeProxy target,
       final LabelBlockProxy labelBlock,
       final GuardActionBlockProxy guardActionBlock,
       final SplineGeometryProxy geometry,
       final PointGeometryProxy startPoint,
       final PointGeometryProxy endPoint)
  {
    return new EdgeElement(source,
                           target,
                           labelBlock,
                           guardActionBlock,
                           geometry,
                           startPoint,
                           endPoint);
  }

  @Override
  public EdgeElement createEdgeProxy()
  {
    return new EdgeElement();
  }

  @Override
  public EnumSetExpressionElement createEnumSetExpressionProxy
      (final String plainText,
       final Collection<? extends SimpleIdentifierProxy> items)
  {
    return new EnumSetExpressionElement(plainText,
                                        items);
  }

  @Override
  public EnumSetExpressionElement createEnumSetExpressionProxy
      (final Collection<? extends SimpleIdentifierProxy> items)
  {
    return new EnumSetExpressionElement(items);
  }

  @Override
  public EventAliasElement createEventAliasProxy
      (final IdentifierProxy identifier,
       final ExpressionProxy expression)
  {
    return new EventAliasElement(identifier,
                                 expression);
  }

  @Override
  public EventDeclElement createEventDeclProxy
      (final IdentifierProxy identifier,
       final EventKind kind,
       final boolean observable,
       final ScopeKind scope,
       final Collection<? extends SimpleExpressionProxy> ranges,
       final ColorGeometryProxy colorGeometry,
       final Map<String,String> attributes)
  {
    return new EventDeclElement(identifier,
                                kind,
                                observable,
                                scope,
                                ranges,
                                colorGeometry,
                                attributes);
  }

  @Override
  public EventDeclElement createEventDeclProxy
      (final IdentifierProxy identifier,
       final EventKind kind)
  {
    return new EventDeclElement(identifier,
                                kind);
  }

  @Override
  public ForeachElement createForeachProxy
      (final Collection<? extends Proxy> body,
       final String name,
       final SimpleExpressionProxy range)
  {
    return new ForeachElement(body,
                              name,
                              range);
  }

  @Override
  public ForeachElement createForeachProxy
      (final String name,
       final SimpleExpressionProxy range)
  {
    return new ForeachElement(name,
                              range);
  }

  @Override
  public FunctionCallExpressionElement createFunctionCallExpressionProxy
      (final String plainText,
       final String functionName,
       final Collection<? extends SimpleExpressionProxy> arguments)
  {
    return new FunctionCallExpressionElement(plainText,
                                             functionName,
                                             arguments);
  }

  @Override
  public FunctionCallExpressionElement createFunctionCallExpressionProxy
      (final String functionName,
       final Collection<? extends SimpleExpressionProxy> arguments)
  {
    return new FunctionCallExpressionElement(functionName,
                                             arguments);
  }

  @Override
  public GraphElement createGraphProxy
      (final boolean deterministic,
       final LabelBlockProxy blockedEvents,
       final Collection<? extends NodeProxy> nodes,
       final Collection<? extends EdgeProxy> edges)
  {
    return new GraphElement(deterministic,
                            blockedEvents,
                            nodes,
                            edges);
  }

  @Override
  public GraphElement createGraphProxy()
  {
    return new GraphElement();
  }

  @Override
  public GroupNodeElement createGroupNodeProxy
      (final String name,
       final PlainEventListProxy propositions,
       final Map<String,String> attributes,
       final Collection<? extends NodeProxy> immediateChildNodes,
       final BoxGeometryProxy geometry)
  {
    return new GroupNodeElement(name,
                                propositions,
                                attributes,
                                immediateChildNodes,
                                geometry);
  }

  @Override
  public GroupNodeElement createGroupNodeProxy
      (final String name)
  {
    return new GroupNodeElement(name);
  }

  @Override
  public GuardActionBlockElement createGuardActionBlockProxy
      (final Collection<? extends SimpleExpressionProxy> guards,
       final Collection<? extends BinaryExpressionProxy> actions,
       final LabelGeometryProxy geometry)
  {
    return new GuardActionBlockElement(guards,
                                       actions,
                                       geometry);
  }

  @Override
  public GuardActionBlockElement createGuardActionBlockProxy()
  {
    return new GuardActionBlockElement();
  }

  @Override
  public IndexedIdentifierElement createIndexedIdentifierProxy
      (final String plainText,
       final String name,
       final Collection<? extends SimpleExpressionProxy> indexes)
  {
    return new IndexedIdentifierElement(plainText,
                                        name,
                                        indexes);
  }

  @Override
  public IndexedIdentifierElement createIndexedIdentifierProxy
      (final String name,
       final Collection<? extends SimpleExpressionProxy> indexes)
  {
    return new IndexedIdentifierElement(name,
                                        indexes);
  }

  @Override
  public InstanceElement createInstanceProxy
      (final IdentifierProxy identifier,
       final String moduleName,
       final Collection<? extends ParameterBindingProxy> bindingList)
  {
    return new InstanceElement(identifier,
                               moduleName,
                               bindingList);
  }

  @Override
  public InstanceElement createInstanceProxy
      (final IdentifierProxy identifier,
       final String moduleName)
  {
    return new InstanceElement(identifier,
                               moduleName);
  }

  @Override
  public IntConstantElement createIntConstantProxy
      (final String plainText,
       final int value)
  {
    return new IntConstantElement(plainText,
                                  value);
  }

  @Override
  public IntConstantElement createIntConstantProxy
      (final int value)
  {
    return new IntConstantElement(value);
  }

  @Override
  public LabelBlockElement createLabelBlockProxy
      (final Collection<? extends Proxy> eventIdentifierList,
       final LabelGeometryProxy geometry)
  {
    return new LabelBlockElement(eventIdentifierList,
                                 geometry);
  }

  @Override
  public LabelBlockElement createLabelBlockProxy()
  {
    return new LabelBlockElement();
  }

  @Override
  public LabelGeometryElement createLabelGeometryProxy
      (final Point2D offset,
       final AnchorPosition anchor)
  {
    return new LabelGeometryElement(offset,
                                    anchor);
  }

  @Override
  public LabelGeometryElement createLabelGeometryProxy
      (final Point2D offset)
  {
    return new LabelGeometryElement(offset);
  }

  @Override
  public ModuleElement createModuleProxy
      (final String name,
       final String comment,
       final URI location,
       final Collection<? extends ConstantAliasProxy> constantAliasList,
       final Collection<? extends EventDeclProxy> eventDeclList,
       final Collection<? extends Proxy> eventAliasList,
       final Collection<? extends Proxy> componentList)
  {
    return new ModuleElement(name,
                             comment,
                             location,
                             constantAliasList,
                             eventDeclList,
                             eventAliasList,
                             componentList);
  }

  @Override
  public ModuleElement createModuleProxy
      (final String name,
       final URI location)
  {
    return new ModuleElement(name,
                             location);
  }

  @Override
  public ModuleSequenceElement createModuleSequenceProxy
      (final String name,
       final String comment,
       final URI location,
       final Collection<? extends ModuleProxy> modules)
  {
    return new ModuleSequenceElement(name,
                                     comment,
                                     location,
                                     modules);
  }

  @Override
  public ModuleSequenceElement createModuleSequenceProxy
      (final String name,
       final URI location)
  {
    return new ModuleSequenceElement(name,
                                     location);
  }

  @Override
  public ParameterBindingElement createParameterBindingProxy
      (final String name,
       final ExpressionProxy expression)
  {
    return new ParameterBindingElement(name,
                                       expression);
  }

  @Override
  public PlainEventListElement createPlainEventListProxy
      (final Collection<? extends Proxy> eventIdentifierList)
  {
    return new PlainEventListElement(eventIdentifierList);
  }

  @Override
  public PlainEventListElement createPlainEventListProxy()
  {
    return new PlainEventListElement();
  }

  @Override
  public PointGeometryElement createPointGeometryProxy
      (final Point2D point)
  {
    return new PointGeometryElement(point);
  }

  @Override
  public QualifiedIdentifierElement createQualifiedIdentifierProxy
      (final String plainText,
       final IdentifierProxy baseIdentifier,
       final IdentifierProxy componentIdentifier)
  {
    return new QualifiedIdentifierElement(plainText,
                                          baseIdentifier,
                                          componentIdentifier);
  }

  @Override
  public QualifiedIdentifierElement createQualifiedIdentifierProxy
      (final IdentifierProxy baseIdentifier,
       final IdentifierProxy componentIdentifier)
  {
    return new QualifiedIdentifierElement(baseIdentifier,
                                          componentIdentifier);
  }

  @Override
  public SimpleComponentElement createSimpleComponentProxy
      (final IdentifierProxy identifier,
       final ComponentKind kind,
       final GraphProxy graph,
       final Map<String,String> attributes)
  {
    return new SimpleComponentElement(identifier,
                                      kind,
                                      graph,
                                      attributes);
  }

  @Override
  public SimpleComponentElement createSimpleComponentProxy
      (final IdentifierProxy identifier,
       final ComponentKind kind,
       final GraphProxy graph)
  {
    return new SimpleComponentElement(identifier,
                                      kind,
                                      graph);
  }

  @Override
  public SimpleIdentifierElement createSimpleIdentifierProxy
      (final String plainText,
       final String name)
  {
    return new SimpleIdentifierElement(plainText,
                                       name);
  }

  @Override
  public SimpleIdentifierElement createSimpleIdentifierProxy
      (final String name)
  {
    return new SimpleIdentifierElement(name);
  }

  @Override
  public SimpleNodeElement createSimpleNodeProxy
      (final String name,
       final PlainEventListProxy propositions,
       final Map<String,String> attributes,
       final boolean initial,
       final PointGeometryProxy pointGeometry,
       final PointGeometryProxy initialArrowGeometry,
       final LabelGeometryProxy labelGeometry)
  {
    return new SimpleNodeElement(name,
                                 propositions,
                                 attributes,
                                 initial,
                                 pointGeometry,
                                 initialArrowGeometry,
                                 labelGeometry);
  }

  @Override
  public SimpleNodeElement createSimpleNodeProxy
      (final String name)
  {
    return new SimpleNodeElement(name);
  }

  @Override
  public SplineGeometryElement createSplineGeometryProxy
      (final Collection<? extends Point2D> points,
       final SplineKind kind)
  {
    return new SplineGeometryElement(points,
                                     kind);
  }

  @Override
  public SplineGeometryElement createSplineGeometryProxy()
  {
    return new SplineGeometryElement();
  }

  @Override
  public UnaryExpressionElement createUnaryExpressionProxy
      (final String plainText,
       final UnaryOperator operator,
       final SimpleExpressionProxy subTerm)
  {
    return new UnaryExpressionElement(plainText,
                                      operator,
                                      subTerm);
  }

  @Override
  public UnaryExpressionElement createUnaryExpressionProxy
      (final UnaryOperator operator,
       final SimpleExpressionProxy subTerm)
  {
    return new UnaryExpressionElement(operator,
                                      subTerm);
  }

  @Override
  public VariableComponentElement createVariableComponentProxy
      (final IdentifierProxy identifier,
       final SimpleExpressionProxy type,
       final SimpleExpressionProxy initialStatePredicate,
       final Collection<? extends VariableMarkingProxy> variableMarkings,
       final boolean isInput)
  {
    return new VariableComponentElement(identifier,
                                        type,
                                        initialStatePredicate,
                                        variableMarkings,
                                        isInput);
  }

  @Override
  public VariableComponentElement createVariableComponentProxy
      (final IdentifierProxy identifier,
       final SimpleExpressionProxy type,
       final SimpleExpressionProxy initialStatePredicate)
  {
    return new VariableComponentElement(identifier,
                                        type,
                                        initialStatePredicate,
                                        null,
                                        false);
  }

  @Override
  public VariableMarkingElement createVariableMarkingProxy
      (final IdentifierProxy proposition,
       final SimpleExpressionProxy predicate)
  {
    return new VariableMarkingElement(proposition,
                                      predicate);
  }


  //#########################################################################
  //# Data Members
  private static final ModuleElementFactory INSTANCE =
    new ModuleElementFactory();
  private static ModuleProxyCloner CLONING_INSTANCE;

}
