//# -*- indent-tabs-mode: nil  c-basic-offset: 2 -*-
//###########################################################################
//# PROJECT: Waters
//# PACKAGE: net.sourceforge.waters.plain.module
//# CLASS:   NodeElement
//###########################################################################
//# $Id$
//###########################################################################
//# THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY A SCRIPT.
//# DO NOT EDIT.
//###########################################################################

package net.sourceforge.waters.plain.module;

import net.sourceforge.waters.model.module.NodeProxy;
import net.sourceforge.waters.model.module.PlainEventListProxy;
import net.sourceforge.waters.plain.base.NamedElement;


/**
 * An immutable implementation of the {@link NodeProxy} interface.
 *
 * @author Robi Malik
 */

public abstract class NodeElement
  extends NamedElement
  implements NodeProxy
{

  //#########################################################################
  //# Constructors
  /**
   * Creates a new node.
   * @param name The name of the new node.
   * @param propositions The list of propositions of the new node, or <CODE>null</CODE> if empty.
   */
  protected NodeElement(final String name,
                        final PlainEventListProxy propositions)
  {
    super(name);
    if (propositions == null) {
      mPropositions = new PlainEventListElement();
    } else {
      mPropositions = propositions;
    }
  }

  /**
   * Creates a new node using default values.
   * This constructor creates a node with
   * an empty list of propositions.
   * @param name The name of the new node.
   */
  protected NodeElement(final String name)
  {
    this(name,
         null);
  }


  //#########################################################################
  //# Cloning
  public NodeElement clone()
  {
    return (NodeElement) super.clone();
  }


  //#########################################################################
  //# Interface net.sourceforge.waters.model.module.NodeProxy
  public PlainEventListProxy getPropositions()
  {
    return mPropositions;
  }


  //#########################################################################
  //# Data Members
  private final PlainEventListProxy mPropositions;


  //#########################################################################
  //# Class Constants
  private static final long serialVersionUID = 8722673673545066528L;

}
