//# -*- indent-tabs-mode: nil  c-basic-offset: 2 -*-
//###########################################################################
//# PROJECT: Waters
//# PACKAGE: net.sourceforge.waters.plain.module
//# CLASS:   PlainEventListElement
//###########################################################################
//# $Id$
//###########################################################################
//# THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY A SCRIPT.
//# DO NOT EDIT.
//###########################################################################

package net.sourceforge.waters.plain.module;

import java.util.Collection;

import net.sourceforge.waters.model.base.Proxy;
import net.sourceforge.waters.model.base.ProxyVisitor;
import net.sourceforge.waters.model.base.VisitorException;
import net.sourceforge.waters.model.module.ModuleProxyVisitor;
import net.sourceforge.waters.model.module.PlainEventListProxy;


/**
 * An immutable implementation of the {@link PlainEventListProxy} interface.
 *
 * @author Robi Malik
 */

public final class PlainEventListElement
  extends EventListExpressionElement
  implements PlainEventListProxy
{

  //#########################################################################
  //# Constructors
  /**
   * Creates a new plain event list.
   * @param eventIdentifierList The list of event identifiers of the new plain event list, or <CODE>null</CODE> if empty.
   *        Each element is of type {@link net.sourceforge.waters.model.module.IdentifierProxy IdentifierProxy} or {@link net.sourceforge.waters.model.module.ForeachProxy ForeachProxy}.
   */
  public PlainEventListElement(final Collection<? extends Proxy> eventIdentifierList)
  {
    super(eventIdentifierList);
  }

  /**
   * Creates a new plain event list using default values.
   * This constructor creates a plain event list with
   * an empty list of event identifiers.
   */
  public PlainEventListElement()
  {
    this(null);
  }


  //#########################################################################
  //# Cloning
  @Override
  public PlainEventListElement clone()
  {
    return (PlainEventListElement) super.clone();
  }


  //#########################################################################
  //# Comparing
  public Class<PlainEventListProxy> getProxyInterface()
  {
    return PlainEventListProxy.class;
  }


  //#########################################################################
  //# Interface net.sourceforge.waters.model.base.Proxy
  public Object acceptVisitor(final ProxyVisitor visitor)
    throws VisitorException
  {
    final ModuleProxyVisitor downcast = (ModuleProxyVisitor) visitor;
    return downcast.visitPlainEventListProxy(this);
  }


  //#########################################################################
  //# Class Constants
  private static final long serialVersionUID = 1899391218638821721L;

}
