//# -*- indent-tabs-mode: nil  c-basic-offset: 2 -*-
//###########################################################################
//# PROJECT: Waters
//# PACKAGE: net.sourceforge.waters.plain.module
//# CLASS:   SimpleIdentifierElement
//###########################################################################
//# $Id$
//###########################################################################
//# THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY A SCRIPT.
//# DO NOT EDIT.
//###########################################################################

package net.sourceforge.waters.plain.module;

import net.sourceforge.waters.model.base.ProxyVisitor;
import net.sourceforge.waters.model.base.VisitorException;
import net.sourceforge.waters.model.module.ModuleProxyVisitor;
import net.sourceforge.waters.model.module.SimpleIdentifierProxy;


/**
 * An immutable implementation of the {@link SimpleIdentifierProxy} interface.
 *
 * @author Robi Malik
 */

public final class SimpleIdentifierElement
  extends IdentifierElement
  implements SimpleIdentifierProxy
{

  //#########################################################################
  //# Constructors
  /**
   * Creates a new simple identifier.
   * @param plainText The original text of the new simple identifier, or <CODE>null</CODE>.
   * @param name The name of the new simple identifier.
   */
  public SimpleIdentifierElement(final String plainText,
                                 final String name)
  {
    super(plainText);
    mName = name;
  }

  /**
   * Creates a new simple identifier using default values.
   * This constructor creates a simple identifier with
   * the original text set to <CODE>null</CODE>.
   * @param name The name of the new simple identifier.
   */
  public SimpleIdentifierElement(final String name)
  {
    this(null,
         name);
  }


  //#########################################################################
  //# Cloning
  public SimpleIdentifierElement clone()
  {
    return (SimpleIdentifierElement) super.clone();
  }


  //#########################################################################
  //# Comparing
  public Class<SimpleIdentifierProxy> getProxyInterface()
  {
    return SimpleIdentifierProxy.class;
  }


  //#########################################################################
  //# Interface net.sourceforge.waters.model.base.Proxy
  public Object acceptVisitor(final ProxyVisitor visitor)
    throws VisitorException
  {
    final ModuleProxyVisitor downcast = (ModuleProxyVisitor) visitor;
    return downcast.visitSimpleIdentifierProxy(this);
  }


  //#########################################################################
  //# Interface net.sourceforge.waters.model.module.SimpleIdentifierProxy
  public String getName()
  {
    return mName;
  }


  //#########################################################################
  //# Data Members
  private final String mName;


  //#########################################################################
  //# Class Constants
  private static final long serialVersionUID = -59614276860081368L;

}
