/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_supremica_softplc_Drivers_AdlinkPCI7432 */

#ifndef _Included_org_supremica_softplc_Drivers_AdlinkPCI7432
#define _Included_org_supremica_softplc_Drivers_AdlinkPCI7432
#ifdef __cplusplus
extern "C" {
#endif
#undef org_supremica_softplc_Drivers_AdlinkPCI7432_PCI_7432
#define org_supremica_softplc_Drivers_AdlinkPCI7432_PCI_7432 16L
#undef org_supremica_softplc_Drivers_AdlinkPCI7432_nrOfDigitalInputs
#define org_supremica_softplc_Drivers_AdlinkPCI7432_nrOfDigitalInputs 32L
#undef org_supremica_softplc_Drivers_AdlinkPCI7432_nrOfDigitalOutputs
#define org_supremica_softplc_Drivers_AdlinkPCI7432_nrOfDigitalOutputs 32L
/* Inaccessible static: defaultOutputs */
#undef org_supremica_softplc_Drivers_AdlinkPCI7432_nrOfSignalsIn
#define org_supremica_softplc_Drivers_AdlinkPCI7432_nrOfSignalsIn 32L
#undef org_supremica_softplc_Drivers_AdlinkPCI7432_nrOfSignalsOut
#define org_supremica_softplc_Drivers_AdlinkPCI7432_nrOfSignalsOut 32L
/*
 * Class:     org_supremica_softplc_Drivers_AdlinkPCI7432
 * Method:    RegisterCard
 * Signature: (SS)S
 */
JNIEXPORT jshort JNICALL Java_org_supremica_softplc_Drivers_AdlinkPCI7432_RegisterCard
  (JNIEnv *, jclass, jshort, jshort);

/*
 * Class:     org_supremica_softplc_Drivers_AdlinkPCI7432
 * Method:    ReleaseCard
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_org_supremica_softplc_Drivers_AdlinkPCI7432_ReleaseCard
  (JNIEnv *, jclass, jshort);

/*
 * Class:     org_supremica_softplc_Drivers_AdlinkPCI7432
 * Method:    WritePort
 * Signature: (SSI)V
 */
JNIEXPORT void JNICALL Java_org_supremica_softplc_Drivers_AdlinkPCI7432_WritePort
  (JNIEnv *, jclass, jshort, jshort, jint);

/*
 * Class:     org_supremica_softplc_Drivers_AdlinkPCI7432
 * Method:    ReadPort
 * Signature: (SS)I
 */
JNIEXPORT jint JNICALL Java_org_supremica_softplc_Drivers_AdlinkPCI7432_ReadPort
  (JNIEnv *, jclass, jshort, jshort);

#ifdef __cplusplus
}
#endif
#endif
