package org.supremica.automata.IO;

import java.io.*;
import org.supremica.automata.*;

/**
 * Creates a PCG-file, most of this file is copied from AutomataToHierarchyToDot.
 *
 * @author Arash
 * @see AutomataToHierarchyToDot
 */
public class AutomataToCommunicationGraph
	implements AutomataSerializer
{
	private final Automata theAutomata;

	public AutomataToCommunicationGraph(final Automata aut)
	{
		this.theAutomata = aut;
	}

	public void serialize(final PrintWriter pw)
		throws Exception
	{
		pw.println("# Generated by AutomataToCommunicationGraph.java ");
		pw.println("# This is a weighted undirected graph for dependency analysis. ");
		pw.println("# PCG-syntax:    Node1 <TAB> Node2 <TAB> Weight               <LF>");
		pw.println("# For Supremica: Aut1  <TAB> Aut2  <TAB> num-of-shared-events <LF>");
		pw.println("#     /Arash ");
		for (int i = 0; i < theAutomata.size(); i++)
		{
			final Automaton currAutomaton = theAutomata.getAutomatonAt(i);
			final Alphabet currAlphabet = currAutomaton.getAlphabet();
			for (int j = i + 1; j < theAutomata.size(); j++)
			{
				final Automaton otherAutomaton = theAutomata.getAutomatonAt(j);
				final Alphabet otherAlphabet = otherAutomaton.getAlphabet();
				final int weight = currAlphabet.nbrOfCommonEvents(otherAlphabet);

				if (weight > 0)
				{
					pw.println("" + currAutomaton.getName() + "\t" + otherAutomaton.getName() + "\t" + weight);
				}
			}
		}

		// TODO:
		// we have num of edges and nodes, give a simple statistic and analysis about the graph type here
		pw.flush();
		pw.close();
	}

	public void serialize(final String fileName)
		throws Exception
	{
		serialize(new PrintWriter(new FileWriter(fileName)));
	}
}
