/******************* AutomatonToADS.java **********************
 * Conversion from Supremica format to PiTCT .ads format
 */
package org.supremica.automata.IO;

import java.util.*;
import java.io.*;
import org.supremica.automata.Arc;
import org.supremica.automata.Automaton;
import org.supremica.automata.State;
import org.supremica.automata.LabeledEvent;


public class AutomatonToADS
	implements AutomataSerializer
{
	// PiTCT assumes that the (single!) initial state has index 0
	// If this is not the case, temporarily swap indices to make it so
	// private final int initIndex;
	// private final State zeroState; // The state originally with index 0
	private final Map<LabeledEvent, Integer> eventMap = new HashMap<>();
	private final Map<State, Integer> stateMap = new HashMap<>();

	private final Automaton aut;

	public AutomatonToADS(final Automaton aut)
	{
		this.aut = aut;

		buildStateMap();	// Need to build maps, since PiTCT uses numbers for states and events
		buildEventMap();	// 0 for initial state, odd numbers for controllable events
	}

	@Override
	public void serialize(final PrintWriter pw)
		throws Exception
	{
		pw.println(aut.getName()); // PiTCT .ads start with the name on first line
		pw.println();
		pw.println("State size (State set will be (0,1....,size-1)):");
		pw.println(aut.nbrOfStates());
		pw.println();
		pw.println("Marker states:");

		printMarkedStates(pw);

		pw.println("\n\nVocal states:\n"); // No idea what this is but it is there

		pw.println("Transitions:");
		printTransitions(pw);

		pw.println("# Generated by Supremica " + java.time.LocalDateTime.now());

	}

	@Override
	public void serialize(String fileName)
		throws Exception
	{
		final PrintWriter pw = new PrintWriter(new FileWriter(fileName));
		serialize(pw);
		pw.flush();
		pw.close();
	}

	///////////////////////////////// Private parts below

	private void printMarkedStates(final PrintWriter pw)
	{
		// Find the marked (accepting) states and write their indices
		final Iterator<State> states_it = aut.stateIterator();
		while (states_it.hasNext())
		{
			State state = (State) states_it.next();
			if (state.isAccepting())
			{
				pw.print(stateMap.get(state));
				pw.print(" ");
			}
		}
	}

	private void buildEventMap()
	{
		int countOdd = 11;	// PiTCT considers controllable events to be odd numbers
		int countEven = 10;	// Uncontrollabel events are even numbers

		final Iterator<LabeledEvent> events = aut.eventIterator();
		while (events.hasNext())
		{
			final LabeledEvent event = events.next();
			if (event.isControllable())
			{
				eventMap.put(event, countOdd);
				countOdd += 2;
			}
			else
			{
				eventMap.put(event, countEven);
				countEven += 2;
			}
		}
	}

	// This is ugly, but we must guarantee that the (single!) initial state is numbered 0
	// and the other states are numbered consequtively 1..num_states-1
	private void buildStateMap()
	{
		final State initState = aut.getInitialState();
		stateMap.put(initState, 0);
		int countStates = 1;

		final Iterator<State> states_it = aut.stateIterator();
		while (states_it.hasNext())
		{
			final State state = states_it.next();
			if(state != initState)
				stateMap.put(state, countStates++);
		}
	}

	private void printTransitions(final PrintWriter pw)
	{
		final Iterator<State> states = aut.stateIterator();
		while (states.hasNext())
		{
			final State sourceState = states.next();
			final int srcInt = stateMap.get(sourceState);
			final Iterator<Arc> outgoingArcs = sourceState.outgoingArcsIterator();
			while (outgoingArcs.hasNext())
			{
				final Arc arc = (Arc) outgoingArcs.next();
				final State destState = arc.getToState();
				final LabeledEvent event = arc.getEvent();
				final StringBuffer buf = new StringBuffer();
				buf.append(srcInt);
				buf.append(" ");
				buf.append(eventMap.get(event));
				buf.append(" ");
				buf.append(stateMap.get(destState));
				pw.println(buf.toString());
			}
		}
	}

	private String sanityCheck()
	{
		if (!aut.hasInitialState())
		{
			return "This automaton has no initial state";
		}
		return null;
	}
}