/* Generated By:JJTree: Do not edit this line. ASTarray_specification.java */
package org.supremica.softplc.CompILer.Parser.SyntaxTree;

import org.supremica.softplc.CompILer.Parser.*;

public class ASTarray_specification
	extends SimpleNode
{
	public ASTarray_specification(int id)
	{
		super(id);
	}

	public ASTarray_specification(parser p, int id)
	{
		super(p, id);
	}
}
