/* Generated By:JJTree: Do not edit this line. ASTarray_initial_elements.java */
package org.supremica.softplc.CompILer.Parser.SyntaxTree;

public class ASTarray_initial_elements
	extends SimpleNode
{
	public ASTarray_initial_elements(int id)
	{
		super(id);
	}

	public ASTarray_initial_elements(parser p, int id)
	{
		super(p, id);
	}
}
