/* Generated By:JJTree: Do not edit this line. ASTaccess_declarations.java */

package org.supremica.softplc.CompILer.Parser.SyntaxTree;
import org.supremica.softplc.CompILer.Parser.*;

public class ASTaccess_declarations extends SimpleNode {
  public ASTaccess_declarations(int id) {
    super(id);
  }

  public ASTaccess_declarations(parser p, int id) {
    super(p, id);
  }

}
