/* Generated By:JJTree: Do not edit this line. ASTderived_function_block_name.java */
package org.supremica.softplc.CompILer.Parser.SyntaxTree;

import org.supremica.softplc.CompILer.Parser.*;

public class ASTderived_function_block_name
	extends SimpleNode
{
	public ASTderived_function_block_name(int id)
	{
		super(id);
	}

	public ASTderived_function_block_name(parser p, int id)
	{
		super(p, id);
	}

	// Appended
	private String name;

	public void setName(String n)
	{
		name = n;
	}

	public String getName()
	{
		return name;
	}

	public String toString()
	{
		return "derived_function_block_name: " + name;
	}

	public Object visit(SimpleNodeVisitor v, Object o)
	{
		return v.visitDERIVED_FUNCTION_BLOCK_NAME(this, o);
	}
}
