/* Generated By:JJTree: Do not edit this line. ASTderived_function_name.java */
package org.supremica.softplc.CompILer.Parser.SyntaxTree;

import org.supremica.softplc.CompILer.Parser.*;

public class ASTderived_function_name
	extends SimpleNode
{
	public ASTderived_function_name(int id)
	{
		super(id);
	}

	public ASTderived_function_name(parser p, int id)
	{
		super(p, id);
	}
}
