/* Generated By:JJTree: Do not edit this line. ASTdouble_byte_string_var_declaration.java */
package org.supremica.softplc.CompILer.Parser.SyntaxTree;

public class ASTdouble_byte_string_var_declaration
	extends SimpleNode
{
	public ASTdouble_byte_string_var_declaration(int id)
	{
		super(id);
	}

	public ASTdouble_byte_string_var_declaration(parser p, int id)
	{
		super(p, id);
	}
}
