/* Generated By:JJTree: Do not edit this line. ASTday_minute.java */
package org.supremica.softplc.CompILer.Parser.SyntaxTree;

import org.supremica.softplc.CompILer.Parser.*;

public class ASTday_minute
	extends SimpleNode
{
	public ASTday_minute(int id)
	{
		super(id);
	}

	public ASTday_minute(parser p, int id)
	{
		super(p, id);
	}
}
