/* Generated By:JJTree: Do not edit this line. ASTedge_declaration.java */
package org.supremica.softplc.CompILer.Parser.SyntaxTree;

import org.supremica.softplc.CompILer.Parser.*;

public class ASTedge_declaration
	extends SimpleNode
{
	public ASTedge_declaration(int id)
	{
		super(id);
	}

	public ASTedge_declaration(parser p, int id)
	{
		super(p, id);
	}
}
