/* Generated By:JJTree: Do not edit this line. ASTfb_name.java */

package org.supremica.softplc.CompILer.Parser.SyntaxTree;
import org.supremica.softplc.CompILer.Parser.*;

public class ASTfb_name extends SimpleNode {
  public ASTfb_name(int id) {
    super(id);
  }

  public ASTfb_name(parser p, int id) {
    super(p, id);
  }
	//Appended
  private String name;
  private String typeName;

  public void setName(String n) {
    name = n;
  }

  public String getName(){
    return name;
  }
  public void setTypeName(String n){
   	typeName = n;
  }

  public String getTypeName(){
    return typeName;
  }

  public String toString() {
      return "fb_name: " + name + " type: " + typeName;
  }

  public Object visit(SimpleNodeVisitor v, Object o){
	  return v.visitFB_NAME(this,o);
  }
}
