/* Generated By:JJTree: Do not edit this line. ASTfb_task.java */

package org.supremica.softplc.CompILer.Parser.SyntaxTree;
import org.supremica.softplc.CompILer.Parser.*;

public class ASTfb_task extends SimpleNode {
  public ASTfb_task(int id) {
    super(id);
  }

  public ASTfb_task(parser p, int id) {
    super(p, id);
  }

}
