/* Generated By:JJTree: Do not edit this line. ASTfixed_point.java */

package org.supremica.softplc.CompILer.Parser.SyntaxTree;
import org.supremica.softplc.CompILer.Parser.*;

public class ASTfixed_point extends SimpleNode {
  public ASTfixed_point(int id) {
    super(id);
  }

  public ASTfixed_point(parser p, int id) {
    super(p, id);
  }

}
