/* Generated By:JJTree: Do not edit this line. ASTfunction_block_body.java */

package org.supremica.softplc.CompILer.Parser.SyntaxTree;
import org.supremica.softplc.CompILer.Parser.*;

public class ASTfunction_block_body extends SimpleNode {
  public ASTfunction_block_body(int id) {
    super(id);
  }

  public ASTfunction_block_body(parser p, int id) {
    super(p, id);
  }
    //Appended
    public Object visit(SimpleNodeVisitor v, Object o) {
        return v.visitFUNCTION_BLOCK_BODY(this,o);
    }
}
