/* Generated By:JJTree: Do not edit this line. ASTfb_name_decl.java */
package org.supremica.softplc.CompILer.Parser.SyntaxTree;

public class ASTfb_name_decl
	extends SimpleNode
{
	public ASTfb_name_decl(int id)
	{
		super(id);
	}

	public ASTfb_name_decl(parser p, int id)
	{
		super(p, id);
	}
}
