/* Generated By:JJTree: Do not edit this line. ASTil_param_out_assignment.java */
package org.supremica.softplc.CompILer.Parser.SyntaxTree;

import org.supremica.softplc.CompILer.Parser.*;

public class ASTil_param_out_assignment
	extends SimpleNode
{
	public ASTil_param_out_assignment(int id)
	{
		super(id);
	}

	public ASTil_param_out_assignment(parser p, int id)
	{
		super(p, id);
	}
}
