/* Generated By:JJTree: Do not edit this line. ASTinput_declarations.java */
package org.supremica.softplc.CompILer.Parser.SyntaxTree;

public class ASTinput_declarations
	extends SimpleNode
{
	public ASTinput_declarations(int id)
	{
		super(id);
	}

	public ASTinput_declarations(parser p, int id)
	{
		super(p, id);
	}
}
