/* Generated By:JJTree: Do not edit this line. ASTil_assign_operator.java */
package org.supremica.softplc.CompILer.Parser.SyntaxTree;

public class ASTil_assign_operator
	extends SimpleNode
{
	public ASTil_assign_operator(int id)
	{
		super(id);
	}

	public ASTil_assign_operator(parser p, int id)
	{
		super(p, id);
	}
}
