/* Generated By:JJTree: Do not edit this line. ASTinitialized_structure.java */
package org.supremica.softplc.CompILer.Parser.SyntaxTree;

public class ASTinitialized_structure
	extends SimpleNode
{
	public ASTinitialized_structure(int id)
	{
		super(id);
	}

	public ASTinitialized_structure(parser p, int id)
	{
		super(p, id);
	}
}
