/* Generated By:JJTree: Do not edit this line. ASTinput_declaration.java */

package org.supremica.softplc.CompILer.Parser.SyntaxTree;
import org.supremica.softplc.CompILer.Parser.*;

public class ASTinput_declaration extends SimpleNode {
  public ASTinput_declaration(int id) {
    super(id);
  }

  public ASTinput_declaration(parser p, int id) {
    super(p, id);
  }

}
