/* Generated By:JJTree: Do not edit this line. ASTinstance_specific_init.java */

package org.supremica.softplc.CompILer.Parser.SyntaxTree;
import org.supremica.softplc.CompILer.Parser.*;

public class ASTinstance_specific_init extends SimpleNode {
  public ASTinstance_specific_init(int id) {
    super(id);
  }

  public ASTinstance_specific_init(parser p, int id) {
    super(p, id);
  }

}
