/* Generated By:JJTree: Do not edit this line. ASTil_operand_list.java */
package org.supremica.softplc.CompILer.Parser.SyntaxTree;

import org.supremica.softplc.CompILer.Parser.*;
import java.util.LinkedList;

public class ASTil_operand_list
	extends SimpleNode
{
	public ASTil_operand_list(int id)
	{
		super(id);
	}

	public ASTil_operand_list(parser p, int id)
	{
		super(p, id);
	}

	// Appended
	private LinkedList operands = new LinkedList();

	public void addOperand(Operand o)
	{
		operands.add(o);
	}

	public LinkedList getOperands()
	{
		return operands;
	}

	public Object visit(SimpleNodeVisitor v, Object o)
	{
		return v.visitIL_OPERAND_LIST(this, o);
	}
}
