/* Generated By:JJTree: Do not edit this line. ASTinterval.java */
package org.supremica.softplc.CompILer.Parser.SyntaxTree;

public class ASTinterval
	extends SimpleNode
{
	public ASTinterval(int id)
	{
		super(id);
	}

	public ASTinterval(parser p, int id)
	{
		super(p, id);
	}
}
