/* Generated By:JJTree: Do not edit this line. ASTlocated_var_declarations.java */

package org.supremica.softplc.CompILer.Parser.SyntaxTree;
import org.supremica.softplc.CompILer.Parser.*;

public class ASTlocated_var_declarations extends SimpleNode {
  public ASTlocated_var_declarations(int id) {
    super(id);
  }

  public ASTlocated_var_declarations(parser p, int id) {
    super(p, id);
  }

    //Appended
    public Object visit(SimpleNodeVisitor v, Object o){
        return v.visitLOCATED_VAR_DECLARATIONS(this,o);
    }


}
