/* Generated By:JJTree: Do not edit this line. ASTmultiply_operator.java */

package org.supremica.softplc.CompILer.Parser.SyntaxTree;
import org.supremica.softplc.CompILer.Parser.*;

public class ASTmultiply_operator extends SimpleNode {
  public ASTmultiply_operator(int id) {
    super(id);
  }

  public ASTmultiply_operator(parser p, int id) {
    super(p, id);
  }

}
