/* Generated By:JJTree: Do not edit this line. ASTnon_generic_type_name.java */
package org.supremica.softplc.CompILer.Parser.SyntaxTree;

public class ASTnon_generic_type_name
	extends SimpleNode
{
	public ASTnon_generic_type_name(int id)
	{
		super(id);
	}

	public ASTnon_generic_type_name(parser p, int id)
	{
		super(p, id);
	}
}
