/* Generated By:JJTree: Do not edit this line. ASTprog_conf_elements.java */
package org.supremica.softplc.CompILer.Parser.SyntaxTree;

public class ASTprog_conf_elements
	extends SimpleNode
{
	public ASTprog_conf_elements(int id)
	{
		super(id);
	}

	public ASTprog_conf_elements(parser p, int id)
	{
		super(p, id);
	}
}
