/* Generated By:JJTree: Do not edit this line. ASTrecord_variable.java */
package org.supremica.softplc.CompILer.Parser.SyntaxTree;

import org.supremica.softplc.CompILer.Parser.*;

public class ASTrecord_variable
	extends SimpleNode
{
	public ASTrecord_variable(int id)
	{
		super(id);
	}

	public ASTrecord_variable(parser p, int id)
	{
		super(p, id);
	}

	// Appended
	public Object visit(SimpleNodeVisitor v, Object o)
	{
		return v.visitRECORD_VARIABLE(this, o);
	}
}
