/* Generated By:JJTree: Do not edit this line. ASTstructure_type_name.java */
package org.supremica.softplc.CompILer.Parser.SyntaxTree;

import org.supremica.softplc.CompILer.Parser.*;

public class ASTstructure_type_name
	extends SimpleNode
{
	public ASTstructure_type_name(int id)
	{
		super(id);
	}

	public ASTstructure_type_name(parser p, int id)
	{
		super(p, id);
	}
}
