/* Generated By:JJTree: Do not edit this line. ASTstructure_element_name.java */

package org.supremica.softplc.CompILer.Parser.SyntaxTree;
import org.supremica.softplc.CompILer.Parser.*;

public class ASTstructure_element_name extends SimpleNode {
  public ASTstructure_element_name(int id) {
    super(id);
  }

  public ASTstructure_element_name(parser p, int id) {
    super(p, id);
  }

}
