/* Generated By:JJTree: Do not edit this line. ASTstring_var_declaration.java */
package org.supremica.softplc.CompILer.Parser.SyntaxTree;

public class ASTstring_var_declaration
	extends SimpleNode
{
	public ASTstring_var_declaration(int id)
	{
		super(id);
	}

	public ASTstring_var_declaration(parser p, int id)
	{
		super(p, id);
	}
}
