/* Generated By:JJTree: Do not edit this line. ASTsubrange_type_declaration.java */
package org.supremica.softplc.CompILer.Parser.SyntaxTree;

import org.supremica.softplc.CompILer.Parser.*;

public class ASTsubrange_type_declaration
	extends SimpleNode
{
	public ASTsubrange_type_declaration(int id)
	{
		super(id);
	}

	public ASTsubrange_type_declaration(parser p, int id)
	{
		super(p, id);
	}
}
