/* Generated By:JJTree: Do not edit this line. ASTsimple_type_name.java */
package org.supremica.softplc.CompILer.Parser.SyntaxTree;

import org.supremica.softplc.CompILer.Parser.*;

public class ASTsimple_type_name
	extends SimpleNode
{
	public ASTsimple_type_name(int id)
	{
		super(id);
	}

	public ASTsimple_type_name(parser p, int id)
	{
		super(p, id);
	}

	// Appended
	private String name;

	public void setName(String n)
	{
		name = n;
	}

	public String getName()
	{
		return name;
	}

	public String toString()
	{
		return "simple_type_name: " + name;
	}

	public Object visit(SimpleNodeVisitor v, Object o)
	{
		return v.visitSIMPLE_TYPE_NAME(this, o);
	}
}
