/* Generated By:JJTree: Do not edit this line. ASTsingle_element_type_declaration.java */

package org.supremica.softplc.CompILer.Parser.SyntaxTree;
import org.supremica.softplc.CompILer.Parser.*;

public class ASTsingle_element_type_declaration extends SimpleNode {
  public ASTsingle_element_type_declaration(int id) {
    super(id);
  }

  public ASTsingle_element_type_declaration(parser p, int id) {
    super(p, id);
  }

}
