/* Generated By:JJTree: Do not edit this line. ASTstructure_specification.java */
package org.supremica.softplc.CompILer.Parser.SyntaxTree;

import org.supremica.softplc.CompILer.Parser.*;

public class ASTstructure_specification
	extends SimpleNode
{
	public ASTstructure_specification(int id)
	{
		super(id);
	}

	public ASTstructure_specification(parser p, int id)
	{
		super(p, id);
	}
}
