/* Generated By:JJTree: Do not edit this line. ASTsingle_byte_string_var_declaration.java */
package org.supremica.softplc.CompILer.Parser.SyntaxTree;

import org.supremica.softplc.CompILer.Parser.*;

public class ASTsingle_byte_string_var_declaration
	extends SimpleNode
{
	public ASTsingle_byte_string_var_declaration(int id)
	{
		super(id);
	}

	public ASTsingle_byte_string_var_declaration(parser p, int id)
	{
		super(p, id);
	}
}
