/* Generated By:JJTree: Do not edit this line. ASTsimple_spec_init.java */

package org.supremica.softplc.CompILer.Parser.SyntaxTree;
import org.supremica.softplc.CompILer.Parser.*;

public class ASTsimple_spec_init extends SimpleNode {
  public ASTsimple_spec_init(int id) {
    super(id);
  }

  public ASTsimple_spec_init(parser p, int id) {
    super(p, id);
  }
    //Appended

	private String typeName;

	public void setTypeName(String typeName){
		this.typeName = typeName;
	}

	public String getTypeName() {
		return this.typeName;
	}

    public Object visit(SimpleNodeVisitor v, Object o){
        return v.visitSIMPLE_SPEC_INIT(this,o);
    }
}
