/* Generated By:JJTree: Do not edit this line. ASTtask_configuration.java */

package org.supremica.softplc.CompILer.Parser.SyntaxTree;
import org.supremica.softplc.CompILer.Parser.*;

public class ASTtask_configuration extends SimpleNode {
  public ASTtask_configuration(int id) {
    super(id);
  }

  public ASTtask_configuration(parser p, int id) {
    super(p, id);
  }

}
