/* Generated By:JJTree: Do not edit this line. ASTterm.java */
package org.supremica.softplc.CompILer.Parser.SyntaxTree;

public class ASTterm
	extends SimpleNode
{
	public ASTterm(int id)
	{
		super(id);
	}

	public ASTterm(parser p, int id)
	{
		super(p, id);
	}
}
