/* Generated By:JJTree: Do not edit this line. ASTtime_of_day.java */
package org.supremica.softplc.CompILer.Parser.SyntaxTree;

import org.supremica.softplc.CompILer.Parser.*;

public class ASTtime_of_day
	extends SimpleNode
{
	public ASTtime_of_day(int id)
	{
		super(id);
	}

	public ASTtime_of_day(parser p, int id)
	{
		super(p, id);
	}
}
