/* Generated By:JJTree: Do not edit this line. ASTtype_declaration.java */
package org.supremica.softplc.CompILer.Parser.SyntaxTree;

public class ASTtype_declaration
	extends SimpleNode
{
	public ASTtype_declaration(int id)
	{
		super(id);
	}

	public ASTtype_declaration(parser p, int id)
	{
		super(p, id);
	}
}
