/* Generated By:JJTree: Do not edit this line. ASTunary_expression.java */

package org.supremica.softplc.CompILer.Parser.SyntaxTree;
import org.supremica.softplc.CompILer.Parser.*;

public class ASTunary_expression extends SimpleNode {
  public ASTunary_expression(int id) {
    super(id);
  }

  public ASTunary_expression(parser p, int id) {
    super(p, id);
  }

}
