/* Generated By:JJTree: Do not edit this line. ASTvar1_init_decl.java */

package org.supremica.softplc.CompILer.Parser.SyntaxTree;
import org.supremica.softplc.CompILer.Parser.*;

public class ASTvar1_init_decl extends SimpleNode {
  public ASTvar1_init_decl(int id) {
    super(id);
  }

  public ASTvar1_init_decl(parser p, int id) {
    super(p, id);
  }

    //Appended
	private String[] names;
	private String typeName;

	public void setNames(String[] names) {
		this.names = names;
	}

	public String[] getNames() {
		return names;
	}

	public void setTypeName(String typeName){
		this.typeName = typeName;
	}

	public String getTypeName() {
		return this.typeName;
	}


    public Object visit(SimpleNodeVisitor v, Object o){
        return v.visitVAR1_INIT_DECL(this,o);
    }
}
