/* Generated By:JJTree: Do not edit this line. parserTreeConstants.java */

package org.supremica.softplc.CompILer.Parser.SyntaxTree;

public interface parserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTNUMERIC_LITERAL = 2;
  public int JJTBOOLEAN_LITERAL = 3;
  public int JJTCHARACTER_STRING = 4;
  public int JJTTIME_LITERAL = 5;
  public int JJTDURATION = 6;
  public int JJTINTERVAL = 7;
  public int JJTDAYS = 8;
  public int JJTFIXED_POINT = 9;
  public int JJTHOURS = 10;
  public int JJTMINUTES = 11;
  public int JJTSECONDS = 12;
  public int JJTMILLISECONDS = 13;
  public int JJTTIME_OF_DAY = 14;
  public int JJTDAYTIME = 15;
  public int JJTDAY_HOUR = 16;
  public int JJTDAY_MINUTE = 17;
  public int JJTDAY_SECOND = 18;
  public int JJTDATE = 19;
  public int JJTDATE_LITERAL = 20;
  public int JJTYEAR = 21;
  public int JJTMONTH = 22;
  public int JJTDAY = 23;
  public int JJTDATE_AND_TIME = 24;
  public int JJTDATA_TYPE_NAME = 25;
  public int JJTNON_GENERIC_TYPE_NAME = 26;
  public int JJTELEMENTARY_TYPE_NAME = 27;
  public int JJTDERIVED_TYPE_NAME = 28;
  public int JJTSINGLE_ELEMENT_TYPE_NAME = 29;
  public int JJTSIMPLE_TYPE_NAME = 30;
  public int JJTSUBRANGE_TYPE_NAME = 31;
  public int JJTENUMERATED_TYPE_NAME = 32;
  public int JJTARRAY_TYPE_NAME = 33;
  public int JJTSTRUCTURE_TYPE_NAME = 34;
  public int JJTDATA_TYPE_DECLARATION = 35;
  public int JJTTYPE_DECLARATION = 36;
  public int JJTSINGLE_ELEMENT_TYPE_DECLARATION = 37;
  public int JJTSIMPLE_TYPE_DECLARATION = 38;
  public int JJTSIMPLE_SPEC_INIT = 39;
  public int JJTSIMPLE_SPECIFICATION = 40;
  public int JJTSUBRANGE_TYPE_DECLARATION = 41;
  public int JJTSUBRANGE_SPEC_INIT = 42;
  public int JJTSUBRANGE_SPECIFICATION = 43;
  public int JJTSUBRANGE = 44;
  public int JJTENUMERATED_TYPE_DECLARATION = 45;
  public int JJTENUMERATED_SPEC_INIT = 46;
  public int JJTENUMERATED_SPECIFICATION = 47;
  public int JJTENUMERATED_VALUE = 48;
  public int JJTARRAY_TYPE_DECLARATION = 49;
  public int JJTARRAY_SPEC_INIT = 50;
  public int JJTARRAY_SPECIFICATION = 51;
  public int JJTARRAY_INITIALIZATION = 52;
  public int JJTARRAY_INITIAL_ELEMENTS = 53;
  public int JJTARRAY_INITIAL_ELEMENT = 54;
  public int JJTSTRUCTURE_TYPE_DECLARATION = 55;
  public int JJTSTRUCTURE_SPECIFICATION = 56;
  public int JJTINITIALIZED_STRUCTURE = 57;
  public int JJTSTRUCTURE_DECLARATION = 58;
  public int JJTSTRUCTURE_ELEMENT_DECLARATION = 59;
  public int JJTSTRUCTURE_ELEMENT_NAME = 60;
  public int JJTSTRUCTURE_INITIALIZATION = 61;
  public int JJTSTRUCTURE_ELEMENT_INITIALIZATION = 62;
  public int JJTSTRING_TYPE_NAME = 63;
  public int JJTSTRING_TYPE_DECLARATION = 64;
  public int JJTVARIABLE = 65;
  public int JJTVARIABLE_NAME = 66;
  public int JJTMULTI_ELEMENT_VARIABLE = 67;
  public int JJTARRAY_VARIABLE = 68;
  public int JJTSUBSCRIPTED_VARIABLE = 69;
  public int JJTSUBSCRIPT_LIST = 70;
  public int JJTSUBSCRIPT = 71;
  public int JJTSTRUCTURED_VARIABLE = 72;
  public int JJTRECORD_VARIABLE = 73;
  public int JJTFIELD_SELECTOR = 74;
  public int JJTINPUT_DECLARATIONS = 75;
  public int JJTINPUT_DECLARATION = 76;
  public int JJTEDGE_DECLARATION = 77;
  public int JJTVAR_INIT_DECL = 78;
  public int JJTVAR1_INIT_DECL = 79;
  public int JJTVAR1_LIST = 80;
  public int JJTARRAY_VAR_INIT_DECL = 81;
  public int JJTSTRUCTURED_VAR_INIT_DECL = 82;
  public int JJTFB_NAME_DECL = 83;
  public int JJTFB_NAME_LIST = 84;
  public int JJTFB_NAME = 85;
  public int JJTOUTPUT_DECLARATIONS = 86;
  public int JJTINPUT_OUTPUT_DECLARATIONS = 87;
  public int JJTVAR_DECLARATION = 88;
  public int JJTTEMP_VAR_DECL = 89;
  public int JJTVAR1_DECLARATION = 90;
  public int JJTARRAY_VAR_DECLARATION = 91;
  public int JJTSTRUCTURED_VAR_DECLARATION = 92;
  public int JJTVAR_DECLARATIONS = 93;
  public int JJTRETENTIVE_VAR_DECLARATIONS = 94;
  public int JJTLOCATED_VAR_DECLARATIONS = 95;
  public int JJTLOCATED_VAR_DECL = 96;
  public int JJTEXTERNAL_VAR_DECLARATIONS = 97;
  public int JJTEXTERNAL_DECLARATION = 98;
  public int JJTGLOBAL_VAR_NAME = 99;
  public int JJTGLOBAL_VAR_DECLARATIONS = 100;
  public int JJTGLOBAL_VAR_DECL = 101;
  public int JJTGLOBAL_VAR_SPEC = 102;
  public int JJTLOCATED_VAR_SPEC_INIT = 103;
  public int JJTLOCATION = 104;
  public int JJTGLOBAL_VAR_LIST = 105;
  public int JJTSTRING_VAR_DECLARATION = 106;
  public int JJTSINGLE_BYTE_STRING_VAR_DECLARATION = 107;
  public int JJTDOUBLE_BYTE_STRING_VAR_DECLARATION = 108;
  public int JJTINCOMPL_LOCATED_VAR_DECLARATIONS = 109;
  public int JJTINCOMPL_LOCATED_VAR_DECL = 110;
  public int JJTINCOMPL_LOCATION = 111;
  public int JJTVAR_SPEC = 112;
  public int JJTFUNCTION_NAME = 113;
  public int JJTDERIVED_FUNCTION_NAME = 114;
  public int JJTFUNCTION_DECLARATION = 115;
  public int JJTIO_VAR_DECLARATIONS = 116;
  public int JJTFUNCTION_VAR_DECLS = 117;
  public int JJTFUNCTION_BODY = 118;
  public int JJTVAR2_INIT_DECL = 119;
  public int JJTFUNCTION_BLOCK_TYPE_NAME = 120;
  public int JJTDERIVED_FUNCTION_BLOCK_NAME = 121;
  public int JJTFUNCTION_BLOCK_DECLARATION = 122;
  public int JJTJAVA_BLOCK_DECLARATION = 123;
  public int JJTOTHER_VAR_DECLARATIONS = 124;
  public int JJTTEMP_VAR_DECLS = 125;
  public int JJTNON_RETENTIVE_VAR_DECLS = 126;
  public int JJTFUNCTION_BLOCK_BODY = 127;
  public int JJTPROGRAM_TYPE_NAME = 128;
  public int JJTPROGRAM_DECLARATION = 129;
  public int JJTPROGRAM_ACCESS_DECLS = 130;
  public int JJTPROGRAM_ACCESS_DECL = 131;
  public int JJTCONFIGURATION_NAME = 132;
  public int JJTRESOURCE_TYPE_NAME = 133;
  public int JJTCONFIGURATION_DECLARATION = 134;
  public int JJTRESOURCE_DECLARATION = 135;
  public int JJTSINGLE_RESOURCE_DECLARATION = 136;
  public int JJTRESOURCE_NAME = 137;
  public int JJTACCESS_DECLARATIONS = 138;
  public int JJTACCESS_DECLARATION = 139;
  public int JJTACCESS_PATH = 140;
  public int JJTGLOBAL_VAR_REFERENCE = 141;
  public int JJTACCESS_NAME = 142;
  public int JJTPROGRAM_OUTPUT_REFERENCE = 143;
  public int JJTPROGRAM_NAME = 144;
  public int JJTDIRECTION = 145;
  public int JJTTASK_CONFIGURATION = 146;
  public int JJTTASK_NAME = 147;
  public int JJTTASK_INITIALIZATION = 148;
  public int JJTDATA_SOURCE = 149;
  public int JJTPROGRAM_CONFIGURATION = 150;
  public int JJTPROG_CONF_ELEMENTS = 151;
  public int JJTPROG_CONF_ELEMENT = 152;
  public int JJTFB_TASK = 153;
  public int JJTPROG_CNXN = 154;
  public int JJTPROG_DATA_SOURCE = 155;
  public int JJTDATA_SINK = 156;
  public int JJTINSTANCE_SPECIFIC_INITIALIZATIONS = 157;
  public int JJTINSTANCE_SPECIFIC_INIT = 158;
  public int JJTLABEL = 159;
  public int JJTIL_SIMPLE_OPERATION = 160;
  public int JJTIL_EXPRESSION = 161;
  public int JJTIL_JUMP_OPERATION = 162;
  public int JJTIL_FB_CALL = 163;
  public int JJTIL_OPERAND_LIST = 164;
  public int JJTSIMPLE_INSTR_LIST = 165;
  public int JJTIL_SIMPLE_INSTRUCTION = 166;
  public int JJTIL_PARAM_LIST = 167;
  public int JJTIL_PARAM_INSTRUCTION = 168;
  public int JJTIL_PARAM_LAST_INSTRUCTION = 169;
  public int JJTIL_PARAM_ASSIGNMENT = 170;
  public int JJTIL_PARAM_OUT_ASSIGNMENT = 171;
  public int JJTIL_ASSIGN_OPERATOR = 172;
  public int JJTIL_ASSIGN_OUT_OPERATOR = 173;
  public int JJTIL_CALL_OPERATOR = 174;
  public int JJTIL_CALL_JAVA_OPERATOR = 175;
  public int JJTIL_RETURN_OPERATOR = 176;
  public int JJTIL_JUMP_OPERATOR = 177;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "numeric_literal",
    "boolean_literal",
    "character_string",
    "time_literal",
    "duration",
    "interval",
    "days",
    "fixed_point",
    "hours",
    "minutes",
    "seconds",
    "milliseconds",
    "time_of_day",
    "daytime",
    "day_hour",
    "day_minute",
    "day_second",
    "date",
    "date_literal",
    "year",
    "month",
    "day",
    "date_and_time",
    "data_type_name",
    "non_generic_type_name",
    "elementary_type_name",
    "derived_type_name",
    "single_element_type_name",
    "simple_type_name",
    "subrange_type_name",
    "enumerated_type_name",
    "array_type_name",
    "structure_type_name",
    "data_type_declaration",
    "type_declaration",
    "single_element_type_declaration",
    "simple_type_declaration",
    "simple_spec_init",
    "simple_specification",
    "subrange_type_declaration",
    "subrange_spec_init",
    "subrange_specification",
    "subrange",
    "enumerated_type_declaration",
    "enumerated_spec_init",
    "enumerated_specification",
    "enumerated_value",
    "array_type_declaration",
    "array_spec_init",
    "array_specification",
    "array_initialization",
    "array_initial_elements",
    "array_initial_element",
    "structure_type_declaration",
    "structure_specification",
    "initialized_structure",
    "structure_declaration",
    "structure_element_declaration",
    "structure_element_name",
    "structure_initialization",
    "structure_element_initialization",
    "string_type_name",
    "string_type_declaration",
    "variable",
    "variable_name",
    "multi_element_variable",
    "array_variable",
    "subscripted_variable",
    "subscript_list",
    "subscript",
    "structured_variable",
    "record_variable",
    "field_selector",
    "input_declarations",
    "input_declaration",
    "edge_declaration",
    "var_init_decl",
    "var1_init_decl",
    "var1_list",
    "array_var_init_decl",
    "structured_var_init_decl",
    "fb_name_decl",
    "fb_name_list",
    "fb_name",
    "output_declarations",
    "input_output_declarations",
    "var_declaration",
    "temp_var_decl",
    "var1_declaration",
    "array_var_declaration",
    "structured_var_declaration",
    "var_declarations",
    "retentive_var_declarations",
    "located_var_declarations",
    "located_var_decl",
    "external_var_declarations",
    "external_declaration",
    "global_var_name",
    "global_var_declarations",
    "global_var_decl",
    "global_var_spec",
    "located_var_spec_init",
    "location",
    "global_var_list",
    "string_var_declaration",
    "single_byte_string_var_declaration",
    "double_byte_string_var_declaration",
    "incompl_located_var_declarations",
    "incompl_located_var_decl",
    "incompl_location",
    "var_spec",
    "function_name",
    "derived_function_name",
    "function_declaration",
    "io_var_declarations",
    "function_var_decls",
    "function_body",
    "var2_init_decl",
    "function_block_type_name",
    "derived_function_block_name",
    "function_block_declaration",
    "java_block_declaration",
    "other_var_declarations",
    "temp_var_decls",
    "non_retentive_var_decls",
    "function_block_body",
    "program_type_name",
    "program_declaration",
    "program_access_decls",
    "program_access_decl",
    "configuration_name",
    "resource_type_name",
    "configuration_declaration",
    "resource_declaration",
    "single_resource_declaration",
    "resource_name",
    "access_declarations",
    "access_declaration",
    "access_path",
    "global_var_reference",
    "access_name",
    "program_output_reference",
    "program_name",
    "direction",
    "task_configuration",
    "task_name",
    "task_initialization",
    "data_source",
    "program_configuration",
    "prog_conf_elements",
    "prog_conf_element",
    "fb_task",
    "prog_cnxn",
    "prog_data_source",
    "data_sink",
    "instance_specific_initializations",
    "instance_specific_init",
    "label",
    "il_simple_operation",
    "il_expression",
    "il_jump_operation",
    "il_fb_call",
    "il_operand_list",
    "simple_instr_list",
    "il_simple_instruction",
    "il_param_list",
    "il_param_instruction",
    "il_param_last_instruction",
    "il_param_assignment",
    "il_param_out_assignment",
    "il_assign_operator",
    "il_assign_out_operator",
    "il_call_operator",
    "il_call_java_operator",
    "il_return_operator",
    "il_jump_operator",
  };
}
