
/*
 *  Supremica Software License Agreement
 *
 *  The Supremica software is not in the public domain
 *  However, it is freely available without fee for education,
 *  research, and non-profit purposes.  By obtaining copies of
 *  this and other files that comprise the Supremica software,
 *  you, the Licensee, agree to abide by the following
 *  conditions and understandings with respect to the
 *  copyrighted software:
 *
 *  The software is copyrighted in the name of Supremica,
 *  and ownership of the software remains with Supremica.
 *
 *  Permission to use, copy, and modify this software and its
 *  documentation for education, research, and non-profit
 *  purposes is hereby granted to Licensee, provided that the
 *  copyright notice, the original author's names and unit
 *  identification, and this permission notice appear on all
 *  such copies, and that no charge be made for such copies.
 *  Any entity desiring permission to incorporate this software
 *  into commercial products or to use it for commercial
 *  purposes should contact:
 *
 *  Knut Akesson (KA), knut@supremica.org
 *  Supremica,
 *  Haradsgatan 26A
 *  431 42 Molndal
 *  SWEDEN
 *
 *  to discuss license terms. No cost evaluation licenses are
 *  available.
 *
 *  Licensee may not use the name, logo, or any other symbol
 *  of Supremica nor the names of any of its employees nor
 *  any adaptation thereof in advertising or publicity
 *  pertaining to the software without specific prior written
 *  approval of the Supremica.
 *
 *  SUPREMICA AND KA MAKES NO REPRESENTATIONS ABOUT THE
 *  SUITABILITY OF THE SOFTWARE FOR ANY PURPOSE.
 *  IT IS PROVIDED "AS IS" WITHOUT EXPRESS OR IMPLIED WARRANTY.
 *
 *  Supremica or KA shall not be liable for any damages
 *  suffered by Licensee from the use of this software.
 *
 *  Supremica is owned and represented by KA.
 */
package org.supremica.automata.algorithms;

import java.util.*;
import org.supremica.gui.*;
import org.supremica.automata.Automata;

public class FileSecurity
{
	private Set superUsers = new HashSet();
	private String currentUser = null;
	private final static String superuserIdentity = WorkbenchProperties.getSuperuserIdentity();

	public FileSecurity()
	{
		superUsers.add(superuserIdentity);
	}

	public void setCurrentUser(String currentUser)
	{

		/*
		 *  if (currentUser != null)
		 *  { // Only allowed to login once
		 *  return;
		 *  }
		 */
		this.currentUser = currentUser;
	}

	public String getCurrentUser()
	{
		return currentUser;
	}

	public boolean hasCurrentUser()
	{
		return currentUser != null;
	}

	public boolean allowOpening(Automata theAutomata)
	{
		if (hasCurrentUser() && isSuperUser(currentUser))
		{
			return true;
		}

		if (!WorkbenchProperties.generalUseSecurity())
		{
			return true;
		}

		String owner = theAutomata.getOwner();

		if ((owner == null) || (owner.equals("")))
		{
			return false;
		}

		// Allow opening files generated by superuser and current user
		if (isSuperUser(owner) || owner.equals(currentUser))
		{

			// System.err.println("Nästan");
			String oldHash = theAutomata.getHash();
			String newHash = theAutomata.computeHash();

			if (oldHash.equals(newHash))
			{
				return true;
			}

			// System.err.println("hashfailed old:" + oldHash + " new: " + newHash);
			return false;
		}

		return false;
	}

	public boolean isSuperUser(String username)
	{
		return superUsers.contains(username);
	}

	public boolean allowSuperUserLogin()
	{
		return WorkbenchProperties.allowSuperUserLogin();
	}
}
