
/*
 * Supremica Software License Agreement
 *
 * The Supremica software is not in the public domain
 * However, it is freely available without fee for education,
 * research, and non-profit purposes.  By obtaining copies of
 * this and other files that comprise the Supremica software,
 * you, the Licensee, agree to abide by the following
 * conditions and understandings with respect to the
 * copyrighted software:
 *
 * The software is copyrighted in the name of Supremica,
 * and ownership of the software remains with Supremica.
 *
 * Permission to use, copy, and modify this software and its
 * documentation for education, research, and non-profit
 * purposes is hereby granted to Licensee, provided that the
 * copyright notice, the original author's names and unit
 * identification, and this permission notice appear on all
 * such copies, and that no charge be made for such copies.
 * Any entity desiring permission to incorporate this software
 * into commercial products or to use it for commercial
 * purposes should contact:
 *
 * Knut Akesson (KA), knut@supremica.org
 * Supremica,
 * Haradsgatan 26A
 * 431 42 Molndal
 * SWEDEN
 *
 * to discuss license terms. No cost evaluation licenses are
 * available.
 *
 * Licensee may not use the name, logo, or any other symbol
 * of Supremica nor the names of any of its employees nor
 * any adaptation thereof in advertising or publicity
 * pertaining to the software without specific prior written
 * approval of the Supremica.
 *
 * SUPREMICA AND KA MAKES NO REPRESENTATIONS ABOUT THE
 * SUITABILITY OF THE SOFTWARE FOR ANY PURPOSE.
 * IT IS PROVIDED "AS IS" WITHOUT EXPRESS OR IMPLIED WARRANTY.
 *
 * Supremica or KA shall not be liable for any damages
 * suffered by Licensee from the use of this software.
 *
 * Supremica is owned and represented by KA.
 */
package org.supremica.automata.algorithms;

import org.supremica.log.*;
import java.io.*;
import java.util.*;
import java.text.DateFormat;

public class IEC61131Helper
{

	public static void serializeAppBegin(PrintWriter pw, String fileName)
	{

		// Start of file header
		Date theDate = new Date();

		pw.println("(* This file is automatically generated from Supremica *)");
		pw.println("(* Supremica version: " + org.supremica.Version.version() + " *)");
		pw.println("(* This file was generated at: " +  DateFormat.getDateTimeInstance().format(new Date()) + " *)");
		//pw.println("(* Synchronization type: " + syncType.toString() + "*)");
		/*
		pw.println("(* The following automata are synchronized: *)");
		for (Iterator autIt = theAutomata.iterator(); autIt.hasNext();)
		{
			Automaton currAutomaton = (Automaton)autIt.next();
			printILComment(pw, "(* Automaton: " + currAutomaton.getName() + " *)");
		}*/
		pw.println("PROGRAM " + fileName);
	}

	public static void serializeAppEnd(PrintWriter pw)
	{
		pw.println("END_PROGRAM");
	}

	public static void serializeVarBegin(PrintWriter pw)
	{
		pw.println("VAR");
	}

	public void serializeBooleanVariableDeclaration(PrintWriter pw, String variableName, String comment)
	{
		pw.print("\t\t" + variableName + " : BOOL; ");
		if (comment != null)
		{
			pw.print(comment);
		}
		pw.println();
	}

	public static void serializeVarEnd(PrintWriter pw)
	{
		pw.println("END_VAR\n");
	}

	public static void serializeILBegin(PrintWriter pw)
	{
		pw.println("      CODEBLOCK Code COORD 0.0, 0.0 OBJSIZE 0.0, 0.0 :");
		pw.println("         INSTRUCTIONLIST");
	}

	public static void serializeILEnd(PrintWriter pw)
	{
		pw.println("\n         END_CODEBLOCK\n");
	}

	public static void serializeSTBegin(PrintWriter pw)
	{
		pw.println("      CODEBLOCK Code COORD 0.0, 0.0 OBJSIZE 0.0, 0.0 :");
		pw.println("         STRUCTUREDTEXT");
	}

	public static void serializeSTEnd(PrintWriter pw)
	{
		pw.println("\n         END_CODEBLOCK\n");
	}

	public static void serializePrj(PrintWriter pw, String fileName)
	{
		pw.println("'2002-01-11-16:24:38.775'");
		pw.println("Header");
		pw.println(" ( SyntaxVersion '3.0'");
		pw.println("   SavedDate '2002-01-11-16:47:35.825'");
		pw.println("   ChangedDate '2002-01-11-16:24:38.775'");
		pw.println("   FileName '" + fileName + "'\n\n  )");
		pw.println("FileUnits");
		pw.println(" ( Application");
		pw.println("    ( Name '" + fileName + "'");
		pw.println("      Directory '' ) )");
		pw.println("ControlSystem");
		pw.println(" ( Name\n Directory '' )");
		pw.println("ColorTable");
		pw.println(" ( ColorModel HLS\n )");
	}
}
