/**
 * This file is automatically generated from Supremica
 * Supremica version: 200404161407
 * This file was generated at: Apr 16, 2004 5:02:40 PM
 *
 * The following automata are synchronized.
 * The number is the index used in this file
 * to identify the automata.
 *   Automaton 0: "Progress spec: Manual or automatic mode"
 *   Automaton 1: "Progress spec: Gatekeeper (gk)"
 *   Automaton 2: "Progress spec: Elevate and measure (em)"
 *   Automaton 3: "Progress spec: Measure station - measure"
 *   Automaton 4: "Progress spec: Measure station - putter"
 *   Automaton 5: "Progress spec: Elevate and sort (es)"
 *   Automaton 6: "Interaction spec: GK and EM"
 *   Automaton 7: "Interaction spec: Measure station"
 *   Automaton 8: "Interaction spec: EM and ES"
 *   Automaton 9: "Interaction spec: ES and lower buffer"
 *   Automaton 10: "Interaction spec: ES and upper buffer"
 *   Automaton 11: "Plant: Manual button"
 *   Automaton 12: "Plant: Automatic button"
 *   Automaton 13: "Plant: Gatekeeper - In"
 *   Automaton 14: "Plant: Gatekeeper - Out"
 *   Automaton 15: "Plant: Elevator - Measure"
 *   Automaton 16: "Plant: Measure - Putter"
 *   Automaton 17: "Plant: Disable events"
 *   Automaton 18: "Extended Plant: GK and EM"
 *   Automaton 19: "Variable: size of ball"
 *   Automaton 20: "Timer: em.timer.before_up"
 *   Automaton 21: "Timer: em.timer.before_ballcheck"
 *   Automaton 22: "Timer: em.timer.measure"
 *   Automaton 23: "Timer: em.timer.before_put"
 *   Automaton 24: "Timer: em.timer.putting"
 *   Automaton 25: "Timer: es.timer.before_up"
 *   Automaton 26: "Timer: es.timer.before_ballcheck"
 *   Automaton 27: "Timer: es.timer.before_deput"
 *
 * Event indices and the corresponding event label
 *   Event 0: "arm.allocate_lower_buffer" controllable
 *   Event 1: "arm.allocate_upper_buffer" controllable
 *   Event 2: "arm.lower_lower_buffer" controllable
 *   Event 3: "arm.lower_upper_buffer" controllable
 *   Event 4: "arm.raise_lower_buffer" controllable
 *   Event 5: "arm.raise_upper_buffer" controllable
 *   Event 6: "arm.release_lower_buffer" controllable
 *   Event 7: "arm.release_upper_buffer" controllable
 *   Event 8: "button.automatic.pressed" uncontrollable
 *   Event 9: "button.automatic.released" uncontrollable
 *   Event 10: "button.manual.pressed" uncontrollable
 *   Event 11: "button.manual.released" uncontrollable
 *   Event 12: "em.ball_out_of_measure_station" uncontrollable
 *   Event 13: "em.elevator.allocate_station" controllable
 *   Event 14: "em.elevator.release_station" controllable
 *   Event 15: "em.enter_ball" controllable
 *   Event 16: "em.go_down" controllable
 *   Event 17: "em.go_up" controllable
 *   Event 18: "em.has_ball" uncontrollable
 *   Event 19: "em.is_down" uncontrollable
 *   Event 20: "em.is_up" uncontrollable
 *   Event 21: "em.large_ball" uncontrollable
 *   Event 22: "em.measure.allocate_station" controllable
 *   Event 23: "em.measure.finished" uncontrollable
 *   Event 24: "em.measure.go_in" controllable
 *   Event 25: "em.measure.go_out" controllable
 *   Event 26: "em.measure.has_ball" uncontrollable
 *   Event 27: "em.measure.has_no_ball" uncontrollable
 *   Event 28: "em.measure.release_station" controllable
 *   Event 29: "em.measure.start" controllable
 *   Event 30: "em.putter.allocate_station" controllable
 *   Event 31: "em.putter.finished" uncontrollable
 *   Event 32: "em.putter.go_in" controllable
 *   Event 33: "em.putter.go_out" controllable
 *   Event 34: "em.putter.is_in" controllable
 *   Event 35: "em.putter.is_out" controllable
 *   Event 36: "em.putter.release_station" controllable
 *   Event 37: "em.putter.start" controllable
 *   Event 38: "em.small_ball" uncontrollable
 *   Event 39: "em.timer.before_ballcheck.start" controllable
 *   Event 40: "em.timer.before_ballcheck.timeout" uncontrollable
 *   Event 41: "em.timer.before_put.start" controllable
 *   Event 42: "em.timer.before_put.timeout" uncontrollable
 *   Event 43: "em.timer.before_up.start" controllable
 *   Event 44: "em.timer.before_up.timeout" uncontrollable
 *   Event 45: "em.timer.measure.start" controllable
 *   Event 46: "em.timer.measure.timeout" uncontrollable
 *   Event 47: "em.timer.putting.start" controllable
 *   Event 48: "em.timer.putting.timeout" uncontrollable
 *   Event 49: "es.allocate_lower_buffer" controllable
 *   Event 50: "es.allocate_upper_buffer" controllable
 *   Event 51: "es.ball_lower_level" uncontrollable
 *   Event 52: "es.ball_upper_level" uncontrollable
 *   Event 53: "es.deput_ball_lower" controllable
 *   Event 54: "es.deput_ball_upper" controllable
 *   Event 55: "es.enter_ball" controllable
 *   Event 56: "es.go_down" controllable
 *   Event 57: "es.got_ball" controllable
 *   Event 58: "es.is_lower" uncontrollable
 *   Event 59: "es.is_not_down" controllable
 *   Event 60: "es.is_upper" uncontrollable
 *   Event 61: "es.lower_putter.go_in" controllable
 *   Event 62: "es.lower_putter.go_out" controllable
 *   Event 63: "es.no_ball_lower_level" uncontrollable
 *   Event 64: "es.no_ball_upper_level" uncontrollable
 *   Event 65: "es.put_ball_lower" controllable
 *   Event 66: "es.put_ball_upper" controllable
 *   Event 67: "es.release_lower_buffer" controllable
 *   Event 68: "es.release_upper_buffer" controllable
 *   Event 69: "es.timer.before_ballcheck.start" controllable
 *   Event 70: "es.timer.before_ballcheck.timeout" uncontrollable
 *   Event 71: "es.timer.before_deput.start" controllable
 *   Event 72: "es.timer.before_deput.timeout" uncontrollable
 *   Event 73: "es.timer.before_up.start" controllable
 *   Event 74: "es.timer.before_up.timeout" uncontrollable
 *   Event 75: "es.up_lower" controllable
 *   Event 76: "es.up_upper" controllable
 *   Event 77: "es.upper_putter.go_in" controllable
 *   Event 78: "es.upper_putter.go_out" controllable
 *   Event 79: "gk.ball_out_of_gatekeeper" uncontrollable
 *   Event 80: "gk.enter_ball" controllable
 *   Event 81: "gk.has_ball" uncontrollable
 *   Event 82: "gk.in.go_in" controllable
 *   Event 83: "gk.in.go_out" controllable
 *   Event 84: "gk.in.is_in" controllable
 *   Event 85: "gk.in.is_out" controllable
 *   Event 86: "gk.out.go_in" controllable
 *   Event 87: "gk.out.go_out" controllable
 *   Event 88: "gk.out.is_in" controllable
 *   Event 89: "gk.out.is_out" controllable
 *   Event 90: "gk.release_ball" controllable
 *   Event 91: "is_large_ball" controllable
 *   Event 92: "is_small_ball" controllable
 *   Event 93: "mode.automatic" controllable
 *   Event 94: "mode.manual" controllable
 */
public class BallProcess
{
	static final int NO_EVENT_IS_SELECTED = -1;
	static final int NR_OF_EVENTS = 95;
	static final int NR_OF_AUTOMATA = 28;

	/**
	 * Preferred scan cycle time in milliseconds.
	 * The program executes continously if the real
	 * scan cycle time is larger than this value.
	 */
	static final int PREFERRED_SCAN_CYCLE_TIME = 0;

	/**
	 * The enabled event that comes first in this array is executed.
	 * The uncontrollable events has the highest priority
	 */
	static final int[] EVENT_PRIORITY_QUEUE = new int[]{8, 9, 10, 11, 12, 18, 19, 20, 21, 23, 26, 27, 31, 38, 40, 42, 44, 46, 48, 51, 52, 58, 60, 63, 64, 70, 72, 74, 79, 81, 0, 1, 2, 3, 4, 5, 6, 7, 13, 14, 15, 16, 17, 22, 24, 25, 28, 29, 30, 32, 33, 34, 35, 36, 37, 39, 41, 43, 45, 47, 49, 50, 53, 54, 55, 56, 57, 59, 61, 62, 65, 66, 67, 68, 69, 71, 73, 75, 76, 77, 78, 80, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94};

	/**
	 * A map from event index to event label. Is not used by default.
	 */
	static final String[] EVENT_LABELS = new String[]{"arm.allocate_lower_buffer",
			"arm.allocate_upper_buffer",
			"arm.lower_lower_buffer",
			"arm.lower_upper_buffer",
			"arm.raise_lower_buffer",
			"arm.raise_upper_buffer",
			"arm.release_lower_buffer",
			"arm.release_upper_buffer",
			"button.automatic.pressed",
			"button.automatic.released",
			"button.manual.pressed",
			"button.manual.released",
			"em.ball_out_of_measure_station",
			"em.elevator.allocate_station",
			"em.elevator.release_station",
			"em.enter_ball",
			"em.go_down",
			"em.go_up",
			"em.has_ball",
			"em.is_down",
			"em.is_up",
			"em.large_ball",
			"em.measure.allocate_station",
			"em.measure.finished",
			"em.measure.go_in",
			"em.measure.go_out",
			"em.measure.has_ball",
			"em.measure.has_no_ball",
			"em.measure.release_station",
			"em.measure.start",
			"em.putter.allocate_station",
			"em.putter.finished",
			"em.putter.go_in",
			"em.putter.go_out",
			"em.putter.is_in",
			"em.putter.is_out",
			"em.putter.release_station",
			"em.putter.start",
			"em.small_ball",
			"em.timer.before_ballcheck.start",
			"em.timer.before_ballcheck.timeout",
			"em.timer.before_put.start",
			"em.timer.before_put.timeout",
			"em.timer.before_up.start",
			"em.timer.before_up.timeout",
			"em.timer.measure.start",
			"em.timer.measure.timeout",
			"em.timer.putting.start",
			"em.timer.putting.timeout",
			"es.allocate_lower_buffer",
			"es.allocate_upper_buffer",
			"es.ball_lower_level",
			"es.ball_upper_level",
			"es.deput_ball_lower",
			"es.deput_ball_upper",
			"es.enter_ball",
			"es.go_down",
			"es.got_ball",
			"es.is_lower",
			"es.is_not_down",
			"es.is_upper",
			"es.lower_putter.go_in",
			"es.lower_putter.go_out",
			"es.no_ball_lower_level",
			"es.no_ball_upper_level",
			"es.put_ball_lower",
			"es.put_ball_upper",
			"es.release_lower_buffer",
			"es.release_upper_buffer",
			"es.timer.before_ballcheck.start",
			"es.timer.before_ballcheck.timeout",
			"es.timer.before_deput.start",
			"es.timer.before_deput.timeout",
			"es.timer.before_up.start",
			"es.timer.before_up.timeout",
			"es.up_lower",
			"es.up_upper",
			"es.upper_putter.go_in",
			"es.upper_putter.go_out",
			"gk.ball_out_of_gatekeeper",
			"gk.enter_ball",
			"gk.has_ball",
			"gk.in.go_in",
			"gk.in.go_out",
			"gk.in.is_in",
			"gk.in.is_out",
			"gk.out.go_in",
			"gk.out.go_out",
			"gk.out.is_in",
			"gk.out.is_out",
			"gk.release_ball",
			"is_large_ball",
			"is_small_ball",
			"mode.automatic",
			"mode.manual"};

	/**
	 * This vector holds the current state.
	 * The indices corresponds to automata.
	 * The value of an element corresponds
	 * to the state of that automaton.
	 */
	static int[] currentState = new int[NR_OF_AUTOMATA];

	/**
	 * Intitialization function
	 */
	static void initialize()
	{
		// Add initialization code here
	}

	/**
	 * Checks if the event is enabled in the
	 * current state of the automata
	 * @param eventIndex
	 * @return <code>true</code> if the event is enabled. 
	 *         <code>false</code> otherwise.
	 */
	static boolean eventIsInternallyEnabled(int eventIndex)
	{
		switch (eventIndex)
		{
		case 0: // Event "arm.allocate_lower_buffer"
			return (currentState[9] == 0)
					&& (false /* Automaton 17 */);
		case 1: // Event "arm.allocate_upper_buffer"
			return (currentState[10] == 0)
					&& (false /* Automaton 17 */);
		case 2: // Event "arm.lower_lower_buffer"
			return (currentState[9] == 1);
		case 3: // Event "arm.lower_upper_buffer"
			return (currentState[10] == 1);
		case 4: // Event "arm.raise_lower_buffer"
			return (currentState[9] == 1);
		case 5: // Event "arm.raise_upper_buffer"
			return (currentState[10] == 1);
		case 6: // Event "arm.release_lower_buffer"
			return (currentState[9] == 1);
		case 7: // Event "arm.release_upper_buffer"
			return (currentState[10] == 1);
		case 8: // Event "button.automatic.pressed"
			return (currentState[12] == 0)
					&& (false /* Automaton 17 */);
		case 9: // Event "button.automatic.released"
			return (currentState[12] == 2);
		case 10: // Event "button.manual.pressed"
			return (currentState[11] == 0);
		case 11: // Event "button.manual.released"
			return (currentState[11] == 2);
		case 12: // Event "em.ball_out_of_measure_station"
			return (currentState[2] == 3);
		case 13: // Event "em.elevator.allocate_station"
			return (currentState[2] == 10 || currentState[2] == 6)
					&& (currentState[7] == 0);
		case 14: // Event "em.elevator.release_station"
			return (currentState[2] == 13 || currentState[2] == 7)
					&& (currentState[7] == 3);
		case 15: // Event "em.enter_ball"
			return (currentState[2] == 0)
					&& (currentState[6] == 1);
		case 16: // Event "em.go_down"
			return (currentState[2] == 5)
					&& (currentState[7] == 3)
					&& (currentState[15] == 0 || currentState[15] == 1);
		case 17: // Event "em.go_up"
			return (currentState[2] == 9)
					&& (currentState[7] == 3)
					&& (currentState[15] == 1 || currentState[15] == 0);
		case 18: // Event "em.has_ball"
			return (currentState[2] == 1)
					&& (currentState[6] == 4)
					&& (currentState[18] == 1);
		case 19: // Event "em.is_down"
			return (currentState[6] == 2)
					&& (currentState[15] == 0);
		case 20: // Event "em.is_up"
			return (currentState[2] == 11)
					&& (currentState[6] == 6)
					&& (currentState[15] == 1);
		case 21: // Event "em.large_ball"
			return (currentState[3] == 5)
					&& (currentState[19] == 0 || currentState[19] == 2);
		case 22: // Event "em.measure.allocate_station"
			return (currentState[3] == 1)
					&& (currentState[7] == 0);
		case 23: // Event "em.measure.finished"
			return (currentState[2] == 18)
					&& (currentState[3] == 8);
		case 24: // Event "em.measure.go_in"
			return (currentState[3] == 6)
					&& (currentState[7] == 1);
		case 25: // Event "em.measure.go_out"
			return (currentState[3] == 2)
					&& (currentState[7] == 1);
		case 26: // Event "em.measure.has_ball"
			return (currentState[2] == 15)
					&& (currentState[8] == 0);
		case 27: // Event "em.measure.has_no_ball"
			return (currentState[2] == 15);
		case 28: // Event "em.measure.release_station"
			return (currentState[3] == 7)
					&& (currentState[7] == 1);
		case 29: // Event "em.measure.start"
			return (currentState[2] == 16)
					&& (currentState[3] == 0);
		case 30: // Event "em.putter.allocate_station"
			return (currentState[4] == 1)
					&& (currentState[7] == 0);
		case 31: // Event "em.putter.finished"
			return (currentState[2] == 4)
					&& (currentState[4] == 7);
		case 32: // Event "em.putter.go_in"
			return (currentState[4] == 3)
					&& (currentState[7] == 2)
					&& (currentState[16] == 0 || currentState[16] == 1);
		case 33: // Event "em.putter.go_out"
			return (currentState[4] == 2)
					&& (currentState[7] == 2)
					&& (currentState[16] == 1 || currentState[16] == 0);
		case 34: // Event "em.putter.is_in"
			return (currentState[16] == 0)
					&& (false /* Automaton 17 */);
		case 35: // Event "em.putter.is_out"
			return (currentState[16] == 1)
					&& (false /* Automaton 17 */);
		case 36: // Event "em.putter.release_station"
			return (currentState[4] == 6)
					&& (currentState[7] == 2);
		case 37: // Event "em.putter.start"
			return (currentState[2] == 17)
					&& (currentState[4] == 0);
		case 38: // Event "em.small_ball"
			return (currentState[3] == 5)
					&& (currentState[19] == 0 || currentState[19] == 1);
		case 39: // Event "em.timer.before_ballcheck.start"
			return (currentState[2] == 12)
					&& (currentState[21] == 0 || currentState[21] == 1);
		case 40: // Event "em.timer.before_ballcheck.timeout"
			return (currentState[2] == 14)
					&& (currentState[21] == 1);
		case 41: // Event "em.timer.before_put.start"
			return (false /* Automaton 2 */)
					&& (currentState[23] == 0 || currentState[23] == 1);
		case 42: // Event "em.timer.before_put.timeout"
			return (false /* Automaton 2 */)
					&& (currentState[23] == 1);
		case 43: // Event "em.timer.before_up.start"
			return (currentState[2] == 2)
					&& (currentState[20] == 0 || currentState[20] == 1);
		case 44: // Event "em.timer.before_up.timeout"
			return (currentState[2] == 8)
					&& (currentState[20] == 1);
		case 45: // Event "em.timer.measure.start"
			return (currentState[3] == 3)
					&& (currentState[22] == 0 || currentState[22] == 1);
		case 46: // Event "em.timer.measure.timeout"
			return (currentState[3] == 4)
					&& (currentState[22] == 1);
		case 47: // Event "em.timer.putting.start"
			return (currentState[4] == 4)
					&& (currentState[24] == 0 || currentState[24] == 1);
		case 48: // Event "em.timer.putting.timeout"
			return (currentState[4] == 5)
					&& (currentState[24] == 1);
		case 49: // Event "es.allocate_lower_buffer"
			return (currentState[5] == 20)
					&& (currentState[9] == 0);
		case 50: // Event "es.allocate_upper_buffer"
			return (currentState[5] == 23)
					&& (currentState[10] == 0);
		case 51: // Event "es.ball_lower_level"
			return (currentState[5] == 21);
		case 52: // Event "es.ball_upper_level"
			return (currentState[5] == 24);
		case 53: // Event "es.deput_ball_lower"
			return (currentState[9] == 2);
		case 54: // Event "es.deput_ball_upper"
			return (currentState[10] == 2);
		case 55: // Event "es.enter_ball"
			return (currentState[5] == 0)
					&& (currentState[8] == 1);
		case 56: // Event "es.go_down"
			return (currentState[5] == 9);
		case 57: // Event "es.got_ball"
			return (currentState[5] == 1);
		case 58: // Event "es.is_lower"
			return (currentState[5] == 14);
		case 59: // Event "es.is_not_down"
			return (false /* Automaton 5 */);
		case 60: // Event "es.is_upper"
			return (currentState[5] == 15);
		case 61: // Event "es.lower_putter.go_in"
			return (currentState[5] == 5);
		case 62: // Event "es.lower_putter.go_out"
			return (currentState[5] == 22);
		case 63: // Event "es.no_ball_lower_level"
			return (currentState[5] == 21);
		case 64: // Event "es.no_ball_upper_level"
			return (currentState[5] == 24);
		case 65: // Event "es.put_ball_lower"
			return (currentState[9] == 2);
		case 66: // Event "es.put_ball_upper"
			return (currentState[10] == 2);
		case 67: // Event "es.release_lower_buffer"
			return (currentState[5] == 6)
					&& (currentState[9] == 2);
		case 68: // Event "es.release_upper_buffer"
			return (currentState[5] == 8)
					&& (currentState[10] == 2);
		case 69: // Event "es.timer.before_ballcheck.start"
			return (currentState[5] == 16 || currentState[5] == 17)
					&& (currentState[26] == 0 || currentState[26] == 1);
		case 70: // Event "es.timer.before_ballcheck.timeout"
			return (currentState[5] == 18 || currentState[5] == 19)
					&& (currentState[26] == 1);
		case 71: // Event "es.timer.before_deput.start"
			return (currentState[5] == 26 || currentState[5] == 27)
					&& (currentState[27] == 0 || currentState[27] == 1);
		case 72: // Event "es.timer.before_deput.timeout"
			return (currentState[5] == 3 || currentState[5] == 4)
					&& (currentState[27] == 1);
		case 73: // Event "es.timer.before_up.start"
			return (currentState[5] == 2)
					&& (currentState[25] == 0 || currentState[25] == 1);
		case 74: // Event "es.timer.before_up.timeout"
			return (currentState[5] == 10)
					&& (currentState[25] == 1);
		case 75: // Event "es.up_lower"
			return (currentState[5] == 12);
		case 76: // Event "es.up_upper"
			return (currentState[5] == 13);
		case 77: // Event "es.upper_putter.go_in"
			return (currentState[5] == 7);
		case 78: // Event "es.upper_putter.go_out"
			return (currentState[5] == 25);
		case 79: // Event "gk.ball_out_of_gatekeeper"
			return (currentState[1] == 6)
					&& (currentState[6] == 5);
		case 80: // Event "gk.enter_ball"
			return (currentState[0] == 1 || currentState[0] == 2 || currentState[0] == 3 || currentState[0] == 4 || currentState[0] == 5 || currentState[0] == 6 || currentState[0] == 7)
					&& (currentState[1] == 0);
		case 81: // Event "gk.has_ball"
			return (currentState[1] == 1)
					&& (currentState[6] == 0);
		case 82: // Event "gk.in.go_in"
			return (currentState[1] == 3)
					&& (currentState[13] == 0 || currentState[13] == 1);
		case 83: // Event "gk.in.go_out"
			return (currentState[1] == 2)
					&& (currentState[13] == 1 || currentState[13] == 0);
		case 84: // Event "gk.in.is_in"
			return (currentState[13] == 0)
					&& (false /* Automaton 17 */);
		case 85: // Event "gk.in.is_out"
			return (currentState[13] == 1)
					&& (false /* Automaton 17 */);
		case 86: // Event "gk.out.go_in"
			return (currentState[1] == 7)
					&& (currentState[14] == 0 || currentState[14] == 1);
		case 87: // Event "gk.out.go_out"
			return (currentState[1] == 5)
					&& (currentState[14] == 1 || currentState[14] == 0)
					&& (currentState[18] == 0);
		case 88: // Event "gk.out.is_in"
			return (currentState[14] == 0)
					&& (false /* Automaton 17 */);
		case 89: // Event "gk.out.is_out"
			return (currentState[14] == 1)
					&& (false /* Automaton 17 */);
		case 90: // Event "gk.release_ball"
			return (currentState[1] == 4)
					&& (currentState[6] == 3);
		case 91: // Event "is_large_ball"
			return (currentState[5] == 11)
					&& (currentState[19] == 1 || currentState[19] == 0);
		case 92: // Event "is_small_ball"
			return (currentState[5] == 11)
					&& (currentState[19] == 2 || currentState[19] == 0);
		case 93: // Event "mode.automatic"
			return (currentState[0] == 0 || currentState[0] == 1 || currentState[0] == 2 || currentState[0] == 3 || currentState[0] == 4 || currentState[0] == 5 || currentState[0] == 6 || currentState[0] == 7)
					&& (currentState[12] == 1);
		case 94: // Event "mode.manual"
			return (currentState[0] == 0 || currentState[0] == 1 || currentState[0] == 2 || currentState[0] == 3 || currentState[0] == 4 || currentState[0] == 5 || currentState[0] == 6 || currentState[0] == 7)
					&& (currentState[11] == 1);
		default:
			// Should never get here
			return false;
		}
	}

	/**
	 * Checks if the event is enabled by external
	 * conditions such as input signal values.
	 * @param eventIndex
	 * @return <code>true</code> if the event is enabled.
	 *         <code>false</code> otherwise.
	 */
	static boolean eventIsExternallyEnabled(int eventIndex)
	{
		// An external condition can for example be: SensorValue(0) == 2
		// All external conditions are true by default.
		switch (eventIndex)
		{
		case 0: // Event "arm.allocate_lower_buffer"
			return true;
		case 1: // Event "arm.allocate_upper_buffer"
			return true;
		case 2: // Event "arm.lower_lower_buffer"
			return true;
		case 3: // Event "arm.lower_upper_buffer"
			return true;
		case 4: // Event "arm.raise_lower_buffer"
			return true;
		case 5: // Event "arm.raise_upper_buffer"
			return true;
		case 6: // Event "arm.release_lower_buffer"
			return true;
		case 7: // Event "arm.release_upper_buffer"
			return true;
		case 8: // Event "button.automatic.pressed"
			return true;
		case 9: // Event "button.automatic.released"
			return true;
		case 10: // Event "button.manual.pressed"
			return true;
		case 11: // Event "button.manual.released"
			return true;
		case 12: // Event "em.ball_out_of_measure_station"
			return true;
		case 13: // Event "em.elevator.allocate_station"
			return true;
		case 14: // Event "em.elevator.release_station"
			return true;
		case 15: // Event "em.enter_ball"
			return true;
		case 16: // Event "em.go_down"
			return true;
		case 17: // Event "em.go_up"
			return true;
		case 18: // Event "em.has_ball"
			return true;
		case 19: // Event "em.is_down"
			return true;
		case 20: // Event "em.is_up"
			return true;
		case 21: // Event "em.large_ball"
			return true;
		case 22: // Event "em.measure.allocate_station"
			return true;
		case 23: // Event "em.measure.finished"
			return true;
		case 24: // Event "em.measure.go_in"
			return true;
		case 25: // Event "em.measure.go_out"
			return true;
		case 26: // Event "em.measure.has_ball"
			return true;
		case 27: // Event "em.measure.has_no_ball"
			return true;
		case 28: // Event "em.measure.release_station"
			return true;
		case 29: // Event "em.measure.start"
			return true;
		case 30: // Event "em.putter.allocate_station"
			return true;
		case 31: // Event "em.putter.finished"
			return true;
		case 32: // Event "em.putter.go_in"
			return true;
		case 33: // Event "em.putter.go_out"
			return true;
		case 34: // Event "em.putter.is_in"
			return true;
		case 35: // Event "em.putter.is_out"
			return true;
		case 36: // Event "em.putter.release_station"
			return true;
		case 37: // Event "em.putter.start"
			return true;
		case 38: // Event "em.small_ball"
			return true;
		case 39: // Event "em.timer.before_ballcheck.start"
			return true;
		case 40: // Event "em.timer.before_ballcheck.timeout"
			return true;
		case 41: // Event "em.timer.before_put.start"
			return true;
		case 42: // Event "em.timer.before_put.timeout"
			return true;
		case 43: // Event "em.timer.before_up.start"
			return true;
		case 44: // Event "em.timer.before_up.timeout"
			return true;
		case 45: // Event "em.timer.measure.start"
			return true;
		case 46: // Event "em.timer.measure.timeout"
			return true;
		case 47: // Event "em.timer.putting.start"
			return true;
		case 48: // Event "em.timer.putting.timeout"
			return true;
		case 49: // Event "es.allocate_lower_buffer"
			return true;
		case 50: // Event "es.allocate_upper_buffer"
			return true;
		case 51: // Event "es.ball_lower_level"
			return true;
		case 52: // Event "es.ball_upper_level"
			return true;
		case 53: // Event "es.deput_ball_lower"
			return true;
		case 54: // Event "es.deput_ball_upper"
			return true;
		case 55: // Event "es.enter_ball"
			return true;
		case 56: // Event "es.go_down"
			return true;
		case 57: // Event "es.got_ball"
			return true;
		case 58: // Event "es.is_lower"
			return true;
		case 59: // Event "es.is_not_down"
			return true;
		case 60: // Event "es.is_upper"
			return true;
		case 61: // Event "es.lower_putter.go_in"
			return true;
		case 62: // Event "es.lower_putter.go_out"
			return true;
		case 63: // Event "es.no_ball_lower_level"
			return true;
		case 64: // Event "es.no_ball_upper_level"
			return true;
		case 65: // Event "es.put_ball_lower"
			return true;
		case 66: // Event "es.put_ball_upper"
			return true;
		case 67: // Event "es.release_lower_buffer"
			return true;
		case 68: // Event "es.release_upper_buffer"
			return true;
		case 69: // Event "es.timer.before_ballcheck.start"
			return true;
		case 70: // Event "es.timer.before_ballcheck.timeout"
			return true;
		case 71: // Event "es.timer.before_deput.start"
			return true;
		case 72: // Event "es.timer.before_deput.timeout"
			return true;
		case 73: // Event "es.timer.before_up.start"
			return true;
		case 74: // Event "es.timer.before_up.timeout"
			return true;
		case 75: // Event "es.up_lower"
			return true;
		case 76: // Event "es.up_upper"
			return true;
		case 77: // Event "es.upper_putter.go_in"
			return true;
		case 78: // Event "es.upper_putter.go_out"
			return true;
		case 79: // Event "gk.ball_out_of_gatekeeper"
			return true;
		case 80: // Event "gk.enter_ball"
			return true;
		case 81: // Event "gk.has_ball"
			return true;
		case 82: // Event "gk.in.go_in"
			return true;
		case 83: // Event "gk.in.go_out"
			return true;
		case 84: // Event "gk.in.is_in"
			return true;
		case 85: // Event "gk.in.is_out"
			return true;
		case 86: // Event "gk.out.go_in"
			return true;
		case 87: // Event "gk.out.go_out"
			return true;
		case 88: // Event "gk.out.is_in"
			return true;
		case 89: // Event "gk.out.is_out"
			return true;
		case 90: // Event "gk.release_ball"
			return true;
		case 91: // Event "is_large_ball"
			return true;
		case 92: // Event "is_small_ball"
			return true;
		case 93: // Event "mode.automatic"
			return true;
		case 94: // Event "mode.manual"
			return true;
		default:
			// Should never get here
			return false;
		}
	}

	/**
	 * Updates the states of the automata
	 * @param eventIndex The executed event
	 */
	static void executeEventInternally(int eventIndex)
	{
		switch (eventIndex)
		{
		case NO_EVENT_IS_SELECTED: // If no event was enabled
			break;
		case 0: // Event "arm.allocate_lower_buffer"

			// Transitions in "Interaction spec: ES and lower buffer"
			if (currentState[9] == 0)
				currentState[9] = 1;

			// Transitions in "Plant: Disable events"
			break;
		case 1: // Event "arm.allocate_upper_buffer"

			// Transitions in "Interaction spec: ES and upper buffer"
			if (currentState[10] == 0)
				currentState[10] = 1;

			// Transitions in "Plant: Disable events"
			break;
		case 2: // Event "arm.lower_lower_buffer"

			// Transitions in "Interaction spec: ES and lower buffer"
			// currentState[9] == 1 has event 2 as self loop, no transition
			break;
		case 3: // Event "arm.lower_upper_buffer"

			// Transitions in "Interaction spec: ES and upper buffer"
			// currentState[10] == 1 has event 3 as self loop, no transition
			break;
		case 4: // Event "arm.raise_lower_buffer"

			// Transitions in "Interaction spec: ES and lower buffer"
			// currentState[9] == 1 has event 4 as self loop, no transition
			break;
		case 5: // Event "arm.raise_upper_buffer"

			// Transitions in "Interaction spec: ES and upper buffer"
			// currentState[10] == 1 has event 5 as self loop, no transition
			break;
		case 6: // Event "arm.release_lower_buffer"

			// Transitions in "Interaction spec: ES and lower buffer"
			if (currentState[9] == 1)
				currentState[9] = 0;
			break;
		case 7: // Event "arm.release_upper_buffer"

			// Transitions in "Interaction spec: ES and upper buffer"
			if (currentState[10] == 1)
				currentState[10] = 0;
			break;
		case 8: // Event "button.automatic.pressed"

			// Transitions in "Plant: Automatic button"
			if (currentState[12] == 0)
				currentState[12] = 1;

			// Transitions in "Plant: Disable events"
			break;
		case 9: // Event "button.automatic.released"

			// Transitions in "Plant: Automatic button"
			if (currentState[12] == 2)
				currentState[12] = 0;
			break;
		case 10: // Event "button.manual.pressed"

			// Transitions in "Plant: Manual button"
			if (currentState[11] == 0)
				currentState[11] = 1;
			break;
		case 11: // Event "button.manual.released"

			// Transitions in "Plant: Manual button"
			if (currentState[11] == 2)
				currentState[11] = 0;
			break;
		case 12: // Event "em.ball_out_of_measure_station"

			// Transitions in "Progress spec: Elevate and measure (em)"
			if (currentState[2] == 3)
				currentState[2] = 6;
			break;
		case 13: // Event "em.elevator.allocate_station"

			// Transitions in "Progress spec: Elevate and measure (em)"
			if (currentState[2] == 10)
				currentState[2] = 9;
			else if (currentState[2] == 6)
				currentState[2] = 5;

			// Transitions in "Interaction spec: Measure station"
			if (currentState[7] == 0)
				currentState[7] = 3;
			break;
		case 14: // Event "em.elevator.release_station"

			// Transitions in "Progress spec: Elevate and measure (em)"
			if (currentState[2] == 13)
				currentState[2] = 12;
			else if (currentState[2] == 7)
				currentState[2] = 0;

			// Transitions in "Interaction spec: Measure station"
			if (currentState[7] == 3)
				currentState[7] = 0;
			break;
		case 15: // Event "em.enter_ball"

			// Transitions in "Progress spec: Elevate and measure (em)"
			if (currentState[2] == 0)
				currentState[2] = 1;

			// Transitions in "Interaction spec: GK and EM"
			if (currentState[6] == 1)
				currentState[6] = 3;
			break;
		case 16: // Event "em.go_down"

			// Transitions in "Progress spec: Elevate and measure (em)"
			if (currentState[2] == 5)
				currentState[2] = 7;

			// Transitions in "Interaction spec: Measure station"
			// currentState[7] == 3 has event 16 as self loop, no transition

			// Transitions in "Plant: Elevator - Measure"
			// currentState[15] == 0 has event 16 as self loop, no transition
			if (currentState[15] == 1)
				currentState[15] = 0;
			break;
		case 17: // Event "em.go_up"

			// Transitions in "Progress spec: Elevate and measure (em)"
			if (currentState[2] == 9)
				currentState[2] = 11;

			// Transitions in "Interaction spec: Measure station"
			// currentState[7] == 3 has event 17 as self loop, no transition

			// Transitions in "Plant: Elevator - Measure"
			// currentState[15] == 1 has event 17 as self loop, no transition
			if (currentState[15] == 0)
				currentState[15] = 1;
			break;
		case 18: // Event "em.has_ball"

			// Transitions in "Progress spec: Elevate and measure (em)"
			if (currentState[2] == 1)
				currentState[2] = 2;

			// Transitions in "Interaction spec: GK and EM"
			if (currentState[6] == 4)
				currentState[6] = 5;

			// Transitions in "Extended Plant: GK and EM"
			if (currentState[18] == 1)
				currentState[18] = 0;
			break;
		case 19: // Event "em.is_down"

			// Transitions in "Interaction spec: GK and EM"
			if (currentState[6] == 2)
				currentState[6] = 1;

			// Transitions in "Plant: Elevator - Measure"
			// currentState[15] == 0 has event 19 as self loop, no transition
			break;
		case 20: // Event "em.is_up"

			// Transitions in "Progress spec: Elevate and measure (em)"
			if (currentState[2] == 11)
				currentState[2] = 13;

			// Transitions in "Interaction spec: GK and EM"
			if (currentState[6] == 6)
				currentState[6] = 0;

			// Transitions in "Plant: Elevator - Measure"
			// currentState[15] == 1 has event 20 as self loop, no transition
			break;
		case 21: // Event "em.large_ball"

			// Transitions in "Progress spec: Measure station - measure"
			if (currentState[3] == 5)
				currentState[3] = 6;

			// Transitions in "Variable: size of ball"
			if (currentState[19] == 0)
				currentState[19] = 1;
			else if (currentState[19] == 2)
				currentState[19] = 1;
			break;
		case 22: // Event "em.measure.allocate_station"

			// Transitions in "Progress spec: Measure station - measure"
			if (currentState[3] == 1)
				currentState[3] = 2;

			// Transitions in "Interaction spec: Measure station"
			if (currentState[7] == 0)
				currentState[7] = 1;
			break;
		case 23: // Event "em.measure.finished"

			// Transitions in "Progress spec: Elevate and measure (em)"
			if (currentState[2] == 18)
				currentState[2] = 17;

			// Transitions in "Progress spec: Measure station - measure"
			if (currentState[3] == 8)
				currentState[3] = 0;
			break;
		case 24: // Event "em.measure.go_in"

			// Transitions in "Progress spec: Measure station - measure"
			if (currentState[3] == 6)
				currentState[3] = 7;

			// Transitions in "Interaction spec: Measure station"
			// currentState[7] == 1 has event 24 as self loop, no transition
			break;
		case 25: // Event "em.measure.go_out"

			// Transitions in "Progress spec: Measure station - measure"
			if (currentState[3] == 2)
				currentState[3] = 3;

			// Transitions in "Interaction spec: Measure station"
			// currentState[7] == 1 has event 25 as self loop, no transition
			break;
		case 26: // Event "em.measure.has_ball"

			// Transitions in "Progress spec: Elevate and measure (em)"
			if (currentState[2] == 15)
				currentState[2] = 16;

			// Transitions in "Interaction spec: EM and ES"
			if (currentState[8] == 0)
				currentState[8] = 1;
			break;
		case 27: // Event "em.measure.has_no_ball"

			// Transitions in "Progress spec: Elevate and measure (em)"
			if (currentState[2] == 15)
				currentState[2] = 5;
			break;
		case 28: // Event "em.measure.release_station"

			// Transitions in "Progress spec: Measure station - measure"
			if (currentState[3] == 7)
				currentState[3] = 8;

			// Transitions in "Interaction spec: Measure station"
			if (currentState[7] == 1)
				currentState[7] = 0;
			break;
		case 29: // Event "em.measure.start"

			// Transitions in "Progress spec: Elevate and measure (em)"
			if (currentState[2] == 16)
				currentState[2] = 18;

			// Transitions in "Progress spec: Measure station - measure"
			if (currentState[3] == 0)
				currentState[3] = 1;
			break;
		case 30: // Event "em.putter.allocate_station"

			// Transitions in "Progress spec: Measure station - putter"
			if (currentState[4] == 1)
				currentState[4] = 2;

			// Transitions in "Interaction spec: Measure station"
			if (currentState[7] == 0)
				currentState[7] = 2;
			break;
		case 31: // Event "em.putter.finished"

			// Transitions in "Progress spec: Elevate and measure (em)"
			if (currentState[2] == 4)
				currentState[2] = 3;

			// Transitions in "Progress spec: Measure station - putter"
			if (currentState[4] == 7)
				currentState[4] = 0;
			break;
		case 32: // Event "em.putter.go_in"

			// Transitions in "Progress spec: Measure station - putter"
			if (currentState[4] == 3)
				currentState[4] = 6;

			// Transitions in "Interaction spec: Measure station"
			// currentState[7] == 2 has event 32 as self loop, no transition

			// Transitions in "Plant: Measure - Putter"
			// currentState[16] == 0 has event 32 as self loop, no transition
			if (currentState[16] == 1)
				currentState[16] = 0;
			break;
		case 33: // Event "em.putter.go_out"

			// Transitions in "Progress spec: Measure station - putter"
			if (currentState[4] == 2)
				currentState[4] = 4;

			// Transitions in "Interaction spec: Measure station"
			// currentState[7] == 2 has event 33 as self loop, no transition

			// Transitions in "Plant: Measure - Putter"
			// currentState[16] == 1 has event 33 as self loop, no transition
			if (currentState[16] == 0)
				currentState[16] = 1;
			break;
		case 34: // Event "em.putter.is_in"

			// Transitions in "Plant: Measure - Putter"
			// currentState[16] == 0 has event 34 as self loop, no transition

			// Transitions in "Plant: Disable events"
			break;
		case 35: // Event "em.putter.is_out"

			// Transitions in "Plant: Measure - Putter"
			// currentState[16] == 1 has event 35 as self loop, no transition

			// Transitions in "Plant: Disable events"
			break;
		case 36: // Event "em.putter.release_station"

			// Transitions in "Progress spec: Measure station - putter"
			if (currentState[4] == 6)
				currentState[4] = 7;

			// Transitions in "Interaction spec: Measure station"
			if (currentState[7] == 2)
				currentState[7] = 0;
			break;
		case 37: // Event "em.putter.start"

			// Transitions in "Progress spec: Elevate and measure (em)"
			if (currentState[2] == 17)
				currentState[2] = 4;

			// Transitions in "Progress spec: Measure station - putter"
			if (currentState[4] == 0)
				currentState[4] = 1;
			break;
		case 38: // Event "em.small_ball"

			// Transitions in "Progress spec: Measure station - measure"
			if (currentState[3] == 5)
				currentState[3] = 6;

			// Transitions in "Variable: size of ball"
			if (currentState[19] == 0)
				currentState[19] = 2;
			else if (currentState[19] == 1)
				currentState[19] = 2;
			break;
		case 39: // Event "em.timer.before_ballcheck.start"

			// Transitions in "Progress spec: Elevate and measure (em)"
			if (currentState[2] == 12)
				currentState[2] = 14;

			// Transitions in "Timer: em.timer.before_ballcheck"
			if (currentState[21] == 0)
				currentState[21] = 1;
			// currentState[21] == 1 has event 39 as self loop, no transition
			break;
		case 40: // Event "em.timer.before_ballcheck.timeout"

			// Transitions in "Progress spec: Elevate and measure (em)"
			if (currentState[2] == 14)
				currentState[2] = 15;

			// Transitions in "Timer: em.timer.before_ballcheck"
			if (currentState[21] == 1)
				currentState[21] = 0;
			break;
		case 41: // Event "em.timer.before_put.start"

			// Transitions in "Progress spec: Elevate and measure (em)"

			// Transitions in "Timer: em.timer.before_put"
			if (currentState[23] == 0)
				currentState[23] = 1;
			// currentState[23] == 1 has event 41 as self loop, no transition
			break;
		case 42: // Event "em.timer.before_put.timeout"

			// Transitions in "Progress spec: Elevate and measure (em)"

			// Transitions in "Timer: em.timer.before_put"
			if (currentState[23] == 1)
				currentState[23] = 0;
			break;
		case 43: // Event "em.timer.before_up.start"

			// Transitions in "Progress spec: Elevate and measure (em)"
			if (currentState[2] == 2)
				currentState[2] = 8;

			// Transitions in "Timer: em.timer.before_up"
			if (currentState[20] == 0)
				currentState[20] = 1;
			// currentState[20] == 1 has event 43 as self loop, no transition
			break;
		case 44: // Event "em.timer.before_up.timeout"

			// Transitions in "Progress spec: Elevate and measure (em)"
			if (currentState[2] == 8)
				currentState[2] = 10;

			// Transitions in "Timer: em.timer.before_up"
			if (currentState[20] == 1)
				currentState[20] = 0;
			break;
		case 45: // Event "em.timer.measure.start"

			// Transitions in "Progress spec: Measure station - measure"
			if (currentState[3] == 3)
				currentState[3] = 4;

			// Transitions in "Timer: em.timer.measure"
			if (currentState[22] == 0)
				currentState[22] = 1;
			// currentState[22] == 1 has event 45 as self loop, no transition
			break;
		case 46: // Event "em.timer.measure.timeout"

			// Transitions in "Progress spec: Measure station - measure"
			if (currentState[3] == 4)
				currentState[3] = 5;

			// Transitions in "Timer: em.timer.measure"
			if (currentState[22] == 1)
				currentState[22] = 0;
			break;
		case 47: // Event "em.timer.putting.start"

			// Transitions in "Progress spec: Measure station - putter"
			if (currentState[4] == 4)
				currentState[4] = 5;

			// Transitions in "Timer: em.timer.putting"
			if (currentState[24] == 0)
				currentState[24] = 1;
			// currentState[24] == 1 has event 47 as self loop, no transition
			break;
		case 48: // Event "em.timer.putting.timeout"

			// Transitions in "Progress spec: Measure station - putter"
			if (currentState[4] == 5)
				currentState[4] = 3;

			// Transitions in "Timer: em.timer.putting"
			if (currentState[24] == 1)
				currentState[24] = 0;
			break;
		case 49: // Event "es.allocate_lower_buffer"

			// Transitions in "Progress spec: Elevate and sort (es)"
			if (currentState[5] == 20)
				currentState[5] = 22;

			// Transitions in "Interaction spec: ES and lower buffer"
			if (currentState[9] == 0)
				currentState[9] = 2;
			break;
		case 50: // Event "es.allocate_upper_buffer"

			// Transitions in "Progress spec: Elevate and sort (es)"
			if (currentState[5] == 23)
				currentState[5] = 25;

			// Transitions in "Interaction spec: ES and upper buffer"
			if (currentState[10] == 0)
				currentState[10] = 2;
			break;
		case 51: // Event "es.ball_lower_level"

			// Transitions in "Progress spec: Elevate and sort (es)"
			if (currentState[5] == 21)
				currentState[5] = 20;
			break;
		case 52: // Event "es.ball_upper_level"

			// Transitions in "Progress spec: Elevate and sort (es)"
			if (currentState[5] == 24)
				currentState[5] = 23;
			break;
		case 53: // Event "es.deput_ball_lower"

			// Transitions in "Interaction spec: ES and lower buffer"
			// currentState[9] == 2 has event 53 as self loop, no transition
			break;
		case 54: // Event "es.deput_ball_upper"

			// Transitions in "Interaction spec: ES and upper buffer"
			// currentState[10] == 2 has event 54 as self loop, no transition
			break;
		case 55: // Event "es.enter_ball"

			// Transitions in "Progress spec: Elevate and sort (es)"
			if (currentState[5] == 0)
				currentState[5] = 1;

			// Transitions in "Interaction spec: EM and ES"
			if (currentState[8] == 1)
				currentState[8] = 0;
			break;
		case 56: // Event "es.go_down"

			// Transitions in "Progress spec: Elevate and sort (es)"
			if (currentState[5] == 9)
				currentState[5] = 0;
			break;
		case 57: // Event "es.got_ball"

			// Transitions in "Progress spec: Elevate and sort (es)"
			if (currentState[5] == 1)
				currentState[5] = 2;
			break;
		case 58: // Event "es.is_lower"

			// Transitions in "Progress spec: Elevate and sort (es)"
			if (currentState[5] == 14)
				currentState[5] = 16;
			break;
		case 59: // Event "es.is_not_down"

			// Transitions in "Progress spec: Elevate and sort (es)"
			break;
		case 60: // Event "es.is_upper"

			// Transitions in "Progress spec: Elevate and sort (es)"
			if (currentState[5] == 15)
				currentState[5] = 17;
			break;
		case 61: // Event "es.lower_putter.go_in"

			// Transitions in "Progress spec: Elevate and sort (es)"
			if (currentState[5] == 5)
				currentState[5] = 6;
			break;
		case 62: // Event "es.lower_putter.go_out"

			// Transitions in "Progress spec: Elevate and sort (es)"
			if (currentState[5] == 22)
				currentState[5] = 26;
			break;
		case 63: // Event "es.no_ball_lower_level"

			// Transitions in "Progress spec: Elevate and sort (es)"
			if (currentState[5] == 21)
				currentState[5] = 9;
			break;
		case 64: // Event "es.no_ball_upper_level"

			// Transitions in "Progress spec: Elevate and sort (es)"
			if (currentState[5] == 24)
				currentState[5] = 9;
			break;
		case 65: // Event "es.put_ball_lower"

			// Transitions in "Interaction spec: ES and lower buffer"
			// currentState[9] == 2 has event 65 as self loop, no transition
			break;
		case 66: // Event "es.put_ball_upper"

			// Transitions in "Interaction spec: ES and upper buffer"
			// currentState[10] == 2 has event 66 as self loop, no transition
			break;
		case 67: // Event "es.release_lower_buffer"

			// Transitions in "Progress spec: Elevate and sort (es)"
			if (currentState[5] == 6)
				currentState[5] = 9;

			// Transitions in "Interaction spec: ES and lower buffer"
			if (currentState[9] == 2)
				currentState[9] = 0;
			break;
		case 68: // Event "es.release_upper_buffer"

			// Transitions in "Progress spec: Elevate and sort (es)"
			if (currentState[5] == 8)
				currentState[5] = 9;

			// Transitions in "Interaction spec: ES and upper buffer"
			if (currentState[10] == 2)
				currentState[10] = 0;
			break;
		case 69: // Event "es.timer.before_ballcheck.start"

			// Transitions in "Progress spec: Elevate and sort (es)"
			if (currentState[5] == 16)
				currentState[5] = 18;
			else if (currentState[5] == 17)
				currentState[5] = 19;

			// Transitions in "Timer: es.timer.before_ballcheck"
			if (currentState[26] == 0)
				currentState[26] = 1;
			// currentState[26] == 1 has event 69 as self loop, no transition
			break;
		case 70: // Event "es.timer.before_ballcheck.timeout"

			// Transitions in "Progress spec: Elevate and sort (es)"
			if (currentState[5] == 18)
				currentState[5] = 21;
			else if (currentState[5] == 19)
				currentState[5] = 24;

			// Transitions in "Timer: es.timer.before_ballcheck"
			if (currentState[26] == 1)
				currentState[26] = 0;
			break;
		case 71: // Event "es.timer.before_deput.start"

			// Transitions in "Progress spec: Elevate and sort (es)"
			if (currentState[5] == 26)
				currentState[5] = 3;
			else if (currentState[5] == 27)
				currentState[5] = 4;

			// Transitions in "Timer: es.timer.before_deput"
			if (currentState[27] == 0)
				currentState[27] = 1;
			// currentState[27] == 1 has event 71 as self loop, no transition
			break;
		case 72: // Event "es.timer.before_deput.timeout"

			// Transitions in "Progress spec: Elevate and sort (es)"
			if (currentState[5] == 3)
				currentState[5] = 5;
			else if (currentState[5] == 4)
				currentState[5] = 7;

			// Transitions in "Timer: es.timer.before_deput"
			if (currentState[27] == 1)
				currentState[27] = 0;
			break;
		case 73: // Event "es.timer.before_up.start"

			// Transitions in "Progress spec: Elevate and sort (es)"
			if (currentState[5] == 2)
				currentState[5] = 10;

			// Transitions in "Timer: es.timer.before_up"
			if (currentState[25] == 0)
				currentState[25] = 1;
			// currentState[25] == 1 has event 73 as self loop, no transition
			break;
		case 74: // Event "es.timer.before_up.timeout"

			// Transitions in "Progress spec: Elevate and sort (es)"
			if (currentState[5] == 10)
				currentState[5] = 11;

			// Transitions in "Timer: es.timer.before_up"
			if (currentState[25] == 1)
				currentState[25] = 0;
			break;
		case 75: // Event "es.up_lower"

			// Transitions in "Progress spec: Elevate and sort (es)"
			if (currentState[5] == 12)
				currentState[5] = 14;
			break;
		case 76: // Event "es.up_upper"

			// Transitions in "Progress spec: Elevate and sort (es)"
			if (currentState[5] == 13)
				currentState[5] = 15;
			break;
		case 77: // Event "es.upper_putter.go_in"

			// Transitions in "Progress spec: Elevate and sort (es)"
			if (currentState[5] == 7)
				currentState[5] = 8;
			break;
		case 78: // Event "es.upper_putter.go_out"

			// Transitions in "Progress spec: Elevate and sort (es)"
			if (currentState[5] == 25)
				currentState[5] = 27;
			break;
		case 79: // Event "gk.ball_out_of_gatekeeper"

			// Transitions in "Progress spec: Gatekeeper (gk)"
			if (currentState[1] == 6)
				currentState[1] = 7;

			// Transitions in "Interaction spec: GK and EM"
			if (currentState[6] == 5)
				currentState[6] = 6;
			break;
		case 80: // Event "gk.enter_ball"

			// Transitions in "Progress spec: Manual or automatic mode"
			if (currentState[0] == 1)
				currentState[0] = 0;
			else if (currentState[0] == 2)
				currentState[0] = 3;
			else if (currentState[0] == 3)
				currentState[0] = 4;
			else if (currentState[0] == 4)
				currentState[0] = 5;
			else if (currentState[0] == 5)
				currentState[0] = 6;
			else if (currentState[0] == 6)
				currentState[0] = 7;
			else if (currentState[0] == 7)
				currentState[0] = 0;

			// Transitions in "Progress spec: Gatekeeper (gk)"
			if (currentState[1] == 0)
				currentState[1] = 2;
			break;
		case 81: // Event "gk.has_ball"

			// Transitions in "Progress spec: Gatekeeper (gk)"
			if (currentState[1] == 1)
				currentState[1] = 3;

			// Transitions in "Interaction spec: GK and EM"
			if (currentState[6] == 0)
				currentState[6] = 2;
			break;
		case 82: // Event "gk.in.go_in"

			// Transitions in "Progress spec: Gatekeeper (gk)"
			if (currentState[1] == 3)
				currentState[1] = 4;

			// Transitions in "Plant: Gatekeeper - In"
			// currentState[13] == 0 has event 82 as self loop, no transition
			if (currentState[13] == 1)
				currentState[13] = 0;
			break;
		case 83: // Event "gk.in.go_out"

			// Transitions in "Progress spec: Gatekeeper (gk)"
			if (currentState[1] == 2)
				currentState[1] = 1;

			// Transitions in "Plant: Gatekeeper - In"
			// currentState[13] == 1 has event 83 as self loop, no transition
			if (currentState[13] == 0)
				currentState[13] = 1;
			break;
		case 84: // Event "gk.in.is_in"

			// Transitions in "Plant: Gatekeeper - In"
			// currentState[13] == 0 has event 84 as self loop, no transition

			// Transitions in "Plant: Disable events"
			break;
		case 85: // Event "gk.in.is_out"

			// Transitions in "Plant: Gatekeeper - In"
			// currentState[13] == 1 has event 85 as self loop, no transition

			// Transitions in "Plant: Disable events"
			break;
		case 86: // Event "gk.out.go_in"

			// Transitions in "Progress spec: Gatekeeper (gk)"
			if (currentState[1] == 7)
				currentState[1] = 0;

			// Transitions in "Plant: Gatekeeper - Out"
			// currentState[14] == 0 has event 86 as self loop, no transition
			if (currentState[14] == 1)
				currentState[14] = 0;
			break;
		case 87: // Event "gk.out.go_out"

			// Transitions in "Progress spec: Gatekeeper (gk)"
			if (currentState[1] == 5)
				currentState[1] = 6;

			// Transitions in "Plant: Gatekeeper - Out"
			// currentState[14] == 1 has event 87 as self loop, no transition
			if (currentState[14] == 0)
				currentState[14] = 1;

			// Transitions in "Extended Plant: GK and EM"
			if (currentState[18] == 0)
				currentState[18] = 1;
			break;
		case 88: // Event "gk.out.is_in"

			// Transitions in "Plant: Gatekeeper - Out"
			// currentState[14] == 0 has event 88 as self loop, no transition

			// Transitions in "Plant: Disable events"
			break;
		case 89: // Event "gk.out.is_out"

			// Transitions in "Plant: Gatekeeper - Out"
			// currentState[14] == 1 has event 89 as self loop, no transition

			// Transitions in "Plant: Disable events"
			break;
		case 90: // Event "gk.release_ball"

			// Transitions in "Progress spec: Gatekeeper (gk)"
			if (currentState[1] == 4)
				currentState[1] = 5;

			// Transitions in "Interaction spec: GK and EM"
			if (currentState[6] == 3)
				currentState[6] = 4;
			break;
		case 91: // Event "is_large_ball"

			// Transitions in "Progress spec: Elevate and sort (es)"
			if (currentState[5] == 11)
				currentState[5] = 13;

			// Transitions in "Variable: size of ball"
			// currentState[19] == 1 has event 91 as self loop, no transition
			// currentState[19] == 0 has event 91 as self loop, no transition
			break;
		case 92: // Event "is_small_ball"

			// Transitions in "Progress spec: Elevate and sort (es)"
			if (currentState[5] == 11)
				currentState[5] = 12;

			// Transitions in "Variable: size of ball"
			// currentState[19] == 2 has event 92 as self loop, no transition
			// currentState[19] == 0 has event 92 as self loop, no transition
			break;
		case 93: // Event "mode.automatic"

			// Transitions in "Progress spec: Manual or automatic mode"
			if (currentState[0] == 0)
				currentState[0] = 2;
			// currentState[0] == 1 has event 93 as self loop, no transition
			// currentState[0] == 2 has event 93 as self loop, no transition
			// currentState[0] == 3 has event 93 as self loop, no transition
			// currentState[0] == 4 has event 93 as self loop, no transition
			// currentState[0] == 5 has event 93 as self loop, no transition
			// currentState[0] == 6 has event 93 as self loop, no transition
			// currentState[0] == 7 has event 93 as self loop, no transition

			// Transitions in "Plant: Automatic button"
			if (currentState[12] == 1)
				currentState[12] = 2;
			break;
		case 94: // Event "mode.manual"

			// Transitions in "Progress spec: Manual or automatic mode"
			if (currentState[0] == 0)
				currentState[0] = 1;
			// currentState[0] == 1 has event 94 as self loop, no transition
			// currentState[0] == 2 has event 94 as self loop, no transition
			// currentState[0] == 3 has event 94 as self loop, no transition
			// currentState[0] == 4 has event 94 as self loop, no transition
			// currentState[0] == 5 has event 94 as self loop, no transition
			// currentState[0] == 6 has event 94 as self loop, no transition
			// currentState[0] == 7 has event 94 as self loop, no transition

			// Transitions in "Plant: Manual button"
			if (currentState[11] == 1)
				currentState[11] = 2;
			break;
		default:
			// Should never get here
		}
	}

	/**
	 * Sets output signals according to the executed event
	 * @param eventIndex The executed event
	 */
	static void executeEventExternally(int eventIndex)
	{
		// Add actions here, the default does not change anything. Example:
		// SetGlobalOutput(OUT_A, OUT_ON); // enable output A;
		switch (eventIndex)
		{
		case NO_EVENT_IS_SELECTED: // If no event was enabled
			break;
		case 0: // Event "arm.allocate_lower_buffer"
			break;
		case 1: // Event "arm.allocate_upper_buffer"
			break;
		case 2: // Event "arm.lower_lower_buffer"
			break;
		case 3: // Event "arm.lower_upper_buffer"
			break;
		case 4: // Event "arm.raise_lower_buffer"
			break;
		case 5: // Event "arm.raise_upper_buffer"
			break;
		case 6: // Event "arm.release_lower_buffer"
			break;
		case 7: // Event "arm.release_upper_buffer"
			break;
		case 8: // Event "button.automatic.pressed"
			break;
		case 9: // Event "button.automatic.released"
			break;
		case 10: // Event "button.manual.pressed"
			break;
		case 11: // Event "button.manual.released"
			break;
		case 12: // Event "em.ball_out_of_measure_station"
			break;
		case 13: // Event "em.elevator.allocate_station"
			break;
		case 14: // Event "em.elevator.release_station"
			break;
		case 15: // Event "em.enter_ball"
			break;
		case 16: // Event "em.go_down"
			break;
		case 17: // Event "em.go_up"
			break;
		case 18: // Event "em.has_ball"
			break;
		case 19: // Event "em.is_down"
			break;
		case 20: // Event "em.is_up"
			break;
		case 21: // Event "em.large_ball"
			break;
		case 22: // Event "em.measure.allocate_station"
			break;
		case 23: // Event "em.measure.finished"
			break;
		case 24: // Event "em.measure.go_in"
			break;
		case 25: // Event "em.measure.go_out"
			break;
		case 26: // Event "em.measure.has_ball"
			break;
		case 27: // Event "em.measure.has_no_ball"
			break;
		case 28: // Event "em.measure.release_station"
			break;
		case 29: // Event "em.measure.start"
			break;
		case 30: // Event "em.putter.allocate_station"
			break;
		case 31: // Event "em.putter.finished"
			break;
		case 32: // Event "em.putter.go_in"
			break;
		case 33: // Event "em.putter.go_out"
			break;
		case 34: // Event "em.putter.is_in"
			break;
		case 35: // Event "em.putter.is_out"
			break;
		case 36: // Event "em.putter.release_station"
			break;
		case 37: // Event "em.putter.start"
			break;
		case 38: // Event "em.small_ball"
			break;
		case 39: // Event "em.timer.before_ballcheck.start"
			break;
		case 40: // Event "em.timer.before_ballcheck.timeout"
			break;
		case 41: // Event "em.timer.before_put.start"
			break;
		case 42: // Event "em.timer.before_put.timeout"
			break;
		case 43: // Event "em.timer.before_up.start"
			break;
		case 44: // Event "em.timer.before_up.timeout"
			break;
		case 45: // Event "em.timer.measure.start"
			break;
		case 46: // Event "em.timer.measure.timeout"
			break;
		case 47: // Event "em.timer.putting.start"
			break;
		case 48: // Event "em.timer.putting.timeout"
			break;
		case 49: // Event "es.allocate_lower_buffer"
			break;
		case 50: // Event "es.allocate_upper_buffer"
			break;
		case 51: // Event "es.ball_lower_level"
			break;
		case 52: // Event "es.ball_upper_level"
			break;
		case 53: // Event "es.deput_ball_lower"
			break;
		case 54: // Event "es.deput_ball_upper"
			break;
		case 55: // Event "es.enter_ball"
			break;
		case 56: // Event "es.go_down"
			break;
		case 57: // Event "es.got_ball"
			break;
		case 58: // Event "es.is_lower"
			break;
		case 59: // Event "es.is_not_down"
			break;
		case 60: // Event "es.is_upper"
			break;
		case 61: // Event "es.lower_putter.go_in"
			break;
		case 62: // Event "es.lower_putter.go_out"
			break;
		case 63: // Event "es.no_ball_lower_level"
			break;
		case 64: // Event "es.no_ball_upper_level"
			break;
		case 65: // Event "es.put_ball_lower"
			break;
		case 66: // Event "es.put_ball_upper"
			break;
		case 67: // Event "es.release_lower_buffer"
			break;
		case 68: // Event "es.release_upper_buffer"
			break;
		case 69: // Event "es.timer.before_ballcheck.start"
			break;
		case 70: // Event "es.timer.before_ballcheck.timeout"
			break;
		case 71: // Event "es.timer.before_deput.start"
			break;
		case 72: // Event "es.timer.before_deput.timeout"
			break;
		case 73: // Event "es.timer.before_up.start"
			break;
		case 74: // Event "es.timer.before_up.timeout"
			break;
		case 75: // Event "es.up_lower"
			break;
		case 76: // Event "es.up_upper"
			break;
		case 77: // Event "es.upper_putter.go_in"
			break;
		case 78: // Event "es.upper_putter.go_out"
			break;
		case 79: // Event "gk.ball_out_of_gatekeeper"
			break;
		case 80: // Event "gk.enter_ball"
			break;
		case 81: // Event "gk.has_ball"
			break;
		case 82: // Event "gk.in.go_in"
			break;
		case 83: // Event "gk.in.go_out"
			break;
		case 84: // Event "gk.in.is_in"
			break;
		case 85: // Event "gk.in.is_out"
			break;
		case 86: // Event "gk.out.go_in"
			break;
		case 87: // Event "gk.out.go_out"
			break;
		case 88: // Event "gk.out.is_in"
			break;
		case 89: // Event "gk.out.is_out"
			break;
		case 90: // Event "gk.release_ball"
			break;
		case 91: // Event "is_large_ball"
			break;
		case 92: // Event "is_small_ball"
			break;
		case 93: // Event "mode.automatic"
			break;
		case 94: // Event "mode.manual"
			break;
		default:
			// Should never get here
		}
	}

	public static void main(String[] args)
	{
		// The index of the event that is selected to be executed
		int eventToBeExecuted = NO_EVENT_IS_SELECTED;
		
		// Set current state to the initial state
		for (int i = 0; i < currentState.length; ++i)
			currentState[i] = 0;

		// Initialize the supervisor
		initialize();
		
		long timeOfLastScan = System.currentTimeMillis();
		long timeToSleep;
		
		// Main scancycle
		while (true)
		{
			eventToBeExecuted = NO_EVENT_IS_SELECTED;

			/*
			 * Select the first event that is enabled.
			 * Search in the order that is given by the
			 * priority queue. Uncontrollable events
			 * lies first in the queue and are thus
			 * selected first. For an event to be
			 * enabled, it has to be enabled in the
			 * current internal state as well as 
			 * by external input signals.
			 */
			for (int i = 0; i < NR_OF_EVENTS && eventToBeExecuted == NO_EVENT_IS_SELECTED; ++i)
				if (eventIsInternallyEnabled(EVENT_PRIORITY_QUEUE[i]) && eventIsExternallyEnabled(EVENT_PRIORITY_QUEUE[i]))
					eventToBeExecuted = EVENT_PRIORITY_QUEUE[i];

			// Set outputs
			executeEventExternally(eventToBeExecuted);
			
			// Update state
			executeEventInternally(eventToBeExecuted);
			
			// For debugging
			//System.out.println(EVENT_LABELS[eventToBeExecuted]);
			
			/*
			 * For a constant scan cycle time, set
			 * PREFERRED_SCAN_CYCLE_TIME to a value larger than
			 * the real scan cycle time. 
			 */
			timeToSleep = PREFERRED_SCAN_CYCLE_TIME - (System.currentTimeMillis() - timeOfLastScan); 
			if (timeToSleep > 0)
			{
				try
				{
					Thread.sleep(timeToSleep);
				}
				catch(InterruptedException e){}
			}
			timeOfLastScan = System.currentTimeMillis();
		}
	}
}
