//# -*- indent-tabs-mode: nil  c-basic-offset: 2 -*-
//###########################################################################
//# PROJECT: Waters
//# PACKAGE: net.sourceforge.waters.model.compiler.efa
//# CLASS:   EFAEvent
//###########################################################################
//# $Id$
//###########################################################################

package net.sourceforge.waters.model.compiler.efa;

import net.sourceforge.waters.model.compiler.dnf.CompiledClause;
import net.sourceforge.waters.model.module.IdentifierProxy;


/**
 * A compiler-internal representation of an event generated by the EFA
 * compiler.
 *
 * @see {@link EFACompiler}.
 * @author Robi Malik
 */

class EFAEvent {

  //#########################################################################
  //# Constructors
  EFAEvent(final EFAEventDecl edecl, final CompiledClause conditions)
  {
    mEventDecl = edecl;
    mConditions = conditions;
  }


  //#########################################################################
  //# Simple Access
  IdentifierProxy createIdentifier()
  {
    return null;
  }


  //#########################################################################
  //# Data Members
  private final EFAEventDecl mEventDecl;
  private final CompiledClause mConditions;

}
