//# -*- indent-tabs-mode: nil  c-basic-offset: 2 -*-
//###########################################################################
//# PROJECT: Waters
//# PACKAGE: net.sourceforge.waters.model.compiler.efa
//# CLASS:   EFAEvent
//###########################################################################
//# $Id$
//###########################################################################

package net.sourceforge.waters.model.compiler.efa;

import net.sourceforge.waters.model.compiler.constraint.ConstraintList;
import net.sourceforge.waters.model.module.EventDeclProxy;
import net.sourceforge.waters.model.module.IdentifierProxy;
import net.sourceforge.waters.model.module.ModuleProxyFactory;
import net.sourceforge.waters.model.module.ModuleProxyCloner;
import net.sourceforge.waters.model.module.QualifiedIdentifierProxy;


/**
 * A compiler-internal representation of an atomic event in a system of
 * synchronised EFA. This class represents the actual events generated by
 * the compiler. Each EFA event has an associated event declararion ({@link
 * EFAEventDecl}) and a normalised guard expression ({@link
 * ConstraintList}) representing the possible values of the EFA variables
 * when this event is taken.
 *
 * @see {@link EFACompiler}.
 * @author Robi Malik
 */

class EFAEvent {

  //#########################################################################
  //# Constructor
  EFAEvent(final EFAEventDecl edecl, final ConstraintList guards)
  {
    mEFAEventDecl = edecl;
    mGuard = guards;
  }


  //#########################################################################
  //# Simple Access
  EFAEventDecl getEFAEventDecl()
  {
    return mEFAEventDecl;
  }

  ConstraintList getGuard()
  {
    return mGuard;
  }

  IdentifierProxy createIdentifier(final ModuleProxyFactory factory)
  {
    final EventDeclProxy decl = mEFAEventDecl.getEventDecl();
    final IdentifierProxy ident = decl.getIdentifier();
    return appendSuffix(factory, ident);
  }

  void setSuffix(final String suffix)
  {
    mSuffix = suffix;
  }


  //#########################################################################
  //# Auxiliary Methods
  private IdentifierProxy appendSuffix(final ModuleProxyFactory factory,
                                       final IdentifierProxy ident)
  {
    final ModuleProxyCloner cloner = factory.getCloner();
    if (ident instanceof QualifiedIdentifierProxy) {
      final QualifiedIdentifierProxy qual = (QualifiedIdentifierProxy) ident;
      final IdentifierProxy base = qual.getBaseIdentifier();
      final IdentifierProxy comp = qual.getComponentIdentifier();
      final IdentifierProxy baseclone =
        (IdentifierProxy) cloner.getClone(base);
      final IdentifierProxy compclone = appendSuffix(factory, comp);
      return factory.createQualifiedIdentifierProxy(baseclone, compclone);
    } else if (mSuffix.length() > 0) {
      final IdentifierProxy base = (IdentifierProxy) cloner.getClone(ident);
      final IdentifierProxy comp =
        factory.createSimpleIdentifierProxy(mSuffix);
      return factory.createQualifiedIdentifierProxy(base, comp);
    } else {
      return (IdentifierProxy) cloner.getClone(ident);
    }
  }


  //#########################################################################
  //# Data Members
  private final EFAEventDecl mEFAEventDecl;
  private final ConstraintList mGuard;
  private String mSuffix;

}
