#!/bin/sh

THIS=`readlink -f $0`
SUPDIR=`dirname $THIS`
PROPFILE=$HOME/.waters

which java > /dev/null 2>&1
if [ "$?" -eq "0" ]; then
    JAVAVERSION=`java -version 2>&1`
    case "$JAVAVERSION" in
        java\ version\ \"1.8*) JAVACMD=java
        ;;
    esac
fi

if [ "$JAVACMD" = "" -a -x $JAVA_HOME/bin/java ]; then
    JAVAVERSION=`$JAVA_HOME/bin/java -version 2>&1`
    case "$JAVAVERSION" in
	java\ version\ \"1.8*) JAVACMD=$JAVA_HOME/bin/java
	;;
    esac
fi

if [ "$JAVACMD" = "" ]; then
    export JAVA_HOME=/usr/lib/jvm/java-8-oracle
    JAVACMD=$JAVA_HOME/bin/java
    if [ ! -x $JAVACMD ]; then
        echo "Cannot find a working installation of Java 1.8."
        echo "Please make sure it is installed and JAVA_HOME points to it."
        exit 1
    fi
fi

if [ ! -r $PROPFILE ]; then
    cp $SUPDIR/waters.properties $PROPFILE
fi

$JAVACMD -classpath "$SUPDIR/Supremica.jar" "-Djava.library.path=$SUPDIR" \
  org.supremica.gui.ide.IDE -p $PROPFILE "$@" 2>&1 >/dev/null
