
/* Generated By:JJTree: Do not edit this line. TransitionParserTreeConstants.java */
package org.jgrafchart.Transitions;



public interface TransitionParserTreeConstants
{

	public int JJTSTART = 0;
	public int JJTVOID = 1;
	public int JJTANDNODE = 2;
	public int JJTORNODE = 3;
	public int JJTEQNODE = 4;
	public int JJTNEQNODE = 5;
	public int JJTLTNODE = 6;
	public int JJTGTNODE = 7;
	public int JJTLENODE = 8;
	public int JJTGENODE = 9;
	public int JJTNOTNODE = 10;
	public int JJTINTEGER = 11;
	public int JJTVAR = 12;
	public int JJTEVUVAR = 13;
	public int JJTEVDVAR = 14;
	public String[] jjtNodeName = { "Start", "void", "AndNode", "OrNode",
									"EQNode", "NEQNode", "LTNode", "GTNode",
									"LENode", "GENode", "NotNode", "Integer",
									"Var", "Evuvar", "Evdvar", };
}
