# -*- Makefile -*-
#############################################################################
#
# Makefile for libwaters.so / waters.dll
#
#############################################################################


#############################################################################
# OS dependent

ifeq "$(HOST_OS)" "linux"
  MKDIR         = mkdir -p $(strip $(1))
else
  MKDIR         = $(if $(wildcard $(1)),,mkdir $(subst /,\,$(1)))
endif


#############################################################################
# Main Rules

# compile the main file

all::			$(LIB)


$(LIB):			$(OBJ)
			$(call MKDIR,$(LIBDIR))
			$(CXX) -shared $(LDFLAGS) -o $@ $^


#############################################################################
# General Rules
export OBJ      = $(CPP:$(SRCDIR)%.cpp=$(OBJDIR)%.o)

$(OBJDIR)/%.o:		$(SRCDIR)/%.cpp
			@$(call MKDIR,$(dir $@))
			$(CXX) -c $(CFLAGS) $(INCDIRS) -o $@ $<


#############################################################################
# Dependencies

$(DEP):			$(CPP) $(HPP) Makefile
			$(CXX) $(ARCH_FLAGS) -MM $(INCDIRS) $(CPP) | \
	sed -e "/:/s|^.*: *$(SRCDIR)/\(.*\)/[^/]*\.cpp|$(OBJDIR)/\1/\0|" > $@

-include $(DEP)

