# -*- Makefile -*-
#############################################################################
#
# Makefile for libwaters.so / waters.dll
#
#############################################################################


#############################################################################
# OS dependent

ifeq "$(OSTYPE)" "linux-gnu"
  OSPATH        = $(strip $(1))
  MKDIR         = mkdir -p $(strip $(1))
else
  OSPATH        = $(subst /,\,$(1))
  MKDIR         = $(if $(wildcard $(1)),,mkdir $(subst /,\,$(1)))
endif


#############################################################################
# Main Rules

# compile the main file

all::			$(LIB)

test::			$(TESTAPP)


$(LIB):			$(OBJ)
			$(call MKDIR,$(LIBDIR))
			$(CXX) -shared $(LDFLAGS) -o $@ $^

$(TESTAPP):		$(LIB) $(TESTOBJ)
			$(call MKDIR,$(BINDIR))
			$(CXX) -o $@ -L$(LIBDIR) -l$(PROJECT) $(TESTOBJ)


#############################################################################
# General Rules
export OBJ      = $(CPP:$(SRCDIR)%.cpp=$(OBJDIR)%.o)

$(OBJDIR)/%.o:		$(SRCDIR)/%.cpp
			@$(call MKDIR,$(dir $@))
			$(CXX) -c $(CFLAGS) $(INCDIRS) -o $@ $<


#############################################################################
# Dependencies

$(DEP):			$(CPP) $(HPP) Makefile
			$(CXX) -MM $(INCDIRS) $(CPP) | \
	sed -e "/:/s|^.*: *$(SRCDIR)/\(.*\)/[^/]*\.cpp|$(OBJDIR)/\1/\0|" > $@

-include $(DEP)

