# -*- Makefile -*-
#############################################################################
#
# Makefile for libwaters.so
#
#############################################################################


#############################################################################
# OS dependent

ifeq "$(OSTYPE)" "linux"
  MKDIR         = mkdir -p
  OSPATH        = $(1)
else
  MKDIR         = mkdir
  OSPATH        = $(subst /,\,$(1))
endif


#############################################################################
# Main Rules

# compile the main file

all::			$(LIB)

test::			$(TESTAPP)


$(LIB):			$(OBJ)
			-$(MKDIR) $(LIBDIR)
			$(CXX) -shared $(LDFLAGS) -o $@ $^

$(TESTAPP):		$(LIB) $(TESTOBJ)
			-$(MKDIR) $(BINDIR)
			$(CXX) -o $@ -L$(LIBDIR) -l$(PROJECT) $(TESTOBJ)


#############################################################################
# General Rules
export OBJ      = $(CPP:$(SRCDIR)%.cpp=$(OBJDIR)%.o)

$(OBJDIR)/%.o:		$(SRCDIR)/%.cpp
			-$(MKDIR) $(call OSPATH,$(dir $@))
			$(CXX) -c $(CFLAGS) $(INCDIRS) -o $@ $<


#############################################################################
# Dependencies

$(DEP):			$(CPP) $(HPP) Makefile
			$(CXX) -MM $(INCDIRS) $(CPP) | \
	sed -e "/:/s|^.*: *$(SRCDIR)/\(.*\)/[^/]*\.cpp|$(OBJDIR)/\1/\0|" > $@

-include $(DEP)

