#!/bin/sh

THIS=`readlink -f $0`
DIR=`dirname $THIS`

export LD_LIBRARY_PATH=$DIR

cd "$DIR/../examples/waters"
java -cp "$DIR/Supremica.jar" -enableassertions \
    net.sourceforge.waters.mbt.translator.ToModelJUnit "$@"

