#!/bin/sh

THIS=`readlink -f $0`
DIR=`dirname $THIS`

export LD_LIBRARY_PATH=$DIR

WPACK="net.sourceforge.waters"
FACTORY="$WPACK.cpp.analysis.NativeModelVerifierFactory"
MEM="-Xmx512m"
ARGS=

for F in "$@"; do
    case $F in
    -Xmx*)
        MEM="$F"
        ;;
    *)
        ARGS="$ARGS \"$F\""
        ;;
    esac
done

eval java -cp "$DIR/Supremica.jar" -enableassertions $MEM net.sourceforge.waters.model.analysis.UnsupTester "$ARGS"
