#!/bin/sh

THIS=`readlink -f $0`
DIR=`dirname $THIS`

export LD_LIBRARY_PATH=$DIR

WPACK="net.sourceforge.waters"
FACTORY="$WPACK.cpp.analysis.NativeModelVerifierFactory"
MEM="-Xmx512m"
ARGS=

for F in "$@"; do
    case $F in
	-bdd)
	    FACTORY="$WPACK.analysis.bdd.BDDModelVerifierFactory"
	    ;;
	-native)
	    FACTORY="$WPACK.cpp.analysis.NativeModelVerifierFactory"
	    ;;
	-comp)
	    FACTORY="$WPACK.analysis.gnonblocking.ComposingModelVerifierFactory"
	    ;;
	-mod|-modular)
	    FACTORY="$WPACK.analysis.modular.ModularModelVerifierFactory"
	    ;;
	-mono)
	    FACTORY="$WPACK.analysis.monolithic.MonolithicModelVerifierFactory"
	    ;;
	-dist)
	    FACTORY="$WPACK.analysis.distributed.DistributedModelVerifierFactory"
	    ;;
	-proj)
	    FACTORY="$WPACK.analysis.modular.ProjectingModelVerifierFactory"
	    ;;
	-conf)
	    CHECK="Conflict"
	    ;;
	-cont)
	    CHECK="Controllability"
	    ;;
	-lang)
	    CHECK="LanguageInclusion"
	    ;;
    -loop)
        CHECK="ControlLoop"
        ;;
    -sic5|-sic6)
        CHECK="Conflict"
        ARGS="$ARGS \"$F\""
        ;;
    -Xmx*)
        MEM="$F"
        ;;
	*)
	    ARGS="$ARGS \"$F\""
	    ;;
    esac
done

OK=1
if [ "" = "$CHECK" ]; then
    echo "No check specified!"
    echo "Available options are: -conf -cont -lang -loop -sic5"
    OK=0
fi

if [ $OK = 1 ]; then
    eval java -cp "$DIR/Supremica.jar" -enableassertions $MEM \
        $WPACK.model.analysis.CommandLineTool $FACTORY $CHECK "$ARGS"
fi
