#!/bin/sh

THIS=`readlink -f $0`
DIR=`dirname $THIS`

export LD_LIBRARY_PATH=$DIR

WPACK="net.sourceforge.waters"
FACTORY="$WPACK.cpp.analysis.NativeModelVerifierFactory"
ARGS=

for F in $@; do
    case $F in
	-bdd)
	    FACTORY="$WPACK.analysis.bdd.BDDModelVerifierFactory"
	    ;;
	-native)
	    FACTORY="$WPACK.cpp.analysis.NativeModelVerifierFactory"
	    ;;
	-comp)
	    FACTORY="$WPACK.analysis.composing.ComposingModelVerifierFactory"
	    ;;
	-mod|-modular)
	    FACTORY="$WPACK.analysis.modular.ModularModelVerifierFactory"
	    ;;
	-mono)
	    FACTORY="$WPACK.analysis.monolithic.MonolithicModelVerifierFactory"
	    ;;
	-proj)
	    FACTORY="$WPACK.analysis.modular.ProjectingModelVerifierFactory"
	    ;;
	-conf)
	    CHECK="Conflict"
	    ;;
	-cont)
	    CHECK="Controllability"
	    ;;
	-lang)
	    CHECK="LanguageInclusion"
	    ;;
	-loop)
	    CHECK="ControlLoop"
	    ;;
	*)
	    ARGS="$ARGS \"$F\""
	    ;;
    esac
done

OK=1
if [ "" = "$CHECK" ]; then
    echo "No check specified!"
    echo "Available options are: -cont -lang"
    OK=0
fi

if [ $OK = 1 ]; then
    eval java -cp "$DIR/Supremica.jar" -enableassertions -Xmx512m \
        $WPACK.model.analysis.CommandLineTool $FACTORY $CHECK $ARGS
fi
