#!/bin/sh

THIS=`readlink -f $0`
DIR=`dirname $THIS`

export LD_LIBRARY_PATH=$DIR

WPACK="net.sourceforge.waters"
FACTORY="Native"
MEM="-Xmx512m"
ARGS=
FACTORY=
MAIN_FACTORY=

for F in "$@"; do
    case $F in
    -bdd)
        FACTORY="BDD"
        ;;
    -comp|-compositional)
        FACTORY="Compositional"
        ;;
#   -dist)
#       FACTORY="$WPACK.analysis.distributed.DistributedModelVerifierFactory"
#       ;;
    -gnb)
        FACTORY="GNB"
        ;;
    -mod|-modular)
        FACTORY="Modular"
        ;;
    -mono)
        FACTORY="Monolithic"
        ;;
    -native)
        FACTORY="Native"
        ;;
    -po)
        FACTORY="PartialOrder"
        ;;
    -proj)
        FACTORY="Projecting"
        ;;
    -trcomp)
        FACTORY="TRCompositional"
        ;;
    -conf)
        CHECK="ConflictChecker"
        ;;
    -cont)
        CHECK="ControllabilityChecker"
        ;;
    -count)
        CHECK="StateCounter"
        ;;
    -lang)
        CHECK="LanguageInclusionChecker"
        ;;
    -loop)
        CHECK="ControlLoopChecker"
        ;;
    -synth)
        CHECK="SupervisorSynthesizer"
        ;;
    -alf)
        CHECK="ControlLoopChecker"
        ARGS="$ARGS \"-wrapper\" \"$WPACK.analysis.sd.SDActivityLoopChecker\""
        ;;
    -sdc2a)
        CHECK="LanguageInclusionChecker"
        ARGS="$ARGS \"-wrapper\" \"$WPACK.analysis.sd.SDCTwoAVerifier\""
        ;;
    -sdc31a)
        CHECK="LanguageInclusionChecker"
        ARGS="$ARGS \"-wrapper\" \"$WPACK.analysis.sd.SDCThree1AVerifier\""
        ;;
    -sdc31b)
        CHECK="LanguageInclusionChecker"
        ARGS="$ARGS \"-wrapper\" \"$WPACK.analysis.sd.SDCThree1BVerifier\""
        ;;
    -sdc4)
        CHECK="LanguageInclusionChecker"
        ARGS="$ARGS \"-wrapper\" \"$WPACK.analysis.sd.SDCFourVerifier\""
        ;;
    -sdspb)
        CHECK="LanguageInclusionChecker"
        ARGS="$ARGS \"-wrapper\" \"$WPACK.analysis.sd.SDSingularProhibitableBehaviorVerifier\""
        ;;
    -sic5)
        CHECK="ConflictChecker"
        ARGS="$ARGS \"-wrapper\" \"$WPACK.analysis.hisc.SICProperty5Verifier\""
        ;;
    -sic6)
        CHECK="ConflictChecker"
        ARGS="$ARGS \"-wrapper\" \"$WPACK.analysis.hisc.SICProperty6Verifier\""
        ;;
    -Xmx*)
        MEM="$F"
        ;;
    *)
        ARGS="$ARGS \"$F\""
        ;;
    esac
    if [ "" != "$FACTORY" ]; then
        if [ "" = "$MAIN_FACTORY" ]; then
            MAIN_FACTORY=$FACTORY
        else
            ARGS="$ARGS -chain $FACTORY"
        fi
        FACTORY=
    fi
done

OK=1
if [ "" = "$CHECK" ]; then
    echo "No check specified!"
    echo "Available options are: -conf -cont -count -lang -loop -synth"
    OK=0
fi

if [ $OK = 1 ]; then
    eval java -cp "$DIR/Supremica.jar" -enableassertions $MEM \
        $WPACK.model.analysis.CommandLineTool $MAIN_FACTORY $CHECK "$ARGS"
fi
