//# -*- indent-tabs-mode: nil  c-basic-offset: 2 -*-
//###########################################################################
//# PROJECT: Waters
//# PACKAGE: net.sourceforge.waters.subject.module
//# CLASS:   BinaryExpressionSubject
//###########################################################################
//# $Id$
//###########################################################################
//# THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY A SCRIPT.
//# DO NOT EDIT.
//###########################################################################

package net.sourceforge.waters.subject.module;

import java.util.Set;

import net.sourceforge.waters.model.base.ProxyVisitor;
import net.sourceforge.waters.model.base.VisitorException;
import net.sourceforge.waters.model.expr.BinaryOperator;
import net.sourceforge.waters.model.module.BinaryExpressionProxy;
import net.sourceforge.waters.model.module.ModuleProxyCloner;
import net.sourceforge.waters.model.module.ModuleProxyVisitor;
import net.sourceforge.waters.model.module.SimpleExpressionProxy;
import net.sourceforge.waters.subject.base.ModelChangeEvent;
import net.sourceforge.waters.subject.base.ProxySubject;
import net.sourceforge.waters.subject.base.RecursiveUndoInfo;
import net.sourceforge.waters.subject.base.ReplacementUndoInfo;
import net.sourceforge.waters.subject.base.Subject;
import net.sourceforge.waters.subject.base.UndoInfo;


/**
 * The subject implementation of the {@link BinaryExpressionProxy} interface.
 *
 * @author Robi Malik
 */

public final class BinaryExpressionSubject
  extends SimpleExpressionSubject
  implements BinaryExpressionProxy
{

  //#########################################################################
  //# Constructors
  /**
   * Creates a new binary expression.
   * @param plainText The original text of the new binary expression, or <CODE>null</CODE>.
   * @param operator The operator of the new binary expression.
   * @param left The left subterm of the new binary expression.
   * @param right The right subterm of the new binary expression.
   */
  public BinaryExpressionSubject(final String plainText,
                                 final BinaryOperator operator,
                                 final SimpleExpressionProxy left,
                                 final SimpleExpressionProxy right)
  {
    super(plainText);
    mOperator = operator;
    mLeft = (SimpleExpressionSubject) left;
    mLeft.setParent(this);
    mRight = (SimpleExpressionSubject) right;
    mRight.setParent(this);
  }

  /**
   * Creates a new binary expression using default values.
   * This constructor creates a binary expression with
   * the original text set to <CODE>null</CODE>.
   * @param operator The operator of the new binary expression.
   * @param left The left subterm of the new binary expression.
   * @param right The right subterm of the new binary expression.
   */
  public BinaryExpressionSubject(final BinaryOperator operator,
                                 final SimpleExpressionProxy left,
                                 final SimpleExpressionProxy right)
  {
    this(null,
         operator,
         left,
         right);
  }


  //#########################################################################
  //# Cloning and Assigning
  @Override
  public BinaryExpressionSubject clone()
  {
    final ModuleProxyCloner cloner =
      ModuleSubjectFactory.getCloningInstance();
    return (BinaryExpressionSubject) cloner.getClone(this);
  }

  @Override
  public ModelChangeEvent assignMember(final int index,
                                       final Object oldValue,
                                       final Object newValue)
  {
    if (index <= 1) {
      return super.assignMember(index, oldValue, newValue);
    } else {
      switch (index) {
      case 2:
        mOperator = (BinaryOperator) newValue;
        return ModelChangeEvent.createStateChanged(this);
      case 3:
        mLeft.setParent(null);
        mLeft = (SimpleExpressionSubject) newValue;
        mLeft.setParent(this);
        return ModelChangeEvent.createStateChanged(this);
      case 4:
        mRight.setParent(null);
        mRight = (SimpleExpressionSubject) newValue;
        mRight.setParent(this);
        return ModelChangeEvent.createStateChanged(this);
      default:
        return null;
      }
    }
  }

  @Override
  protected void collectUndoInfo(final ProxySubject newState,
                                 final RecursiveUndoInfo info,
                                 final Set<? extends Subject> boundary)
  {
    super.collectUndoInfo(newState, info, boundary);
    final BinaryExpressionSubject downcast =
      (BinaryExpressionSubject) newState;
    if (!mOperator.equals(downcast.mOperator)) {
      final UndoInfo step2 =
        new ReplacementUndoInfo(2, mOperator, downcast.mOperator);
      info.add(step2);
    }
    if (mLeft.getClass() == downcast.mLeft.getClass()) {
      final UndoInfo step3 = mLeft.createUndoInfo(downcast.mLeft, boundary);
      if (step3 != null) {
        info.add(step3);
      }
    } else {
      final SimpleExpressionSubject clone3 = downcast.mLeft.clone();
      final UndoInfo step3 = new ReplacementUndoInfo(3, mLeft, clone3);
      info.add(step3);
    }
    if (mRight.getClass() == downcast.mRight.getClass()) {
      final UndoInfo step4 = mRight.createUndoInfo(downcast.mRight, boundary);
      if (step4 != null) {
        info.add(step4);
      }
    } else {
      final SimpleExpressionSubject clone4 = downcast.mRight.clone();
      final UndoInfo step4 = new ReplacementUndoInfo(4, mRight, clone4);
      info.add(step4);
    }
  }


  //#########################################################################
  //# Comparing
  public Class<BinaryExpressionProxy> getProxyInterface()
  {
    return BinaryExpressionProxy.class;
  }


  //#########################################################################
  //# Interface net.sourceforge.waters.model.base.Proxy
  public Object acceptVisitor(final ProxyVisitor visitor)
    throws VisitorException
  {
    final ModuleProxyVisitor downcast = (ModuleProxyVisitor) visitor;
    return downcast.visitBinaryExpressionProxy(this);
  }


  //#########################################################################
  //# Interface net.sourceforge.waters.model.module.BinaryExpressionProxy
  public BinaryOperator getOperator()
  {
    return mOperator;
  }

  public SimpleExpressionSubject getLeft()
  {
    return mLeft;
  }

  public SimpleExpressionSubject getRight()
  {
    return mRight;
  }


  //#########################################################################
  //# Setters
  /**
   * Sets the operator of this expression.
   */
  public void setOperator(final BinaryOperator operator)
  {
    if (mOperator.equals(operator)) {
      return;
    }
    mOperator = operator;
    fireStateChanged();
  }

  /**
   * Sets the left subterm of this expression.
   */
  public void setLeft(final SimpleExpressionSubject left)
  {
    if (mLeft == left) {
      return;
    }
    left.setParent(this);
    mLeft.setParent(null);
    mLeft = left;
    fireStateChanged();
  }

  /**
   * Sets the right subterm of this expression.
   */
  public void setRight(final SimpleExpressionSubject right)
  {
    if (mRight == right) {
      return;
    }
    right.setParent(this);
    mRight.setParent(null);
    mRight = right;
    fireStateChanged();
  }


  //#########################################################################
  //# Data Members
  private BinaryOperator mOperator;
  private SimpleExpressionSubject mLeft;
  private SimpleExpressionSubject mRight;

}
