//# -*- indent-tabs-mode: nil  c-basic-offset: 2 -*-
//###########################################################################
//# THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY A SCRIPT.
//# DO NOT EDIT.
//###########################################################################
//# Copyright (C) 2004-2020 Robi Malik
//###########################################################################
//# This file is part of Waters.
//# Waters is free software: you can redistribute it and/or modify it under
//# the terms of the GNU General Public License as published by the Free
//# Software Foundation, either version 2 of the License, or (at your option)
//# any later version.
//# Waters is distributed in the hope that it will be useful, but WITHOUT ANY
//# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
//# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
//# details.
//# You should have received a copy of the GNU General Public License along
//# with Waters. If not, see <http://www.gnu.org/licenses/>.
//#
//# Linking Waters statically or dynamically with other modules is making a
//# combined work based on Waters. Thus, the terms and conditions of the GNU
//# General Public License cover the whole combination.
//# In addition, as a special exception, the copyright holders of Waters give
//# you permission to combine Waters with code included in the standard
//# release of Supremica under the Supremica Software License Agreement (or
//# modified versions of such code, with unchanged license). You may copy and
//# distribute such a system following the terms of the GNU GPL for Waters and
//# the licenses of the other code concerned.
//# Note that people who make modified versions of Waters are not obligated to
//# grant this special exception for their modified versions; it is their
//# choice whether to do so. The GNU General Public License gives permission
//# to release a modified version without this exception; this exception also
//# makes it possible to release a modified version which carries forward this
//# exception.
//###########################################################################

package net.sourceforge.waters.subject.module;

import java.util.Collection;
import java.util.Collections;
import java.util.Set;

import net.sourceforge.waters.model.base.ProxyTools;
import net.sourceforge.waters.model.base.ProxyVisitor;
import net.sourceforge.waters.model.base.VisitorException;
import net.sourceforge.waters.model.module.EdgeProxy;
import net.sourceforge.waters.model.module.GraphProxy;
import net.sourceforge.waters.model.module.LabelBlockProxy;
import net.sourceforge.waters.model.module.ModuleProxyCloner;
import net.sourceforge.waters.model.module.ModuleProxyVisitor;
import net.sourceforge.waters.model.module.NodeProxy;
import net.sourceforge.waters.subject.base.ArrayListSubject;
import net.sourceforge.waters.subject.base.IndexedSetSubject;
import net.sourceforge.waters.subject.base.ListSubject;
import net.sourceforge.waters.subject.base.ModelChangeEvent;
import net.sourceforge.waters.subject.base.MutableSubject;
import net.sourceforge.waters.subject.base.ProxySubject;
import net.sourceforge.waters.subject.base.RecursiveUndoInfo;
import net.sourceforge.waters.subject.base.ReplacementUndoInfo;
import net.sourceforge.waters.subject.base.Subject;
import net.sourceforge.waters.subject.base.UndoInfo;


/**
 * The subject implementation of the {@link GraphProxy} interface.
 *
 * @author Robi Malik
 */

public final class GraphSubject
  extends MutableSubject
  implements GraphProxy
{

  //#########################################################################
  //# Constructors
  /**
   * Creates a new graph.
   * @param deterministic The determinism status of the new graph.
   * @param blockedEvents The list of blocked events of the new graph, or <CODE>null</CODE>.
   * @param nodes The set of nodes of the new graph, or <CODE>null</CODE> if empty.
   * @param edges The collection of edges of the new graph, or <CODE>null</CODE> if empty.
   */
  public GraphSubject(final boolean deterministic,
                      final LabelBlockProxy blockedEvents,
                      final Collection<? extends NodeProxy> nodes,
                      final Collection<? extends EdgeProxy> edges)
  {
    mIsDeterministic = deterministic;
    mBlockedEvents = (LabelBlockSubject) blockedEvents;
    if (mBlockedEvents != null) {
      mBlockedEvents.setParent(this);
    }
    if (nodes == null) {
      mNodes = new NodeSetSubject();
    } else {
      mNodes = new NodeSetSubject(nodes);
    }
    mNodes.setParent(this);
    if (edges == null) {
      mEdges = new ArrayListSubject<EdgeSubject>();
    } else {
      mEdges = new ArrayListSubject<EdgeSubject>
        (edges, EdgeSubject.class);
    }
    mEdges.setParent(this);
  }

  /**
   * Creates a new graph using default values.
   * This constructor creates a graph with
   * the determinism status set to <CODE>true</CODE>,
   * the list of blocked events set to <CODE>null</CODE>,
   * an empty set of nodes, and
   * an empty collection of edges.
   */
  public GraphSubject()
  {
    this(true,
         null,
         null,
         null);
  }


  //#########################################################################
  //# Cloning and Assigning
  @Override
  public GraphSubject clone()
  {
    final ModuleProxyCloner cloner =
      ModuleSubjectFactory.getCloningInstance();
    return (GraphSubject) cloner.getClone(this);
  }

  @Override
  public ModelChangeEvent assignMember(final int index,
                                       final Object oldValue,
                                       final Object newValue)
  {
    if (index <= 0) {
      return super.assignMember(index, oldValue, newValue);
    } else {
      switch (index) {
      case 1:
        mIsDeterministic = (Boolean) newValue;
        return ModelChangeEvent.createStateChanged(this);
      case 2:
        if (mBlockedEvents != null) {
          mBlockedEvents.setParent(null);
        }
        mBlockedEvents = (LabelBlockSubject) newValue;
        if (mBlockedEvents != null) {
          mBlockedEvents.setParent(this);
        }
        return ModelChangeEvent.createStateChanged(this);
      default:
        return null;
      }
    }
  }

  @Override
  protected void collectUndoInfo(final ProxySubject newState,
                                 final RecursiveUndoInfo info,
                                 final Set<? extends Subject> boundary)
  {
    super.collectUndoInfo(newState, info, boundary);
    final GraphSubject downcast = (GraphSubject) newState;
    if (mIsDeterministic != downcast.mIsDeterministic) {
      final UndoInfo step1 =
        new ReplacementUndoInfo(1, mIsDeterministic, downcast.mIsDeterministic);
      info.add(step1);
    }
    final boolean null2a = mBlockedEvents == null;
    final boolean null2b = downcast.mBlockedEvents == null;
    if (null2a != null2b) {
      if (boundary ==  null || !boundary.contains(mBlockedEvents)) {
        final LabelBlockSubject clone2 =
          ProxyTools.clone(downcast.mBlockedEvents);
        final UndoInfo step2 =
          new ReplacementUndoInfo(2, mBlockedEvents, clone2);
        info.add(step2);
      }
    } else if (!null2a) {
      final UndoInfo step2 =
        mBlockedEvents.createUndoInfo(downcast.mBlockedEvents, boundary);
      if (step2 != null) {
        info.add(step2);
      }
    }
    final UndoInfo step3 = mNodes.createUndoInfo(downcast.mNodes, boundary);
    if (step3 != null) {
      info.add(step3);
    }
    final UndoInfo step4 = mEdges.createUndoInfo(downcast.mEdges, boundary);
    if (step4 != null) {
      info.add(step4);
    }
  }


  //#########################################################################
  //# Comparing
  public Class<GraphProxy> getProxyInterface()
  {
    return GraphProxy.class;
  }


  //#########################################################################
  //# Interface net.sourceforge.waters.model.base.Proxy
  public Object acceptVisitor(final ProxyVisitor visitor)
    throws VisitorException
  {
    final ModuleProxyVisitor downcast = (ModuleProxyVisitor) visitor;
    return downcast.visitGraphProxy(this);
  }


  //#########################################################################
  //# Interface net.sourceforge.waters.model.module.GraphProxy
  public boolean isDeterministic()
  {
    return mIsDeterministic;
  }

  public LabelBlockSubject getBlockedEvents()
  {
    return mBlockedEvents;
  }

  public Set<NodeProxy> getNodes()
  {
    final Set<?> precast = mNodes;
    @SuppressWarnings("unchecked")
    final Set<NodeProxy> downcast = (Set<NodeProxy>) precast;
    return Collections.unmodifiableSet(downcast);
  }

  public Collection<EdgeProxy> getEdges()
  {
    final Collection<?> precast = mEdges;
    @SuppressWarnings("unchecked")
    final Collection<EdgeProxy> downcast = (Collection<EdgeProxy>) precast;
    return Collections.unmodifiableCollection(downcast);
  }


  //#########################################################################
  //# Setters
  /**
   * Sets the determinism status of this graph.
   */
  public void setDeterministic(final boolean deterministic)
  {
    if (mIsDeterministic == deterministic) {
      return;
    }
    mIsDeterministic = deterministic;
    fireStateChanged();
  }

  /**
   * Sets the list of blocked events of this graph.
   */
  public void setBlockedEvents(final LabelBlockSubject blockedEvents)
  {
    if (mBlockedEvents == blockedEvents) {
      return;
    }
    if (blockedEvents != null) {
      blockedEvents.setParent(this);
    }
    if (mBlockedEvents != null) {
      mBlockedEvents.setParent(null);
    }
    mBlockedEvents = blockedEvents;
    fireStateChanged();
  }

  /**
   * Gets the modifiable set of nodes of this graph.
   */
  public IndexedSetSubject<NodeSubject> getNodesModifiable()
  {
    return mNodes;
  }

  /**
   * Gets the modifiable collection of edges of this graph.
   */
  public ListSubject<EdgeSubject> getEdgesModifiable()
  {
    return mEdges;
  }


  //#########################################################################
  //# Data Members
  private boolean mIsDeterministic;
  private LabelBlockSubject mBlockedEvents;
  private IndexedSetSubject<NodeSubject> mNodes;
  private ListSubject<EdgeSubject> mEdges;

}
