//# -*- indent-tabs-mode: nil  c-basic-offset: 2 -*-
//###########################################################################
//# PROJECT: Waters
//# PACKAGE: net.sourceforge.waters.subject.module
//# CLASS:   IdentifierSubject
//###########################################################################
//# $Id: IdentifierSubject.java,v 1.14 2008-02-15 07:31:49 robi Exp $
//###########################################################################
//# THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY A SCRIPT.
//# DO NOT EDIT.
//###########################################################################

package net.sourceforge.waters.subject.module;

import net.sourceforge.waters.model.module.IdentifierProxy;


/**
 * The subject implementation of the {@link IdentifierProxy} interface.
 *
 * @author Robi Malik
 */

public abstract class IdentifierSubject
  extends SimpleExpressionSubject
  implements IdentifierProxy
{

  //#########################################################################
  //# Constructors
  /**
   * Creates a new identifier.
   * @param plainText The original text of the new identifier, or <CODE>null</CODE>.
   */
  protected IdentifierSubject(final String plainText)
  {
    super(plainText);
  }

  /**
   * Creates a new identifier using default values.
   * This constructor creates an identifier with
   * the original text set to <CODE>null</CODE>.
   */
  protected IdentifierSubject()
  {
    this(null);
  }


  //#########################################################################
  //# Cloning
  public IdentifierSubject clone()
  {
    return (IdentifierSubject) super.clone();
  }


  //#########################################################################
  //# Interface java.lang.Comparable<IdentifierProxy>
  public int compareTo(final IdentifierProxy partner)
  {
    return toString().compareTo(partner.toString());
  }

}
