//# -*- indent-tabs-mode: nil  c-basic-offset: 2 -*-
//###########################################################################
//# THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY A SCRIPT.
//# DO NOT EDIT.
//###########################################################################
//# Copyright (C) 2004-2023 Robi Malik
//###########################################################################
//# This file is part of Waters.
//# Waters is free software: you can redistribute it and/or modify it under
//# the terms of the GNU General Public License as published by the Free
//# Software Foundation, either version 2 of the License, or (at your option)
//# any later version.
//# Waters is distributed in the hope that it will be useful, but WITHOUT ANY
//# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
//# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
//# details.
//# You should have received a copy of the GNU General Public License along
//# with Waters. If not, see <http://www.gnu.org/licenses/>.
//#
//# Linking Waters statically or dynamically with other modules is making a
//# combined work based on Waters. Thus, the terms and conditions of the GNU
//# General Public License cover the whole combination.
//# In addition, as a special exception, the copyright holders of Waters give
//# you permission to combine Waters with code included in the standard
//# release of Supremica under the Supremica Software License Agreement (or
//# modified versions of such code, with unchanged license). You may copy and
//# distribute such a system following the terms of the GNU GPL for Waters and
//# the licenses of the other code concerned.
//# Note that people who make modified versions of Waters are not obligated to
//# grant this special exception for their modified versions; it is their
//# choice whether to do so. The GNU General Public License gives permission
//# to release a modified version without this exception; this exception also
//# makes it possible to release a modified version which carries forward this
//# exception.
//###########################################################################

package net.sourceforge.waters.subject.module;

import java.util.Set;

import net.sourceforge.waters.model.module.IdentifiedProxy;
import net.sourceforge.waters.model.module.IdentifierProxy;
import net.sourceforge.waters.model.module.ModuleProxyCloner;
import net.sourceforge.waters.subject.base.AbstractNamedSubject;
import net.sourceforge.waters.subject.base.ModelChangeEvent;
import net.sourceforge.waters.subject.base.ProxySubject;
import net.sourceforge.waters.subject.base.RecursiveUndoInfo;
import net.sourceforge.waters.subject.base.ReplacementUndoInfo;
import net.sourceforge.waters.subject.base.Subject;
import net.sourceforge.waters.subject.base.UndoInfo;


/**
 * The subject implementation of the {@link IdentifiedProxy} interface.
 *
 * @author Robi Malik
 */

public abstract class IdentifiedSubject
  extends AbstractNamedSubject
  implements IdentifiedProxy
{

  //#########################################################################
  //# Constructors
  /**
   * Creates a new identified object.
   * @param identifier The identifier defining the name of the new identified object.
   */
  protected IdentifiedSubject(final IdentifierProxy identifier)
  {
    mIdentifier = (IdentifierSubject) identifier;
    mIdentifier.setParent(this);
  }


  //#########################################################################
  //# Cloning and Assigning
  @Override
  public IdentifiedSubject clone()
  {
    final ModuleProxyCloner cloner =
      ModuleSubjectFactory.getCloningInstance();
    return (IdentifiedSubject) cloner.getClone(this);
  }

  @Override
  public ModelChangeEvent assignMember(final int index,
                                       final Object oldValue,
                                       final Object newValue)
  {
    if (index <= 0) {
      return super.assignMember(index, oldValue, newValue);
    } else {
      switch (index) {
      case 1:
        mIdentifier.setParent(null);
        mIdentifier = (IdentifierSubject) newValue;
        mIdentifier.setParent(this);
        return ModelChangeEvent.createStateChanged(this);
      default:
        return null;
      }
    }
  }

  @Override
  protected void collectUndoInfo(final ProxySubject newState,
                                 final RecursiveUndoInfo info,
                                 final Set<? extends Subject> boundary)
  {
    super.collectUndoInfo(newState, info, boundary);
    final IdentifiedSubject downcast = (IdentifiedSubject) newState;
    if (mIdentifier.getClass() == downcast.mIdentifier.getClass()) {
      final UndoInfo step1 =
        mIdentifier.createUndoInfo(downcast.mIdentifier, boundary);
      if (step1 != null) {
        info.add(step1);
      }
    } else {
      final IdentifierSubject clone1 = downcast.mIdentifier.clone();
      final UndoInfo step1 = new ReplacementUndoInfo(1, mIdentifier, clone1);
      info.add(step1);
    }
  }


  //#########################################################################
  //# Interface net.sourceforge.waters.model.module.IdentifiedProxy
  public IdentifierSubject getIdentifier()
  {
    return mIdentifier;
  }


  //#########################################################################
  //# Setters
  /**
   * Sets the identifier defining the name of this object.
   */
  public void setIdentifier(final IdentifierSubject identifier)
  {
    if (mIdentifier == identifier) {
      return;
    }
    identifier.setParent(this);
    mIdentifier.setParent(null);
    mIdentifier = identifier;
    fireStateChanged();
  }


  //#########################################################################
  //# Interface net.sourceforge.waters.model.base.NamedProxy
  public String getName()
  {
    return mIdentifier.toString();
  }


  //#########################################################################
  //# Data Members
  private IdentifierSubject mIdentifier;

}
