//# -*- indent-tabs-mode: nil  c-basic-offset: 2 -*-
//###########################################################################
//# PROJECT: Waters
//# PACKAGE: net.sourceforge.waters.subject.module
//# CLASS:   SimpleExpressionSubject
//###########################################################################
//# $Id: SimpleExpressionSubject.java,v 1.10 2007-07-03 11:20:53 robi Exp $
//###########################################################################
//# THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY A SCRIPT.
//# DO NOT EDIT.
//###########################################################################

package net.sourceforge.waters.subject.module;

import net.sourceforge.waters.model.base.Proxy;
import net.sourceforge.waters.model.base.ProxyTools;
import net.sourceforge.waters.model.module.ModuleProxyCloner;
import net.sourceforge.waters.model.module.SimpleExpressionProxy;
import net.sourceforge.waters.subject.base.ProxySubject;


/**
 * The subject implementation of the {@link SimpleExpressionProxy} interface.
 *
 * @author Robi Malik
 */

public abstract class SimpleExpressionSubject
  extends ExpressionSubject
  implements SimpleExpressionProxy
{

  //#########################################################################
  //# Constructors
  /**
   * Creates a new simple expression.
   * @param plainText The original text of the new simple expression, or <CODE>null</CODE>.
   */
  protected SimpleExpressionSubject(final String plainText)
  {
    mPlainText = plainText;
  }

  /**
   * Creates a new simple expression using default values.
   * This constructor creates a simple expression with
   * the original text set to <CODE>null</CODE>.
   */
  protected SimpleExpressionSubject()
  {
    this(null);
  }


  //#########################################################################
  //# Cloning and Assigning
  public SimpleExpressionSubject clone()
  {
    final ModuleProxyCloner cloner =
      ModuleSubjectFactory.getCloningInstance();
    return (SimpleExpressionSubject) cloner.getClone(this);
  }

  public boolean assignFrom(final ProxySubject partner)
  {
    if (this != partner) {
      final SimpleExpressionSubject downcast =
        (SimpleExpressionSubject) partner;
      boolean change = super.assignFrom(partner);
      final String plainText = downcast.getPlainText();
      if (mPlainText != plainText) {
        mPlainText = plainText;
        fireGeometryChanged(mPlainText);
      }
      return change;
    } else {
      return false;
    }
  }


  //#########################################################################
  //# Equality and Hashcode
  public boolean equalsWithGeometry(final Proxy partner)
  {
    if (super.equalsByContents(partner)) {
      final SimpleExpressionProxy downcast = (SimpleExpressionProxy) partner;
      return
        ProxyTools.equals(mPlainText, downcast.getPlainText());
    } else {
      return false;
    }
  }

  public int hashCodeWithGeometry()
  {
    int result = super.hashCodeByContents();
    result *= 5;
    result += ProxyTools.hashCode(mPlainText);
    return result;
  }


  //#########################################################################
  //# Interface net.sourceforge.waters.model.module.SimpleExpressionProxy
  public String getPlainText()
  {
    return mPlainText;
  }


  //#########################################################################
  //# Setters
  /**
   * Sets the original text of this expression.
   */
  public void setPlainText(final String plainText)
  {
    if (mPlainText.equals(plainText)) {
      return;
    }
    mPlainText = plainText;
    fireGeometryChanged(mPlainText);
  }


  //#########################################################################
  //# Data Members
  private String mPlainText;

}
