/* Generated By:JJTree: Do not edit this line. ACTConstant.java */
package org.jgrafchart.Actions;

import com.nwoods.jgo.*;
import java.util.*;

public class ACTConstant
	extends SimpleNode
{
	protected String name;
	public boolean val;

	public ACTConstant(int id)
	{
		super(id);
	}

	public ACTConstant(ActionParser p, int id)
	{
		super(p, id);
	}

	public void setName(String n)
	{
		name = n;

		if (n.compareTo("0") == 0)
		{
			val = false;
		}
		else
		{
			val = true;
		}
	}

	public boolean evaluateBoolean()
	{
		return val;
	}

	public int evaluateInt()
	{
		if (val)
		{
			return 1;
		}
		else
		{
			return 0;
		}
	}

	public String toString()
	{
		return name;
	}

	public boolean compile(ArrayList doc)
	{
		return true;
	}

	public void executeNormalActions(boolean b) {}

	public void executeStoredActions() {}
}
