/* Generated By:JJTree: Do not edit this line. ACTLENode.java */
package org.jgrafchart.Actions;

import java.util.*;

public class ACTLENode
	extends SimpleNode
{
	public ACTLENode(int id)
	{
		super(id);
	}

	public ACTLENode(ActionParser p, int id)
	{
		super(p, id);
	}

	public boolean compile(ArrayList doc)
	{
		boolean result = true;

		result = result && jjtGetChild(0).compile(doc);
		result = result && jjtGetChild(1).compile(doc);

		return result;
	}

	public boolean evaluateBoolean()
	{
		boolean res;

		res = jjtGetChild(0).evaluateInt() <= jjtGetChild(1).evaluateInt();

		return res;
	}
}
