
/* Generated By:JJTree: Do not edit this line. ACTNotNode.java */
package org.jgrafchart.Actions;



import java.util.*;


public class ACTNotNode
	extends SimpleNode
{

	public ACTNotNode(int id)
	{
		super(id);
	}

	public ACTNotNode(ActionParser p, int id)
	{
		super(p, id);
	}

	public boolean compile(ArrayList doc)
	{
		return jjtGetChild(0).compile(doc);
	}

	public boolean evaluateBoolean()
	{

		boolean res;

		res = !jjtGetChild(0).evaluateBoolean();

		return res;
	}
}
