/* Generated By:JJTree: Do not edit this line. ACTNormalNode.java */
package org.jgrafchart.Actions;

import java.util.*;
import com.nwoods.jgo.*;
import org.jgrafchart.Referencable;
import org.jgrafchart.DigitalOut;
import java.util.*;

public class ACTNormalNode
	extends SimpleNode
{
	public ACTNormalNode(int id)
	{
		super(id);
	}

	public ACTNormalNode(ActionParser p, int id)
	{
		super(p, id);
	}

	public boolean compile(ArrayList doc)
	{
		return jjtGetChild(0).compile(doc);
	}

	public void executeStoredActions() {}

	public void executeNormalActions(boolean b)
	{

		// System.out.println("ACTNormalNode.executeNormalActions");
		Referencable out = (Referencable) ((ACTVariable) jjtGetChild(0)).out;
		DigitalOut outw = (DigitalOut) out;

		outw.setNormalAction(b);
	}

	public boolean evaluateBoolean()
	{
		return false;
	}

	public int evaulateInt()
	{
		return 0;
	}
}
