//# -*- indent-tabs-mode: nil  c-basic-offset: 2 -*-
//###########################################################################
//# PROJECT: Waters
//# PACKAGE: net.sourceforge.waters.gui.observer
//# CLASS:   SelectionChangedEvent
//###########################################################################
//# $Id$
//###########################################################################

package net.sourceforge.waters.gui.observer;


/**
 * <P>A notification sent by a component that its selection has changed.</P>
 *
 * <P>This notification is generated by various component in the module
 * editor GUI that maintain a collection of objects with changeable
 * selection. This includes the graph editor panel ({@link
 * net.sourceforge.waters.gui.ControlledSurface ControlledSurface}) as well
 * as the component and event list displays.</P>
 *
 * @author Robi Malik
 */

public class SelectionChangedEvent
  extends EditorChangedEvent
{

  //#########################################################################
  //# Constructors
  public SelectionChangedEvent(final Object source)
  {
    super(source);
  }


  //#########################################################################
  //# Simple Access
  public EditorChangedEvent.Kind getKind()
  {
    return EditorChangedEvent.Kind.SELECTION_CHANGED;
  }


  //#########################################################################
  //# Class Constants
  private static final long serialVersionUID = 1L;

}
